import {useEffect,useRef,useState,useId,useCallback,useMemo} from 'react';
import {attachmentLimits,attachmentMedia,type AttachmentDto,type AttachmentPurpose,type AttachmentIntent,type ExpenseAttachmentDto,type ExpenseAttachmentIntent} from '@shippingco/shared';
import {Msym} from './Icon';
import {attachmentIntent,expenseAttachmentIntent,type AttachmentClient,type ExpenseAttachmentClient,type AttachmentEvidence} from '../../data-access/attachments';
import type {createScopeRuntime} from '../../data-access/scope-runtime';
import {ApiFailure,recoveryFor} from '../../data-access/errors';
import {downscaleImageBlob} from '../../utils/image';
type Client<D,I>={list:()=>Promise<D[]>;initiate:(body:I,key:string)=>Promise<D>;upload:(id:string,file:Blob,progress:(n:number)=>void,signal:AbortSignal)=>Promise<D>;finalize:(id:string,key:string)=>Promise<D>;cancel:(id:string,key:string)=>Promise<D>;bytes:(id:string,key:string)=>Promise<Blob>};
type Entry<D,I>={localId:string;file?:Blob;preview?:string;dto?:D;intent?:I;progress:number;phase:'selected'|'uploading'|'scanning'|'ready'|'failed'|'unsafe'|'canceling'|'cancel_failed'|'ended';error?:string;controller:AbortController;initiateKey:string;finalizeKey:string;cancelKey:string;uploaded:boolean;initiationAttempted:boolean};
export interface AttachmentUploaderProps{client:AttachmentClient;runtime:ReturnType<typeof createScopeRuntime>;purpose?:AttachmentPurpose;parcelId?:string;onChange?:(items:AttachmentDto[])=>void;prepareImage?:typeof downscaleImageBlob}
export function AttachmentUploader({client,runtime,purpose='shipment_evidence',parcelId,onChange,prepareImage}:AttachmentUploaderProps){const bound=useMemo(()=>({...client,list:()=>client.list(parcelId)}),[client,parcelId]);return <PrivateAttachments<AttachmentDto,AttachmentIntent> client={bound} runtime={runtime} makeIntent={file=>attachmentIntent(file,purpose,parcelId)} onChange={onChange} prepareImage={prepareImage} parentLabel="booking"/>;}
export interface ExpenseAttachmentUploaderProps{client:ExpenseAttachmentClient;runtime:ReturnType<typeof createScopeRuntime>;canUpload:boolean;canCancel:boolean;locked:boolean;onActivity?:(busy:boolean)=>void;prepareImage?:typeof downscaleImageBlob}
export function ExpenseAttachmentUploader({client,runtime,canUpload,canCancel,locked,onActivity,prepareImage}:ExpenseAttachmentUploaderProps){return <PrivateAttachments<ExpenseAttachmentDto,ExpenseAttachmentIntent> client={client} runtime={runtime} makeIntent={expenseAttachmentIntent} allowUploads={canUpload} allowCancel={canCancel} locked={locked} onActivity={onActivity} prepareImage={prepareImage} parentLabel="expense request"/>;}
const kinds=[{kind:'image',label:'Photo',icon:'photo_camera',accept:'image/jpeg,image/png'},{kind:'video',label:'Video',icon:'videocam',accept:'video/mp4'},{kind:'audio',label:'Voice note',icon:'mic',accept:'audio/mpeg,audio/wav'}] as const;
function PrivateAttachments<D extends AttachmentEvidence,I>({client,runtime,makeIntent,onChange,onActivity,prepareImage=downscaleImageBlob,parentLabel,allowUploads=true,allowCancel=true,locked=false}:{client:Client<D,I>;runtime:ReturnType<typeof createScopeRuntime>;makeIntent:(file:Blob)=>Promise<I>;onChange?:(items:D[])=>void;onActivity?:(busy:boolean)=>void;prepareImage?:typeof downscaleImageBlob;parentLabel:string;allowUploads?:boolean;allowCancel?:boolean;locked?:boolean}){
 const [entries,setEntries]=useState<Entry<D,I>[]>([]),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[loadFailed,setLoadFailed]=useState(false),[revision,setRevision]=useState(0);
 const current=useRef<Entry<D,I>[]>([]),mounted=useRef(true),activity=useRef(false),label=useId(),inputs=useRef<Record<string,HTMLInputElement|null>>({}),callbacks=useRef({onChange,onActivity}),capabilities=useRef({allowUploads,allowCancel});callbacks.current={onChange,onActivity};capabilities.current={allowUploads,allowCancel};
 const paint=useCallback(()=>{if(!mounted.current)return;setEntries([...current.current]);callbacks.current.onChange?.(current.current.flatMap(e=>e.dto?.state==='ready'?[e.dto]:[]));const busy=(capabilities.current.allowUploads||capabilities.current.allowCancel)&&current.current.some(e=>['selected','uploading','scanning','canceling','cancel_failed'].includes(e.phase)||e.phase==='failed'&&(!!e.file||e.uploaded));if(activity.current!==busy){activity.current=busy;callbacks.current.onActivity?.(busy);}},[]);
 const exists=(e:Entry<D,I>)=>mounted.current&&current.current.includes(e),active=(e:Entry<D,I>)=>exists(e)&&!e.controller.signal.aborted;
 const revoke=useCallback((e:Entry<D,I>)=>{if(e.preview)URL.revokeObjectURL(e.preview);e.preview=undefined;},[]);
 const purge=useCallback(()=>{for(const e of current.current){e.controller.abort();if(e.preview)URL.revokeObjectURL(e.preview);}current.current=[];if(activity.current){activity.current=false;callbacks.current.onActivity?.(false);}if(mounted.current){setEntries([]);callbacks.current.onChange?.([]);setMessage('');setLoading(false);}},[]);
 const fromDto=useCallback((dto:D):Entry<D,I>=>({localId:dto.id,dto,progress:100,phase:dto.state==='ready'?'ready':dto.state==='rejected'?'unsafe':['canceled','deleted','cleanup_pending'].includes(dto.state)?'ended':'failed',error:dto.state==='quarantined'?'Validation pending. Retry when ready.':dto.state==='pending_upload'?'Upload metadata saved. Cancel it if the original file is unavailable.':dto.state==='rejected'?'This file did not pass safety validation.':undefined,controller:new AbortController(),initiateKey:crypto.randomUUID(),finalizeKey:crypto.randomUUID(),cancelKey:crypto.randomUUID(),uploaded:dto.state==='quarantined',initiationAttempted:true}),[]);
 useEffect(()=>{mounted.current=true;purge();const unsubscribe=runtime.onInvalidate(()=>purge());return()=>{unsubscribe();mounted.current=false;purge();};},[client,runtime,paint,purge]);
 useEffect(()=>{let live=true;const ticket=runtime.ticket();setLoading(true);setLoadFailed(false);void client.list().then(items=>{if(!live||!runtime.isCurrent(ticket))return;const existing=current.current;for(const e of existing){const dto=items.find(d=>d.id===e.dto?.id);if(dto){e.dto=dto;if(dto.state==='ready'){e.phase='ready';e.file=undefined;e.error=undefined;if(e.controller.signal.aborted)e.controller=new AbortController();}else if(['canceled','deleted','cleanup_pending'].includes(dto.state)){e.phase='ended';e.file=undefined;e.error=undefined;revoke(e);}else if(dto.state==='rejected'){e.phase='unsafe';e.file=undefined;revoke(e);}}}current.current=[...existing,...items.filter(dto=>!existing.some(e=>e.dto?.id===dto.id)).map(fromDto)];paint();setLoading(false);}).catch(()=>{if(live&&runtime.isCurrent(ticket)){setMessage('Attachments could not be loaded.');setLoading(false);setLoadFailed(true);}});return()=>{live=false;};},[client,runtime,revision,paint,fromDto,revoke]);
 async function run(e:Entry<D,I>){if(locked||!capabilities.current.allowUploads||!active(e))return;e.error=undefined;e.phase=e.uploaded?'scanning':'uploading';paint();try{if(!e.dto){if(!e.file)throw new Error();e.intent??=await makeIntent(e.file);if(!active(e))return;e.initiationAttempted=true;e.dto=await client.initiate(e.intent,e.initiateKey);current.current=current.current.filter(other=>other===e||other.dto?.id!==e.dto!.id);}if(!active(e))return;if(!e.uploaded){if(!e.file)throw new Error();e.dto=await client.upload(e.dto.id,e.file,n=>{if(active(e)){e.progress=n;paint();}},e.controller.signal);e.uploaded=true;}if(!active(e))return;e.phase='scanning';paint();e.dto=await client.finalize(e.dto.id,e.finalizeKey);if(!active(e))return;if(e.dto.state!=='ready'||e.dto.scan_state!=='clean')throw new ApiFailure('ATTACHMENT_REJECTED');e.phase='ready';e.file=undefined;setMessage('Attachment saved securely.');paint();}catch(error){if(!active(e))return;if(!e.dto&&error instanceof ApiFailure&&!['uncertain','pending'].includes(recoveryFor(error,true)))e.initiationAttempted=false;const unsafe=error instanceof ApiFailure&&['ATTACHMENT_REJECTED','ATTACHMENT_CONTENT_MISMATCH','ATTACHMENT_TYPE_UNSUPPORTED'].includes(error.code);e.phase=unsafe?'unsafe':'failed';e.error=unsafe?'This file did not pass safety validation. Remove it and choose another.':error instanceof ApiFailure&&error.code==='ATTACHMENT_SCAN_FAILED'?'File is still quarantined. Retry validation.':'Attachment could not be saved. Retry the same upload or refresh current evidence.';if(unsafe)revoke(e);paint();}}
 async function select(file:File|undefined){if(!file||locked||loading||loadFailed||!allowUploads)return;if(!file.size||file.size>attachmentLimits.fileBytes){setMessage('Choose a nonempty file up to 8 MiB.');return;}if(!Object.hasOwn(attachmentMedia,file.type)){setMessage('Choose a JPEG or PNG photo, MP3 or WAV voice note, or MP4 video.');return;}if(current.current.filter(e=>!['ended'].includes(e.phase)).length>=attachmentLimits.count){setMessage(`A ${parentLabel} can have at most 10 attachments.`);return;}const e:Entry<D,I>={localId:crypto.randomUUID(),file,progress:0,phase:'selected',controller:new AbortController(),initiateKey:crypto.randomUUID(),finalizeKey:crypto.randomUUID(),cancelKey:crypto.randomUUID(),uploaded:false,initiationAttempted:false};current.current.push(e);paint();try{if(file.type.startsWith('image/'))e.file=await prepareImage(file,1280,0.8,e.controller.signal);if(!active(e))return;e.preview=URL.createObjectURL(e.file!);await run(e);}catch{if(active(e)){e.phase='failed';e.error='Photo could not be prepared. Remove it and choose another.';paint();}}}
 async function remove(e:Entry<D,I>){if(locked||!allowCancel||!exists(e))return;const ticket=runtime.ticket();e.controller.abort();revoke(e);e.phase='canceling';e.error=undefined;paint();try{if(!e.dto&&e.initiationAttempted){if(!e.intent)throw new Error();e.dto=await client.initiate(e.intent,e.initiateKey);}if(e.dto&&e.dto.state!=='ready'){const dto=await client.cancel(e.dto.id,e.cancelKey);if(!['canceled','deleted','cleanup_pending'].includes(dto.state))throw new ApiFailure('TEMPORARILY_UNAVAILABLE',{kind:'protocol',dispatched:true});}if(!exists(e)||!runtime.isCurrent(ticket))return;current.current=current.current.filter(other=>other!==e&&(!e.dto||other.dto?.id!==e.dto.id));setMessage('Upload canceled. Temporary bytes will be cleaned.');paint();}catch{if(exists(e)&&runtime.isCurrent(ticket)){e.phase='cancel_failed';e.error='Cancellation is unconfirmed. Retry the same cancellation or refresh current evidence.';paint();}}}
 async function preview(e:Entry<D,I>){try{if(!e.dto||locked)return;const ticket=runtime.ticket(),blob=await client.bytes(e.dto.id,crypto.randomUUID());if(!active(e)||!runtime.isCurrent(ticket))return;if(blob.size!==e.dto.size_bytes||blob.type!==e.dto.media_type)throw new ApiFailure('ATTACHMENT_CONTENT_MISMATCH');revoke(e);e.preview=URL.createObjectURL(blob);paint();}catch{if(active(e)){e.error='Preview is unavailable. Try again.';paint();}}}
 useEffect(()=>{paint();},[allowUploads,allowCancel,paint]);
 const inFlight=entries.some(e=>['selected','uploading','scanning','canceling'].includes(e.phase));
 return <section className="attach" aria-label="Private attachments" style={{minWidth:0,maxWidth:'100%'}}>{allowUploads&&<div className="attach-buttons">{kinds.map(k=><span key={k.kind}><button type="button" className="attach-btn" disabled={loading||loadFailed||locked} onClick={()=>inputs.current[k.kind]?.click()} aria-describedby={label}><Msym name={k.icon}/>{k.label}</button><input ref={node=>{inputs.current[k.kind]=node;}} type="file" hidden disabled={loading||loadFailed||locked} aria-label={`Choose ${k.label.toLowerCase()}`} accept={k.accept} onChange={event=>{const file=event.target.files?.[0];event.target.value='';void select(file);}}/></span>)}</div>}<p id={label} role="status" aria-live="polite">{loading?'Loading attachments…':message||'Private files. Up to 8 MiB each.'}</p><button type="button" className="attach-btn" disabled={loading||inFlight||locked} onClick={()=>setRevision(r=>r+1)}>{loadFailed?'Retry attachment list':'Refresh attachment evidence'}</button><ul className="attach-list">{entries.map(e=><li key={e.localId} style={{flexWrap:'wrap',maxWidth:'100%'}}>{e.preview&&(e.dto?.kind??e.file?.type.split('/')[0])==='image'&&<img src={e.preview} alt="Selected attachment preview"/>}{e.preview&&(e.dto?.kind??e.file?.type.split('/')[0])==='video'&&<video src={e.preview} controls preload="metadata"/>}{e.preview&&(e.dto?.kind??e.file?.type.split('/')[0])==='audio'&&<audio src={e.preview} controls preload="metadata"/>}<div className="u-grow" style={{minWidth:0,overflowWrap:'anywhere'}}><div className="attach-name">{e.dto?.filename??'Selected attachment'}</div><div role="status" aria-live="polite">{e.phase==='ready'?'Saved securely':e.phase==='scanning'?'Checking file safety…':e.phase==='uploading'?`Uploading ${e.progress}%`:e.phase==='selected'?'Preparing file…':e.phase==='canceling'?'Canceling upload…':e.phase==='ended'?e.dto?.state.replaceAll('_',' '):e.error}</div>{e.phase==='uploading'&&<progress aria-label="Upload progress" value={e.progress} max={100}/>} {e.phase==='ready'&&e.error&&<p role="alert">{e.error}</p>}</div>{e.phase==='failed'&&allowUploads&&(e.file||e.uploaded)&&<button type="button" className="attach-btn" disabled={locked} onClick={()=>{void run(e);}}>Retry attachment</button>}{e.phase==='ready'?<>{!e.preview&&<button type="button" className="attach-btn" disabled={locked} onClick={()=>{void preview(e);}}>Preview attachment</button>}{e.preview&&<button type="button" className="attach-btn" onClick={()=>{revoke(e);paint();}}>Hide preview</button>}</>:allowCancel&&e.phase!=='ended'&&<button type="button" className="attach-btn" disabled={locked||e.phase==='canceling'} aria-label={e.phase==='cancel_failed'?'Retry same attachment cancellation':'Cancel attachment upload'} onClick={()=>{void remove(e);}}>{e.phase==='cancel_failed'?'Retry cancellation':'Cancel'}</button>}</li>)}</ul></section>;
}
