import assert from 'node:assert/strict';
import test from 'node:test';
import { randomBytes } from 'node:crypto';
import { provisionDatabase } from '../../../../packages/db/test/support.ts';
import { createAuthService } from '../../src/modules/auth/service.ts';
import { createDeliveryWorker } from '../../src/modules/auth/worker.ts';
import { HttpError } from '../../src/plugins/errors.ts';
import type { Delivery } from '../../src/modules/auth/delivery.ts';
import { buildServer } from '../../src/server.ts';
import { parseEnvironment } from '../../src/env.ts';

const keys={version:'test',verifier:randomBytes(32),encryption:randomBytes(32),browser:randomBytes(32)};
const denied=(error:unknown)=>error instanceof HttpError && error.code==='UNAUTHENTICATED';
await test('OTP race has one winner, survives restart and revokes copied session immediately',{timeout:30000},async t=>{
  const db=await provisionDatabase(t); await db.prepareAuth();
  const pool=db.runtimePool({maxConnections:1}),auth=createAuthService(pool,keys),sent:Delivery[]=[];
  const worker=createDeliveryWorker(pool,keys,async message=>{sent.push(message);return {state:'accepted',reference:'synthetic'};});
  const user=await auth.provision('email','operator@example.test');
  const c=await auth.start('email','operator@example.test','browser-one','127.0.0.1');
  await worker.tick(); assert.equal(sent.length,1);
  await assert.rejects(auth.verify(c.challenge_id,sent[0]!.code,'foreign-browser','127.0.0.1'),denied);
  const race=await Promise.allSettled([auth.verify(c.challenge_id,sent[0]!.code,'browser-one','127.0.0.1'),auth.verify(c.challenge_id,sent[0]!.code,'browser-one','127.0.0.1')]);
  assert.equal(race.filter(r=>r.status==='fulfilled').length,1);
  const winner=race.find(r=>r.status==='fulfilled'); assert.ok(winner?.status==='fulfilled' && !winner.value.linked);
  const token=winner.value.token;
  assert.equal((await auth.current(token)).user_id,user);
  const other=createAuthService(db.runtimePool(),keys);
  assert.equal((await other.current(token)).user_id,user);
  await auth.logout(token); await assert.rejects(other.current(token),denied);
  const stored=await db.adminQuery('SELECT * FROM shipit.auth_challenges');
  assert.equal(stored.rows[0]!.payload,null);
  assert.ok(!JSON.stringify(stored.rows).includes(sent[0]!.code));
  await assert.rejects(pool.query('DELETE FROM shipit.auth_security_events'));
  await worker.cleanup();
});
await test('wrong codes exhaust attempts, decoy accounts enqueue nothing and epochs cancel outstanding codes',{timeout:30000},async t=>{
  const db=await provisionDatabase(t);await db.prepareAuth();const pool=db.runtimePool(),auth=createAuthService(pool,keys),sent:Delivery[]=[];
  const worker=createDeliveryWorker(pool,keys,async m=>{sent.push(m);return {state:'accepted'};});
  const user=await auth.provision('whatsapp','+15555550101');
  const unknown=await auth.start('whatsapp','+15555550102','b','ip');assert.equal(await worker.tick(),false);
  await assert.rejects(auth.verify(unknown.challenge_id,'00000000','b','ip'),denied);
  const c=await auth.start('whatsapp','+15555550101','b','ip');await worker.tick();
  const wrong=sent[0]!.code==='00000000' ? '11111111':'00000000';
  for(let i=0;i<5;i++) await assert.rejects(auth.verify(c.challenge_id,wrong,'b','ip'),denied);
  await assert.rejects(auth.verify(c.challenge_id,sent[0]!.code,'b','ip'),denied);
  const next=await auth.start('whatsapp','+15555550101','b','ip');await worker.tick();
  await auth.changeAccount(user,'disabled');
  await assert.rejects(auth.verify(next.challenge_id,sent[1]!.code,'b','ip'),denied);
  await assert.rejects(auth.start('whatsapp','+15555550101','b','ip').then(()=>auth.start('whatsapp','+15555550101','b','ip')),e=>e instanceof HttpError && e.code==='RATE_LIMITED');
});
await test('alternate-contact recovery requires recent session, rejects foreign IDs and revokes on unlink',{timeout:30000},async t=>{
  const db=await provisionDatabase(t);await db.prepareAuth();const pool=db.runtimePool({maxConnections:1}),auth=createAuthService(pool,keys),sent:Delivery[]=[];
  const worker=createDeliveryWorker(pool,keys,async m=>{sent.push(m);return {state:'accepted'};});
  const user=await auth.provision('email','alpha@example.test'); await auth.provision('email','beta@example.test');
  const c=await auth.start('email','alpha@example.test','b','ip');await worker.tick();
  const login=await auth.verify(c.challenge_id,sent[0]!.code,'b','ip');assert.ok(!login.linked);
  const link=await auth.start('whatsapp','+15555550101','b','ip',login.token);await worker.tick();
  await assert.rejects(auth.verify(link.challenge_id,sent[1]!.code,'b','ip','foreign'),denied);
  assert.deepEqual(await auth.verify(link.challenge_id,sent[1]!.code,'b','ip',login.token),{linked:true});
  const contacts=await auth.contacts(login.token);assert.equal(contacts.length,2);
  const foreign=(await db.adminQuery<{id:string}>('SELECT id FROM shipit.auth_identifiers WHERE user_id<>$1',[user])).rows[0]!.id;
  await assert.rejects(auth.unlink(login.token,foreign),e=>e instanceof HttpError && e.code==='ACTION_FORBIDDEN');
  await auth.unlink(login.token,contacts.find(c=>c.channel==='email')!.id);
  await assert.rejects(auth.current(login.token),denied);
});
await test('HTTP login rotates cookies, never returns credentials and database expiry denies access',{timeout:30000},async t=>{
  const db=await provisionDatabase(t);await db.prepareAuth();const pool=db.runtimePool(),auth=createAuthService(pool,keys),sent:Delivery[]=[];
  await auth.provision('email','http@example.test');
  const worker=createDeliveryWorker(pool,keys,async m=>{sent.push(m);return {state:'accepted'};});
  const logs:string[]=[];
  const config=parseEnvironment({NODE_ENV:'development',HOST:'127.0.0.1',PORT:'3000',LOG_LEVEL:'info',ALLOWED_ORIGINS:'http://localhost:5173',TRUSTED_PROXY_HOPS:'0',DATABASE_SECRET_REF:'local:database',DATABASE_TLS_MODE:'disable'});
  const app=buildServer({config,database:pool,auth:{keys,delivery:{},webhook:undefined},logSink:{write:s=>{logs.push(s);}}});
  t.after(()=>app.close());
  const boot=await app.inject('/auth/bootstrap');const browser=boot.cookies[0]!;
  const headers={origin:'http://localhost:5173','x-csrf-token':boot.json().csrf_token};
  const cookies:Record<string,string>={[browser.name]:browser.value};
  const start=await app.inject({method:'POST',url:'/auth/challenges',headers,cookies,payload:{channel:'email',address:'http@example.test'}});
  assert.equal(start.statusCode,200);await worker.tick();
  const login=await app.inject({method:'POST',url:'/auth/challenges/verify',headers,cookies,payload:{challenge_id:start.json().challenge_id,code:sent[0]!.code}});
  assert.equal(login.statusCode,200);assert.deepEqual(login.json(),{authenticated:true});
  const session=login.cookies.find(c=>c.name==='shipit_session')!;assert.ok(session.httpOnly);
  cookies[session.name]=session.value;
  assert.equal((await app.inject({url:'/auth/session',cookies})).statusCode,200);
  const next=await app.inject({method:'POST',url:'/auth/challenges',headers,cookies,payload:{channel:'email',address:'http@example.test'}});await worker.tick();
  const rotated=await app.inject({method:'POST',url:'/auth/challenges/verify',headers,cookies,payload:{challenge_id:next.json().challenge_id,code:sent[1]!.code}});
  assert.equal(rotated.statusCode,200);assert.notEqual(rotated.cookies[0]!.value,session.value);
  assert.equal((await app.inject({url:'/auth/session',cookies})).statusCode,401);
  const fresh=rotated.cookies[0]!.value;cookies[session.name]=fresh;
  await auth.logoutAll(fresh);assert.equal((await app.inject({url:'/auth/session',cookies})).statusCode,401);
  assert.ok(!logs.join('').includes(sent[0]!.code));assert.ok(!logs.join('').includes(session.value));assert.ok(!logs.join('').includes('http@example.test'));
});
await test('resend preserves code and expiry, stale delivery becomes uncertain and maintenance removes secrets',{timeout:30000},async t=>{
  const db=await provisionDatabase(t);await db.prepareAuth();const pool=db.runtimePool(),auth=createAuthService(pool,keys),sent:Delivery[]=[];
  const user=await auth.provision('email','expiry@example.test');
  const worker=createDeliveryWorker(pool,keys,async m=>{sent.push(m);return {state:'accepted'};});
  const c=await auth.start('email','expiry@example.test','b','ip');await worker.tick();
  await assert.rejects(auth.resend(c.challenge_id,'b','ip'),e=>e instanceof HttpError && e.code==='ACTION_FORBIDDEN');
  await db.adminQuery("UPDATE shipit.auth_challenges SET last_sent_at=clock_timestamp()-interval '61 seconds' WHERE id=$1",[c.challenge_id]);
  await auth.resend(c.challenge_id,'b','ip');await worker.tick();assert.equal(sent[0]!.code,sent[1]!.code);
  await db.adminQuery("UPDATE shipit.auth_challenges SET expires_at=clock_timestamp()-interval '1 second' WHERE id=$1",[c.challenge_id]);
  await assert.rejects(auth.verify(c.challenge_id,sent[0]!.code,'b','ip'),denied);await worker.cleanup();
  assert.equal((await db.adminQuery('SELECT payload FROM shipit.auth_challenges WHERE id=$1',[c.challenge_id])).rows[0]!.payload,null);
  await db.adminQuery("UPDATE shipit.auth_delivery_jobs SET state='sending',claimed_at=clock_timestamp()-interval '2 minutes' WHERE challenge_id=$1",[c.challenge_id]);
  assert.equal(await worker.tick(),false);
  assert.ok((await db.adminQuery('SELECT state FROM shipit.auth_delivery_jobs')).rows.every(r=>r.state==='uncertain'));
  const next=await auth.start('email','expiry@example.test','b','ip');await worker.tick();
  const login=await auth.verify(next.challenge_id,sent[2]!.code,'b','ip');assert.ok(!login.linked);
  await db.adminQuery("UPDATE shipit.auth_sessions SET idle_expires_at=clock_timestamp()-interval '1 second' WHERE user_id=$1",[user]);
  await assert.rejects(auth.current(login.token),denied);
});
