import { describe,expect,it } from 'vitest';
import { deliveryProofIntent,deliveryVerifier,generateDeliveryCode,openDeliveryCode,parseDeliveryProofConfiguration,parseDeliveryProofKeys,sealDeliveryCode,verifyDeliveryCode } from './crypto.ts';

const keys={version:'v1',verifier:Buffer.alloc(32,17),encryption:Buffer.alloc(32,29)};
const identity=['organization','franchise','parcel','attempt','assignment','1','challenge'];
describe('delivery proof cryptography',()=>{
 it('emits bounded six-digit codes through the Node crypto implementation',()=>{const values=Array.from({length:32},generateDeliveryCode);expect(values.every(value=>/^\d{6}$/.test(value))).toBe(true);expect(new Set(values).size).toBeGreaterThan(1);});
 it('domain-separates keyed verifiers and compares only equal identities',()=>{const verifier=deliveryVerifier(keys,identity,'012345');expect(verifier).toMatch(/^[a-f0-9]{64}$/);expect(verifyDeliveryCode(keys,identity,'012345',verifier)).toBe(true);expect(verifyDeliveryCode(keys,[...identity.slice(0,-1),'other'],'012345',verifier)).toBe(false);expect(verifyDeliveryCode(keys,identity,'012346',verifier)).toBe(false);});
 it('uses a separately domain-bound keyed idempotency commitment for low-entropy proof input',()=>{const first=deliveryProofIntent(keys,identity,'012345');expect(first).toMatch(/^[a-f0-9]{64}$/);expect(first).not.toBe(deliveryVerifier(keys,identity,'012345'));expect(deliveryProofIntent(keys,identity,'012346')).not.toBe(first);});
 it('authenticates encrypted resend material against identity and key version',()=>{const sealed=sealDeliveryCode(keys,identity,'654321');expect(sealed).not.toContain('654321');expect(openDeliveryCode(keys,identity,sealed,'v1')).toBe('654321');expect(()=>openDeliveryCode(keys,[...identity,'transplant'],sealed,'v1')).toThrow();expect(()=>openDeliveryCode(keys,identity,sealed,'v2')).toThrow('DELIVERY_PROOF_KEY_UNAVAILABLE');});
 it('rejects weak, shared or malformed purpose keys and parses fail-closed provider qualification',()=>{expect(()=>parseDeliveryProofKeys({version:'v1',verifier:'00'.repeat(32),encryption:'00'.repeat(32)})).toThrow('DELIVERY_PROOF_KEYS_INVALID');expect(()=>parseDeliveryProofConfiguration('{}')).toThrow('DELIVERY_PROOF_CONFIGURATION_INVALID');const unqualified=parseDeliveryProofConfiguration(JSON.stringify({keys:{version:'v2',verifier:'01'.repeat(32),encryption:'02'.repeat(32)},template:{name:'shipit_delivery_code',language:'en'}}));expect(unqualified.keys.version).toBe('v2');expect(unqualified.meta_send_qualified).toBe(false);expect(parseDeliveryProofConfiguration(JSON.stringify({keys:{version:'v2',verifier:'01'.repeat(32),encryption:'02'.repeat(32)},template:{name:'shipit_delivery_code',language:'en',meta_send_qualified:true}})).meta_send_qualified).toBe(true);});
});
