import {protocol} from '../data-access/dto';
import React,{useEffect,useRef,useState} from 'react';
import type {CashLocationDto} from '@shippingco/shared';
import type {CashbookSource} from '../data-access/cashbook';
import type {CommandIntent} from '../data-access/command-intent';
import {TextField,SelectField} from '../components/m3/Input';
import {useResource} from './hooks';
import {Empty,Failure,Loading} from './AsyncState';
import {formatKolkata} from './format';
const money=(paise:string)=>{const n=BigInt(paise),v=n<0n?-n:n;return `${n<0n?'-':''}₹${(v/100n).toLocaleString('en-IN')}.${String(v%100n).padStart(2,'0')}`;};
const kinds=['receipt','refund','refund_correction','legacy_collection','legacy_collection_correction','expense','opening_float','owner_funds','deposit','withdrawal','correction','handover'];
export default function CashbookSources({source,locations,canExport,locked,reportId,open,run,isCurrent}:{source:CashbookSource;locations:CashLocationDto[];canExport:boolean;locked:boolean;reportId:string|null;open:(id:string)=>void;run:(intent:CommandIntent)=>void;isCurrent:()=>boolean}){
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),[from,setFrom]=useState(today),[to,setTo]=useState(today),[sort,setSort]=useState<'occurred_asc'|'occurred_desc'>('occurred_desc'),[method,setMethod]=useState(''),[kind,setKind]=useState(''),[location,setLocation]=useState(''),[reference,setReference]=useState(''),[offset,setOffset]=useState(0),[rowId,setRowId]=useState<string|null>(null),[downloading,setDownloading]=useState(false),[notice,setNotice]=useState('');
 const lifetime=useRef(new AbortController());useEffect(()=>{const abort=new AbortController();lifetime.current=abort;return()=>abort.abort();},[]);
 const observed=useRef<{id:string;metadata:string}|null>(null);const retain=<T extends {snapshot:{id:string}}>(value:T)=>{const metadata=JSON.stringify(value.snapshot);if(observed.current?.id===value.snapshot.id&&observed.current.metadata!==metadata)return protocol();observed.current={id:value.snapshot.id,metadata};return value;};
 const page=useResource((reportId??'none')+'-'+offset,async signal=>reportId?retain(await source.report(reportId,offset,signal)):null),detail=useResource((reportId??'none')+'-'+rowId,async signal=>reportId&&rowId?retain(await source.reportDetail(reportId,rowId,signal)):null);
 const result=page.value?.snapshot.id===reportId?page.value:null,row=detail.value?.snapshot.id===reportId&&detail.value.row.id===rowId?detail.value.row:null,busy=locked||downloading;
 useEffect(()=>{setOffset(0);setRowId(null);},[reportId]);
 const download=async()=>{if(!result)return;setDownloading(true);setNotice('');try{const r=retain(await source.export(result.snapshot.id,lifetime.current.signal));if(!isCurrent()||lifetime.current.signal.aborted)return;const url=URL.createObjectURL(new Blob([r.csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`cashbook-${r.snapshot.id}.csv`;a.click();const revoke=URL.revokeObjectURL.bind(URL);setTimeout(()=>revoke(url),1000);setNotice('CSV ready. It uses the same saved cutoff and control totals.');}catch{if(!lifetime.current.signal.aborted)setNotice('CSV unavailable. Check current access and snapshot expiry, then retry.');}finally{if(!lifetime.current.signal.aborted)setDownloading(false);}};
 return <><section className="card ops-card"><h2 className="t-title-lg">Capture cashbook sources</h2><p>Actual receipts are counted once. Bill allocations do not create new money. Choose up to 31 Kolkata days and 5,000 source rows; snapshots expire after 24 hours.</p><form className="ops-form" aria-label="Capture cashbook sources" onSubmit={e=>{e.preventDefault();setOffset(0);setRowId(null);run(source.capture({from_day:from,to_day:to,sort,payment_method:method||null,kind:kind||null,location_id:location||null}));}}><TextField label="Cashbook from day" type="date" value={from} onChange={setFrom} required disabled={busy}/><TextField label="Cashbook through day" type="date" value={to} onChange={setTo} required disabled={busy}/><SelectField label="Source order" aria-label="Source order" value={sort} onChange={v=>setSort(v as typeof sort)} disabled={busy} options={[{value:'occurred_desc',label:'Newest occurrence first'},{value:'occurred_asc',label:'Oldest occurrence first'}]}/><SelectField label="Source payment method" aria-label="Source payment method" value={method} onChange={setMethod} disabled={busy} options={[{value:'',label:'All methods'},...['cash','upi','card','bank_transfer','other'].map(value=>({value,label:value.replaceAll('_',' ')}))]}/><SelectField label="Source kind" aria-label="Source kind" value={kind} onChange={setKind} disabled={busy} options={[{value:'',label:'All sources'},...kinds.map(value=>({value,label:value.replaceAll('_',' ')}))]}/><SelectField label="Source location filter" aria-label="Source location filter" value={location} onChange={setLocation} disabled={busy} options={[{value:'',label:'All locations, including unknown custody'},...locations.map(l=>({value:l.id,label:l.name}))]}/><button className="btn btn-filled" disabled={busy}>Capture source snapshot</button></form><form className="ops-form" aria-label="Open saved cashbook snapshot" onSubmit={e=>{e.preventDefault();setOffset(0);setRowId(null);open(reference.trim());}}><TextField label="Saved cashbook snapshot reference" value={reference} onChange={setReference} disabled={busy}/><button className="btn btn-outlined" disabled={busy||!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(reference.trim())}>Open saved source snapshot</button></form></section>
 {reportId&&page.phase==='loading'&&<Loading label="Loading captured cashbook sources…"/>}{reportId&&page.phase==='error'&&<Failure retry={page.reload} label="Source snapshot unavailable or expired. Check access or capture a new snapshot."/>}{result&&<section className="card ops-card"><h2 className="t-title-lg">Captured cashbook evidence</h2><p>{result.snapshot.id} · {result.snapshot.filter.from_day} through {result.snapshot.filter.to_day} · cutoff {formatKolkata(result.snapshot.as_of)} · expires {formatKolkata(result.snapshot.expires_at)}</p><dl className="ops-details"><dt>Filtered source rows</dt><dd>{result.snapshot.count}</dd><dt>Known inflows</dt><dd>{money(result.snapshot.totals.known_inflows_paise)}</dd><dt>Known outflows</dt><dd>{money(result.snapshot.totals.known_outflows_paise)}</dd><dt>Known net</dt><dd>{money(result.snapshot.totals.known_net_paise)}</dd><dt>Unknown custody inflows</dt><dd>{money(result.snapshot.totals.unknown_inflows_paise)}</dd><dt>Unknown custody outflows</dt><dd>{money(result.snapshot.totals.unknown_outflows_paise)}</dd><dt>Unknown custody sources</dt><dd>{result.snapshot.totals.unknown_sources}</dd></dl>
 <h3 className="t-title-md">All current recorded positions at capture</h3><p>These controls include every location at the captured cutoff, regardless of the source date and method filters. They do not certify physical cash or bank settlement. Source version {result.snapshot.position.source_version}; unknown custody sources {result.snapshot.position.unknown_sources}.</p><ul className="ops-list">{result.snapshot.position.locations.map(p=><li key={p.location_id}>{p.location_id} · recorded {money(p.known_recorded_paise)} · reserved {money(p.pending_reserved_paise)} · available {money(p.available_paise)} · shortfall {money(p.shortfall_paise)} · {p.state}</li>)}</ul>
 {canExport?<button className="btn btn-outlined" disabled={busy} onClick={()=>{void download();}}>Download matching cashbook CSV</button>:<p>Your role can read this snapshot but cannot export it.</p>}{notice&&<p role="status">{notice}</p>}{result.rows.length===0?<Empty title="No source rows" body="No sources match the saved filters."/>:<div className="ops-list">{result.rows.map(r=><button className="btn btn-outlined cashbook-source-row" key={r.id} disabled={busy} onClick={()=>setRowId(r.id)}>{r.source_kind.replaceAll('_',' ')} · {r.direction} {money(r.amount_paise)} · {r.payment_method??'Method not recorded'} · {formatKolkata(r.occurred_at)}{r.unknown_reason?' · Unknown custody':''}</button>)}</div>}{offset>0&&<button className="btn btn-text" disabled={busy||page.phase==='loading'} onClick={()=>{setRowId(null);setOffset(offset-100);}}>Previous source page</button>}{result.next_offset!==null&&<button className="btn btn-text" disabled={busy||page.phase==='loading'} onClick={()=>{setRowId(null);setOffset(result.next_offset!);}}>Next source page</button>}</section>}
 {rowId&&detail.phase==='loading'&&<Loading label="Loading saved source detail…"/>}{rowId&&detail.phase==='error'&&<Failure retry={detail.reload} label="Saved source detail unavailable."/>}{row&&<section className="card ops-card"><h2 className="t-title-lg">Saved source detail</h2><dl className="ops-details">{Object.entries(row).map(([key,value])=><React.Fragment key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{key==='amount_paise'?money(String(value)):value??'Not recorded'}</dd></React.Fragment>)}</dl></section>}</>;
}
