import CashbookFilters from './CashbookFilters';
import CashbookSources from './CashbookSources';
import CashLocations from './CashLocations';
import CashHandovers from './CashHandovers';
import React,{useEffect,useMemo,useState,useSyncExternalStore} from 'react';
import type {CashLocationDto,CashbookRequestDto,CashbookRequestInput,OperatorRole,ReceiptMethod} from '@shippingco/shared';
import type {ScopeController} from '../operator/scope';
import {cashbook,type CashbookSource} from '../data-access/cashbook';
import {scopedApi} from '../data-access/scoped-api';
import {moneyReceipts} from '../data-access/money-receipts';
import type {CommandIntent} from '../data-access/command-intent';
import {TextField,SelectField} from '../components/m3/Input';
import {useCommand,useResource,usePagedResource} from './hooks';
import {CommandNotice,Empty,Failure,Loading} from './AsyncState';
import {formatMoney,formatKolkata,rupeesToPaise,kolkataInputToInstant,instantToKolkataInput} from './format';
const has=(roles:readonly OperatorRole[],...allowed:OperatorRole[])=>roles.some(r=>allowed.includes(r));
export default function Cashbook({controller,roles}:{controller:ScopeController;roles:readonly OperatorRole[]}){
 useSyncExternalStore(controller.subscribe,controller.snapshot,controller.snapshot);
 if(!controller.runtime.ticket().authority||!has(roles,'franchise_admin','operator','org_admin','accountant'))return <Empty title="Expense access unavailable" body="Select a permitted franchise."/>;
 return <Workspace key={controller.runtime.ticket().generation} controller={controller} roles={roles}/>;
}
function Workspace({controller,roles}:{controller:ScopeController;roles:readonly OperatorRole[]}){
 const api=useMemo(()=>scopedApi(controller),[controller]),source=useMemo(()=>cashbook(api),[api]),receivers=useMemo(()=>moneyReceipts(api),[api]);
 const canRequest=has(roles,'operator','franchise_admin'),admin=has(roles,'franchise_admin'),[selected,setSelected]=useState<string|null>(null),[handoverId,setHandoverId]=useState<string|null>(null),[reportId,setReportId]=useState<string|null>(null),[locationId,setLocationId]=useState<string|null>(null),[filter,setFilter]=useState(''),[filters,setFilters]=useState<Parameters<CashbookSource['requests']>[0]>({}),[cursor,setCursor]=useState<string|undefined>(),[correction,setCorrection]=useState<CashbookRequestDto|null>(null),[revision,setRevision]=useState(0),[blocked,setBlocked]=useState(false),[view,setView]=useState<'requests'|'custody'|'sources'|'locations'>('requests');
 const inbox=useResource(filter+'-'+JSON.stringify(filters)+'-'+(cursor??'')+'-'+revision,signal=>source.requests({...filters,state:filter,cursor},signal)),current=useResource((selected??'none')+'-'+revision,signal=>selected?source.detail(selected,signal):Promise.resolve(null));
 const locations=usePagedResource('locations',async(cursor,signal)=>{const r=await source.locations(cursor??undefined,signal);return {items:r.items,page:{has_more:r.next_cursor!==null,next_cursor:r.next_cursor}};}),employees=usePagedResource('employees',async(cursor,signal)=>{if(!canRequest)return {items:[],page:{has_more:false,next_cursor:null}};const r=await receivers.receivers(cursor??undefined,signal);return {items:r.items,page:{has_more:r.next_cursor!==null,next_cursor:r.next_cursor}};});
 const detail=current.value?.request.id===selected?current.value:null;
 const command=useCommand(async(intent:CommandIntent)=>{if(intent.operation==='cashbook.capture'){const r=await source.executeCapture(intent);return {area:'report',id:r.snapshot.id};}if(intent.operation==='cashbook.configure'){const r=await source.executeConfigure(intent);return {area:'location',id:r.id};}if(intent.operation.startsWith('cashbook.handover.')){const r=await source.executeHandover(intent);return {area:'handover',id:'handover_id' in r?r.handover_id:r.id};}const r=await (intent.operation==='cashbook.request'?source.executeRequest(intent):intent.operation==='cashbook.decide'?source.executeDecision(intent):source.executeApply(intent));return {area:'request',id:'request_id' in r?r.request_id:r.id};}),locked=command.phase==='pending'||command.phase==='uncertain';
 useEffect(()=>{const leave=(event:BeforeUnloadEvent)=>{if(locked){event.preventDefault();event.returnValue='';}},navigate=(event:MouseEvent)=>{if(locked&&event.target instanceof Element&&event.target.closest('a[href]')){event.preventDefault();event.stopPropagation();setBlocked(true);}},change=(event:Event)=>{if(locked&&event.target instanceof Element&&event.target.matches('select[aria-label="Franchise"]')){event.stopPropagation();(event.target as HTMLSelectElement).value=api.franchise;setBlocked(true);}};window.addEventListener('beforeunload',leave);document.addEventListener('click',navigate,true);document.addEventListener('change',change,true);return()=>{window.removeEventListener('beforeunload',leave);document.removeEventListener('click',navigate,true);document.removeEventListener('change',change,true);};},[locked,api.franchise]);
 const saved=(id:string,area='request')=>{if(area==='handover')setHandoverId(id);else if(area==='report')setReportId(id);else if(area==='location'){setLocationId(id);locations.reload();}else setSelected(id);setCorrection(null);setCursor(undefined);setRevision(r=>r+1);};
 const run=async(intent:CommandIntent,target?:string)=>{try{const r=await command.run(intent);if(controller.runtime.isCurrent(api.scope))saved(target??r.id,r.area);}catch{/* Retain original uncertain command. */}};
 const retry=async()=>{try{const r=await command.retry();if(r&&controller.runtime.isCurrent(api.scope))saved(r.id,r.area);}catch{/* Retain exact intent. */}};
 return <><section className="card ops-card"><h1 id="workspace-title" tabIndex={-1} className="t-headline-sm">Expenses and cashbook</h1><p>Record expenses and actual fund movements. A different franchise admin reviews each request before an admin applies it. Recorded funds do not confirm bank settlement.</p><CommandNotice phase={command.phase} code={command.error?.code} retry={command.canRetry?()=>{void retry();}:undefined}/>{blocked&&locked&&<p role="alert">Reconcile this exact request before leaving or changing franchise.</p>}{!locked&&<button className="btn btn-text" onClick={()=>{command.reset();setRevision(r=>r+1);locations.reload();employees.reload();}}>Refresh current evidence</button>}</section>
 <nav aria-label="Cashbook workflow"><button className="btn btn-outlined" disabled={locked} aria-pressed={view==='requests'} onClick={()=>setView('requests')}>Expense and fund requests</button><button className="btn btn-outlined" disabled={locked} aria-pressed={view==='custody'} onClick={()=>setView('custody')}>Cash custody</button>{has(roles,'org_admin','franchise_admin','accountant')&&<button className="btn btn-outlined" disabled={locked} aria-pressed={view==='sources'} onClick={()=>setView('sources')}>Cashbook sources</button>}{admin&&<button className="btn btn-outlined" disabled={locked} aria-pressed={view==='locations'} onClick={()=>setView('locations')}>Configure cash locations</button>}</nav>
 {locations.page.has_more&&<button className="btn btn-text" disabled={locked||locations.phase==='more'} onClick={locations.loadMore}>Load more locations</button>}{canRequest&&employees.page.has_more&&<button className="btn btn-text" disabled={locked||employees.phase==='more'} onClick={employees.loadMore}>Load more employees</button>}
 {view==='locations'&&employees.phase==='loading'&&<Loading label="Loading current cash custodians…"/>}{view==='locations'&&employees.phase==='error'&&<Failure retry={employees.reload} label="Current cash custodians unavailable."/>}
 {view==='requests'&&<>
 {canRequest&&inbox.value&&<RequestEditor key={correction?.id??'new'} source={source} original={correction} locations={locations.items} employees={employees.items} generation={inbox.value.current_source_version} locked={locked||inbox.phase==='loading'} submit={input=>{void run(source.submit(input));}} cancelCorrection={()=>setCorrection(null)}/>}
 {canRequest&&locations.phase==='loading'&&<Loading label="Loading permitted cash locations…"/>}{canRequest&&locations.phase==='error'&&<Failure retry={locations.reload} label="Cash locations could not be loaded."/>}{canRequest&&employees.phase==='error'&&<Failure retry={employees.reload} label="Responsible employees could not be loaded."/>}

 <section className="card ops-card"><h2 className="t-title-lg">{has(roles,'org_admin','franchise_admin','accountant')?'Franchise requests':'My requests'}</h2><SelectField label="Request status" aria-label="Request status" value={filter} onChange={value=>{if(!locked){setCursor(undefined);setFilter(value);}}} disabled={locked} options={[{value:'',label:'All requests'},...['requested','approved','rejected','applied'].map(value=>({value,label:value.replaceAll('_',' ')}))]}/>
 <CashbookFilters locations={locations.items} locked={locked} apply={value=>{setFilters(value);setCursor(undefined);}}/>
 {inbox.phase==='loading'&&<Loading/>}{inbox.phase==='error'&&<Failure retry={inbox.reload}/>} {inbox.value&&<><p className="ops-note">Current evidence as of {formatKolkata(inbox.value.as_of)}</p>{inbox.value.items.length===0?<Empty title="No requests" body="No permitted requests match this status."/>:<div className="ops-list">{inbox.value.items.map(r=><button className="btn btn-outlined" key={r.id} disabled={locked} onClick={()=>{setSelected(r.id);setCorrection(null);}}>{r.kind.replaceAll('_',' ')} · {formatMoney(r.amount_paise)} · {r.state}{r.corrected_by?' · later correction':''}</button>)}</div>}{inbox.value.next_cursor&&<button className="btn btn-text" disabled={locked} onClick={()=>setCursor(inbox.value!.next_cursor!)}>Next request page</button>}{cursor&&<button className="btn btn-text" disabled={locked} onClick={()=>setCursor(undefined)}>First request page</button>}</>}
 </section>{selected&&current.phase==='loading'&&<Loading label="Loading request evidence…"/>}{selected&&current.phase==='error'&&<Failure retry={current.reload} label="This request is unavailable in the selected franchise."/>}
 {detail&&<section className="card ops-card"><h2 className="t-title-lg">Saved request</h2><dl className="ops-details"><dt>Reference</dt><dd>{detail.request.id}</dd><dt>Amount</dt><dd>{formatMoney(detail.request.amount_paise)}</dd><dt>Payment method</dt><dd>{detail.request.payment_method??'Fund movement'}</dd><dt>Occurred</dt><dd>{formatKolkata(detail.request.occurred_at)}</dd><dt>Recorded</dt><dd>{formatKolkata(detail.request.recorded_at)}</dd><dt>Category</dt><dd>{detail.request.category??'Fund movement'}</dd><dt>Responsible employee</dt><dd>{detail.request.responsible_employee_id}</dd><dt>Source location</dt><dd>{detail.request.source_location_id}</dd><dt>Target location</dt><dd>{detail.request.target_location_id??'—'}</dd><dt>Private payee</dt><dd>{detail.request.payee??'—'}</dd><dt>Reason</dt><dd>{detail.request.reason}</dd><dt>State</dt><dd>{detail.effect?'Applied':detail.decision?.decision??'Requested'}</dd></dl>{detail.request.correction_of&&<p>Recording correction of {detail.request.correction_of}. Original evidence remains unchanged.</p>}
 {detail.decision&&<p>Reviewed by {detail.decision.actor_id}. {detail.decision.reason} · {detail.decision.attachments?.length??0} reviewed attachments.</p>}
 {admin&&!detail.decision&&detail.request.actor_id!==api.scope.authority?.userId&&<Review key={selected!} id={selected!} locked={locked} run={(outcome,reason)=>{void run(source.decide(selected!,{decision:outcome,reason,expected_version:1}),selected!);}}/>}
 {admin&&!detail.decision&&detail.request.actor_id===api.scope.authority?.userId&&<p role="status">A different franchise admin must review your request.</p>}
 {admin&&detail.decision?.decision==='approved'&&!detail.effect&&<button className="btn btn-filled" disabled={locked} onClick={()=>{void run(source.apply(selected!,{decision_id:detail!.decision!.id,expected_version:2}),selected!);}}>Apply exact approved request</button>}
 {canRequest&&detail.effect&&<button className="btn btn-outlined" disabled={locked} onClick={()=>setCorrection(detail!.request)}>Request recording correction</button>}
 </section>}</>}{view==='custody'&&<CashHandovers source={source} locations={locations.items} userId={api.scope.authority!.userId} admin={admin} canRequest={canRequest} locked={locked} revision={revision} selected={handoverId} select={setHandoverId} run={intent=>{void run(intent);}}/>}{view==='sources'&&has(roles,'org_admin','franchise_admin','accountant')&&<CashbookSources source={source} locations={locations.items} canExport={has(roles,'franchise_admin','accountant')} locked={locked} reportId={reportId} open={setReportId} run={intent=>{void run(intent);}} isCurrent={()=>controller.runtime.isCurrent(api.scope)}/>}{view==='locations'&&admin&&<CashLocations source={source} api={api} locations={locations.items} employees={employees.items} locked={locked} revision={revision} selected={locationId} select={setLocationId} run={intent=>{void run(intent);}}/>}</>;
}
function Review({id,locked,run}:{id:string;locked:boolean;run:(decision:'approved'|'rejected',reason:string)=>void}){const [reason,setReason]=useState(''),[outcome,setOutcome]=useState<'approved'|'rejected'>('approved');return <form key={id} className="ops-form" onSubmit={e=>{e.preventDefault();if(reason.trim())run(outcome,reason.trim());}}><SelectField label="Review decision" aria-label="Review decision" value={outcome} onChange={value=>setOutcome(value as typeof outcome)} disabled={locked} options={[{value:'approved',label:'Approve exact request'},{value:'rejected',label:'Reject request'}]}/><TextField label="Review reason" value={reason} onChange={setReason} required disabled={locked}/><button className="btn btn-filled" disabled={locked||!reason.trim()}>Record review</button></form>;}
function RequestEditor({source,original,locations,employees,generation,locked,submit,cancelCorrection}:{source:CashbookSource;original:CashbookRequestDto|null;locations:CashLocationDto[];employees:{id:string;label:string}[];generation:number;locked:boolean;submit:(input:CashbookRequestInput)=>void;cancelCorrection:()=>void}){
 const [kind,setKind]=useState<CashbookRequestInput['kind']>(original?.kind??'expense'),[locationId,setLocationId]=useState(original?.source_location_id??''),[targetId,setTargetId]=useState(original?.target_location_id??''),[method,setMethod]=useState<ReceiptMethod>(original?.payment_method??'cash'),[amount,setAmount]=useState(original?`${BigInt(original.amount_paise)/100n}.${String(BigInt(original.amount_paise)%100n).padStart(2,'0')}`:''),[category,setCategory]=useState<CashbookRequestInput['category']>(original?.category??'supplies'),[payee,setPayee]=useState(original?.payee??''),[employee,setEmployee]=useState(original?.responsible_employee_id??''),[reason,setReason]=useState(''),[occurred,setOccurred]=useState(original?instantToKolkataInput(original.occurred_at)??'':''),[error,setError]=useState('');
 const originalSource=useResource('source-'+(original?.id??''),signal=>original?source.location(original.source_location_id,signal):Promise.resolve(null)),originalTarget=useResource('target-'+(original?.id??''),signal=>original?.target_location_id?source.location(original.target_location_id,signal):Promise.resolve(null));
 const sourceChoices=locations.filter(l=>(!!original||l.active)&&(kind==='expense'||(kind==='withdrawal'?l.kind==='noncash':l.kind==='cash'))),targetChoices=locations.filter(l=>(!!original||l.active)&&l.id!==locationId&&l.kind===(kind==='deposit'?'noncash':'cash'));
 const selected=locations.find(l=>l.id===locationId)??originalSource.value,target=locations.find(l=>l.id===targetId)??originalTarget.value,paired=kind==='deposit'||kind==='withdrawal',methods=selected?[...new Set([...selected.methods,...(original?.payment_method?[original.payment_method]:[])])]:[];
 return <section className="card ops-card"><h2 className="t-title-lg">{original?'Request a recording correction':'New expense or fund request'}</h2>{locations.length===0&&!original?<Empty title="No permitted cash locations" body="Ask a franchise admin to configure an account and custody location."/>:<form className="ops-form" aria-label="Cashbook request" onSubmit={e=>{e.preventDefault();const paise=rupeesToPaise(amount),time=original?.occurred_at??kolkataInputToInstant(occurred);if(!selected||paired&&!target||paise===null||!original&&paise===0||!time||!employee||!reason.trim()||kind==='expense'&&!payee.trim()){setError('Select current locations and employee, enter a valid amount and Kolkata occurrence time, and provide the reason/payee.');return;}setError('');submit({kind,payment_method:kind==='expense'?method:null,source_location_id:selected.id,source_revision_id:selected.revision_id,target_location_id:paired?target!.id:null,target_revision_id:paired?target!.revision_id:null,expected_source_version:generation,amount_paise:paise,currency:'INR',category:kind==='expense'?category:null,payee:kind==='expense'?payee.trim():null,responsible_employee_id:employee,reason:reason.trim(),occurred_at:time,...(original?{correction_of:original.id}:{})});}}>
 <SelectField label="Request kind" aria-label="Request kind" value={kind} onChange={v=>{setKind(v as typeof kind);setLocationId('');setTargetId('');}} disabled={locked||!!original} options={['expense','opening_float','owner_funds','deposit','withdrawal'].map(value=>({value,label:value.replaceAll('_',' ')}))}/><SelectField label="Source cash location" aria-label="Source cash location" value={locationId} onChange={value=>{setLocationId(value);setMethod(locations.find(l=>l.id===value)?.methods[0]??'cash');}} disabled={locked||!!original} options={[{value:'',label:'Select location'},...sourceChoices.map(l=>({value:l.id,label:l.name})),...(originalSource.value&&!locations.some(l=>l.id===originalSource.value!.id)?[{value:originalSource.value.id,label:originalSource.value.name}]:[])]}/>
 {paired&&<SelectField label="Target cash location" aria-label="Target cash location" value={targetId} onChange={setTargetId} disabled={locked||!!original} options={[{value:'',label:'Select target'},...targetChoices.map(l=>({value:l.id,label:l.name})),...(originalTarget.value&&!locations.some(l=>l.id===originalTarget.value!.id)?[{value:originalTarget.value.id,label:originalTarget.value.name}]:[])]}/>}
 {kind==='expense'&&<><SelectField label="Payment method" aria-label="Payment method" value={method} onChange={v=>setMethod(v as ReceiptMethod)} disabled={locked} options={methods.map(value=>({value,label:value.replaceAll('_',' ')}))}/><SelectField label="Expense category" aria-label="Expense category" value={category??'supplies'} onChange={v=>setCategory(v as typeof category)} disabled={locked} options={['rent','utilities','supplies','transport','maintenance','other'].map(value=>({value,label:value}))}/><TextField label="Private payee" value={payee} onChange={setPayee} required disabled={locked}/></>}
 <TextField label={original?'Replacement recorded amount (₹; zero annuls)':'Amount (₹)'} value={amount} onChange={setAmount} required disabled={locked}/><SelectField label="Responsible employee" aria-label="Responsible employee" value={employee} onChange={setEmployee} disabled={locked} options={[{value:'',label:'Select employee'},...employees.map(e=>({value:e.id,label:e.label}))]}/><TextField label="Occurred at (Kolkata)" type="datetime-local" value={occurred} onChange={setOccurred} required disabled={locked||!!original}/><TextField label="Reason" value={reason} onChange={setReason} required disabled={locked}/>{error&&<p role="alert">{error}</p>}<button className="btn btn-filled" disabled={locked||!selected||employees.length===0}>Submit for different-admin review</button>{original&&<button type="button" className="btn btn-text" disabled={locked} onClick={cancelCorrection}>Cancel correction draft</button>}
 </form>}</section>;
}
