import React,{useState} from 'react';
import type {CashLocationDto,CashHandoverCommandInput} from '@shippingco/shared';
import type {CashbookSource} from '../data-access/cashbook';
import type {CommandIntent} from '../data-access/command-intent';
import {TextField,SelectField} from '../components/m3/Input';
import {useResource,usePagedResource} from './hooks';
import {Empty,Failure,Loading} from './AsyncState';
import {formatMoney,formatKolkata,rupeesToPaise,kolkataInputToInstant} from './format';
export default function CashHandovers({source,locations,userId,admin,canRequest,locked,revision,selected,select,run}:{source:CashbookSource;locations:CashLocationDto[];userId:string;admin:boolean;canRequest:boolean;locked:boolean;revision:number;selected:string|null;select:(id:string)=>void;run:(intent:CommandIntent)=>void}){
 const [locationId,setLocationId]=useState(''),[targetId,setTargetId]=useState(''),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[occurred,setOccurred]=useState(''),[error,setError]=useState(''),[before,setBefore]=useState<number|undefined>();
 const inbox=usePagedResource('handovers-'+revision,async(cursor,signal)=>{const r=await source.handovers(cursor??undefined,signal);return {items:r.items,page:{has_more:r.next_cursor!==null,next_cursor:r.next_cursor}};}),targets=usePagedResource('targets-'+locationId+'-'+revision,async(cursor,signal)=>{if(!locationId)return {items:[],page:{has_more:false,next_cursor:null}};const r=await source.targets(locationId,cursor??undefined,signal);return {items:r.items,page:{has_more:r.next_cursor!==null,next_cursor:r.next_cursor}};});
 const evidence=useResource('target-evidence-'+locationId+'-'+revision,signal=>locationId?source.targets(locationId,undefined,signal):Promise.resolve(null)),current=useResource('handover-'+selected+'-'+before+'-'+revision,signal=>selected?source.handover(selected,before,signal):Promise.resolve(null));
 const detail=current.value?.request.id===selected?current.value:null,from=locations.find(l=>l.id===locationId),target=targets.items.find(l=>l.id===targetId);
 const cash=locations.filter(l=>l.kind==='cash'&&l.active&&(admin||l.custodian_id===userId));
 return <><section className="card ops-card"><h2 className="t-title-lg">Cash custody handovers</h2><p>The named receiving custodian acknowledges actual cash. Partial acceptance moves only that amount; ending a request releases its remaining reservation.</p>{!canRequest?<p>Your role can read custody evidence but cannot request or acknowledge transfers.</p>:cash.length===0?<Empty title="No sending cash locations" body="A franchise admin must configure your current cash custody location."/>:<form className="ops-form" aria-label="Request cash handover" onSubmit={e=>{e.preventDefault();const paise=rupeesToPaise(amount),time=kolkataInputToInstant(occurred);if(!from||!target||!evidence.value||evidence.value.source_location_id!==locationId||paise===null||paise===0||!time||!reason.trim()){setError('Choose current custody locations, an amount, actual Kolkata time and reason.');return;}setError('');run(source.requestHandover({source_location_id:from.id,source_revision_id:evidence.value.source_revision_id,target_location_id:target.id,target_revision_id:target.revision_id,expected_source_version:evidence.value.current_source_version,amount_paise:paise,currency:'INR',occurred_at:time,reason:reason.trim()}));}}>
 <SelectField label="Sending cash location" aria-label="Sending cash location" value={locationId} disabled={locked} onChange={v=>{setLocationId(v);setTargetId('');}} options={[{value:'',label:'Select sender'},...cash.map(l=>({value:l.id,label:l.name}))]}/><SelectField label="Receiving custodian location" aria-label="Receiving custodian location" value={targetId} disabled={locked||targets.phase==='loading'} onChange={setTargetId} options={[{value:'',label:'Select receiver'},...targets.items.map(l=>({value:l.id,label:l.name}))]}/><TextField label="Handover amount (₹)" value={amount} onChange={setAmount} required disabled={locked}/><TextField label="Cash handed over at (Kolkata)" type="datetime-local" value={occurred} onChange={setOccurred} required disabled={locked}/><TextField label="Handover reason" value={reason} onChange={setReason} required disabled={locked}/>{error&&<p role="alert">{error}</p>}<button className="btn btn-filled" disabled={locked||!target||evidence.phase!=='ready'}>Request custody acknowledgement</button></form>}
 {locationId&&targets.phase==='loading'&&<Loading label="Loading permitted receiving custodians…"/>}{(targets.phase==='error'||evidence.phase==='error')&&<Failure label="Receiving custody choices are unavailable." retry={()=>{targets.reload();evidence.reload();}}/>}{targets.page.has_more&&<button className="btn btn-text" disabled={locked||targets.phase==='more'} onClick={targets.loadMore}>Load more receiving custodians</button>}
 </section><section className="card ops-card"><h2 className="t-title-lg">Permitted handover inbox</h2>{inbox.phase==='loading'&&<Loading/>}{inbox.phase==='error'&&<Failure retry={inbox.reload}/>} {inbox.phase==='empty'&&<Empty title="No handovers" body="No cash handovers are visible in this franchise."/>}<div className="ops-list">{inbox.items.map(h=><button className="btn btn-outlined" disabled={locked} key={h.id} onClick={()=>{setBefore(undefined);select(h.id);}}>{formatMoney(h.amount_paise)} · {h.state.replaceAll('_',' ')} · remaining {formatMoney(h.remaining_paise)}</button>)}</div>{inbox.page.has_more&&<button className="btn btn-text" disabled={locked||inbox.phase==='more'} onClick={inbox.loadMore}>Load more handovers</button>}</section>
 {selected&&current.phase==='loading'&&<Loading label="Loading handover evidence…"/>}{selected&&current.phase==='error'&&<Failure retry={current.reload} label="Handover evidence is unavailable."/>}{detail&&<section className="card ops-card"><h2 className="t-title-lg">Saved custody handover</h2><p>{detail.request.id} · {detail.state.replaceAll('_',' ')}</p><dl className="ops-details"><dt>Requested</dt><dd>{formatMoney(detail.request.amount_paise)}</dd><dt>Accepted</dt><dd>{formatMoney(detail.accepted_paise)}</dd><dt>Remaining reservation</dt><dd>{formatMoney(detail.remaining_paise)}</dd><dt>Ended without movement</dt><dd>{formatMoney(detail.ended_paise)}</dd><dt>Occurred</dt><dd>{formatKolkata(detail.request.occurred_at)}</dd><dt>Reason</dt><dd>{detail.request.reason}</dd></dl>
 {canRequest&&detail.remaining_paise>0&&(detail.target_custodian_id===userId||admin||detail.source_custodian_id===userId)&&<Respond key={detail.request.id+'-'+detail.version} remaining={detail.remaining_paise} locked={locked} canReceive={detail.target_custodian_id===userId} canCancel={admin||detail.source_custodian_id===userId} submit={input=>run(source.respondHandover(detail.request.id,{...input,expected_version:detail.version,expected_source_version:detail.current_source_version,currency:'INR'}))}/>}
 <h3 className="t-title-md">Recorded acknowledgement history</h3>{detail.commands.length===0?<p>No acknowledgements recorded.</p>:<ol>{detail.commands.map(c=><li key={c.id}>{c.kind} · {formatMoney(c.amount_paise)} · {formatKolkata(c.recorded_at)} · {c.reason} · remaining {formatMoney(c.remaining_paise)}</li>)}</ol>}{detail.next_cursor&&<button className="btn btn-text" disabled={locked} onClick={()=>setBefore(detail.next_cursor!)}>Earlier acknowledgements</button>}{before!==undefined&&<button className="btn btn-text" disabled={locked} onClick={()=>setBefore(undefined)}>Latest acknowledgements</button>}
 </section>}</>;
}
function Respond({remaining,locked,canReceive,canCancel,submit}:{remaining:number;locked:boolean;canReceive:boolean;canCancel:boolean;submit:(input:Pick<CashHandoverCommandInput,'kind'|'amount_paise'|'reason'>)=>void}){const [kind,setKind]=useState<CashHandoverCommandInput['kind']>(canReceive?'accept':'cancel'),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState('');return <form className="ops-form" aria-label="Acknowledge cash handover" onSubmit={e=>{e.preventDefault();const paise=kind==='accept'?rupeesToPaise(amount):0;if(paise===null||kind==='accept'&&(paise===0||paise>remaining)||!reason.trim()){setError('Enter an amount within the remaining reservation and a reason.');return;}setError('');submit({kind,amount_paise:paise,reason:reason.trim()});}}><SelectField label="Custody response" aria-label="Custody response" value={kind} onChange={v=>setKind(v as typeof kind)} disabled={locked} options={[...(canReceive?[{value:'accept',label:'Accept actual cash'},{value:'reject',label:'Reject remaining cash'}]:[]),...(canCancel?[{value:'cancel',label:'Cancel remaining reservation'}]:[])]}/>{kind==='accept'&&<TextField label="Actually received cash (₹)" value={amount} onChange={setAmount} required disabled={locked}/>}<TextField label="Custody response reason" value={reason} onChange={setReason} required disabled={locked}/>{error&&<p role="alert">{error}</p>}<button className="btn btn-filled" disabled={locked}>Record custody response</button></form>;}
