import React,{useState} from 'react';
import type {CashLocationDto} from '@shippingco/shared';
import type {CashbookSource} from '../data-access/cashbook';
import {TextField,SelectField} from '../components/m3/Input';
import {kolkataInputToInstant} from './format';
export default function CashbookFilters({locations,locked,apply}:{locations:CashLocationDto[];locked:boolean;apply:(value:Parameters<CashbookSource['requests']>[0])=>void}){
 const [kind,setKind]=useState(''),[category,setCategory]=useState(''),[method,setMethod]=useState(''),[location,setLocation]=useState(''),[employee,setEmployee]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[error,setError]=useState('');
 return <form className="ops-form" aria-label="Filter expense and fund requests" onSubmit={e=>{e.preventDefault();const start=from?kolkataInputToInstant(from):undefined,end=to?kolkataInputToInstant(to):undefined;if(from&&!start||to&&!end||start&&end&&Date.parse(start)>=Date.parse(end)||employee&&!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(employee.trim())){setError('Use a valid employee reference and Kolkata time range with the end after the start.');return;}setError('');apply({kind,category,payment_method:method,source_location_id:location,responsible_employee_id:employee.trim(),from:start??undefined,to:end??undefined});}}><SelectField label="Filter request kind" aria-label="Filter request kind" value={kind} onChange={setKind} disabled={locked} options={[{value:'',label:'All request kinds'},...['expense','opening_float','owner_funds','deposit','withdrawal'].map(value=>({value,label:value.replaceAll('_',' ')}))]}/><SelectField label="Filter expense category" aria-label="Filter expense category" value={category} onChange={setCategory} disabled={locked} options={[{value:'',label:'All categories'},...['rent','utilities','supplies','transport','maintenance','other'].map(value=>({value,label:value}))]}/><SelectField label="Filter expense method" aria-label="Filter expense method" value={method} onChange={setMethod} disabled={locked} options={[{value:'',label:'All methods'},...['cash','upi','card','bank_transfer','other'].map(value=>({value,label:value.replaceAll('_',' ')}))]}/><SelectField label="Filter source location" aria-label="Filter source location" value={location} onChange={setLocation} disabled={locked} options={[{value:'',label:'All locations'},...locations.map(l=>({value:l.id,label:l.name}))]}/><TextField label="Filter responsible employee reference" value={employee} onChange={setEmployee} disabled={locked}/><TextField label="Filter occurred from (Kolkata)" type="datetime-local" value={from} onChange={setFrom} disabled={locked}/><TextField label="Filter occurred before (Kolkata; exclusive)" type="datetime-local" value={to} onChange={setTo} disabled={locked}/>{error&&<p role="alert">{error}</p>}<button className="btn btn-outlined" disabled={locked}>Apply request filters</button><button type="button" className="btn btn-text" disabled={locked} onClick={()=>{setKind('');setCategory('');setMethod('');setLocation('');setEmployee('');setFrom('');setTo('');setError('');apply({});}}>Clear request filters</button></form>;
}
