import React,{useMemo,useState} from 'react';
import type {CashLocationDto} from '@shippingco/shared';
import type {CashbookSource} from '../data-access/cashbook';
import type {ScopedApi} from '../data-access/scoped-api';
import type {CommandIntent} from '../data-access/command-intent';
import {receivingAccounts} from '../data-access/money-receipts';
import {TextField,SelectField} from '../components/m3/Input';
import {usePagedResource,useResource} from './hooks';
import {Empty,Failure,Loading} from './AsyncState';
export default function CashLocations({source,api,locations,employees,locked,revision,selected,select,run}:{source:CashbookSource;api:ScopedApi;locations:CashLocationDto[];employees:{id:string;label:string}[];locked:boolean;revision:number;selected:string|null;select:(id:string|null)=>void;run:(intent:CommandIntent)=>void}){
 const accounts=useMemo(()=>receivingAccounts(api),[api]),list=usePagedResource('accounts-'+revision,async(cursor,signal)=>{const r=await accounts.list(cursor??undefined,signal);return {items:r.items,page:{has_more:r.next_cursor!==null,next_cursor:r.next_cursor}};}),current=useResource('location-'+selected+'-'+revision,signal=>selected?source.location(selected,signal):Promise.resolve(null)),[reference,setReference]=useState('');
 const detail=current.value?.id===selected?current.value:null;
 return <section className="card ops-card"><h2 className="t-title-lg">Configure cash locations</h2><p>A cash location belongs to an actual receiving account and named current custodian. Noncash locations belong to an account. Account and custodian identity stay fixed; rename, deactivate or refresh the account revision through a new location revision.</p><p>Configure receiving accounts in Money receipts before creating locations.</p><div className="ops-list"><button className="btn btn-outlined" disabled={locked} onClick={()=>select(null)}>New cash location</button>{locations.map(l=><button className="btn btn-outlined" key={l.id} disabled={locked} onClick={()=>select(l.id)}>{l.name} · {l.kind} · version {l.version}</button>)}</div><form className="ops-form" aria-label="Open historical cash location" onSubmit={e=>{e.preventDefault();select(reference.trim());}}><TextField label="Cash location reference" value={reference} onChange={setReference} disabled={locked}/><button className="btn btn-outlined" disabled={locked||!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(reference.trim())}>Open location, including inactive</button></form>
 {list.phase==='loading'&&<Loading label="Loading actual receiving accounts…"/>}{list.phase==='error'&&<Failure retry={list.reload} label="Receiving accounts unavailable."/>}{list.page.has_more&&<button className="btn btn-text" disabled={locked||list.phase==='more'} onClick={list.loadMore}>Load more receiving accounts</button>}{selected&&current.phase==='loading'&&<Loading label="Loading current location revision…"/>}{selected&&current.phase==='error'&&<Failure retry={current.reload} label="Cash location unavailable."/>}{(!selected||detail)&&<Editor key={(detail?.id??'new')+'-'+(detail?.version??0)} original={detail} accounts={list.items} employees={employees} locked={locked||list.phase==='loading'} save={input=>run(source.configure(selected,input))}/>}</section>;
}
function Editor({original,accounts,employees,locked,save}:{original:CashLocationDto|null;accounts:Awaited<ReturnType<ReturnType<typeof receivingAccounts>['list']>>['items'];employees:{id:string;label:string}[];locked:boolean;save:(input:Parameters<CashbookSource['configure']>[1])=>void}){
 const [accountId,setAccountId]=useState(original?.account_id??''),[custodian,setCustodian]=useState(original?.custodian_id??''),[name,setName]=useState(original?.name??''),[active,setActive]=useState(original?.active??true),[error,setError]=useState(''),account=accounts.find(a=>a.id===accountId),cash=account?.methods.includes('cash')??original?.kind==='cash';
 return accounts.length===0?<Empty title="No receiving accounts" body="Configure an actual account in Money receipts."/>:<form className="ops-form" aria-label="Save cash location revision" onSubmit={e=>{e.preventDefault();if(!account||!name.trim()||cash&&!custodian){setError('Choose the actual account, cash custodian and location name.');return;}setError('');save({account_id:account.id,expected_account_version:account.version,custodian_id:cash?custodian:null,name:name.trim(),active,expected_version:original?.version??0});}}><SelectField label="Location receiving account" aria-label="Location receiving account" value={accountId} disabled={locked||!!original} onChange={v=>{setAccountId(v);setCustodian('');}} options={[{value:'',label:'Select actual account'},...accounts.map(a=>({value:a.id,label:a.name+(a.active?'':' · inactive')}))]}/>{cash&&<SelectField label="Named cash custodian" aria-label="Named cash custodian" value={custodian} onChange={setCustodian} disabled={locked||!!original} options={[{value:'',label:'Select current employee'},...employees.map(e=>({value:e.id,label:e.label})),...(original?.custodian_id&&!employees.some(e=>e.id===original.custodian_id)?[{value:original.custodian_id,label:'Recorded custodian '+original.custodian_id}]:[])]}/>}<TextField label="Cash location name" value={name} onChange={setName} required disabled={locked}/><SelectField label="Location availability" aria-label="Location availability" value={active?'active':'inactive'} disabled={locked} onChange={v=>setActive(v==='active')} options={[{value:'active',label:'Active for new movements'},{value:'inactive',label:'Inactive; retain historical evidence'}]}/>{account&&<p>Current account revision {account.version}; location revision {original?.version??0}. No account balance is implied.</p>}{error&&<p role="alert">{error}</p>}<button className="btn btn-filled" disabled={locked||!account||!name.trim()}>Save location revision</button></form>;
}
