import React,{useMemo,useState} from 'react';
import type { OperatorRole } from '@shippingco/shared';
import type { ScopeController } from '../operator/scope';
import { scopedApi } from '../data-access/scoped-api';
import { eway,type EwayCapture,type EwayCommand,type EwayCurrent,type EwayRecord } from '../data-access/eway';
import { useCommand,usePagedResource,useResource } from './hooks';
import { CommandNotice,Empty,Failure,Loading } from './AsyncState';
import { formatKolkata,formatMoney,localInputToInstant,rupeesToPaise } from './format';
import { SelectField,TextField } from '../components/m3/Input';
import { Msym } from '../components/m3/Icon';

const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const writable=(roles:readonly OperatorRole[])=>roles.some(role=>role==='franchise_admin'||role==='operator');
export default function Eway({controller,roles}:{controller:ScopeController;roles:readonly OperatorRole[]}){
 const api=useMemo(()=>scopedApi(controller),[controller]),source=useMemo(()=>eway(api),[api]);const reminders=usePagedResource('eway',(cursor,signal)=>source.reminders({limit:50,cursor},signal));const [booking,setBooking]=useState(''),[selected,setSelected]=useState<string|null>(null);
 return <div className="ops-page"><section className="card ops-card"><div className="u-between"><div><h1 className="t-headline-sm">External e-way records</h1><p className="ops-note">Observations remain unverified external facts. ShippingCo estimates are separately labelled and never replace official validity.</p></div><button className="btn btn-outlined" onClick={reminders.reload}><Msym name="refresh"/>Refresh reminders</button></div><form className="ops-form-grid" onSubmit={event=>{event.preventDefault();if(uuid.test(booking))setSelected(booking);}}><TextField label="Booking ID (UUID)" value={booking} onChange={setBooking}/><button className="btn btn-filled" disabled={!uuid.test(booking)}>Open booking record</button></form></section>
  {reminders.phase==='loading'?<Loading label="Loading e-way checks…"/>:reminders.phase==='error'?<Failure label="E-way checks could not be loaded." retry={reminders.reload}/>:reminders.phase==='empty'?<Empty icon="fact_check" title="No bookings on this page" body="The server returned no current reminder projections."/>:<section className="card ops-card"><h2 className="t-title-lg">Server-evaluated checks</h2><ul className="ops-list">{reminders.items.map(item=><li className="ops-row" key={item.booking_id}><span className="ops-row-main"><b className="ops-mono">{item.booking_id}</b><span>{item.external_reference??'No external reference recorded'}</span><span className="ops-note">{item.state.reminder_reasons.length?item.state.reminder_reasons.map(reason=>reason.replaceAll('_',' ')).join(' · '):'No current reminder reasons'} · evaluated {formatKolkata(item.state.evaluated_at)}</span></span><button className="btn btn-text" onClick={()=>setSelected(item.booking_id)}>Open</button></li>)}</ul>{reminders.page.has_more&&<button className="btn btn-outlined" disabled={reminders.phase==='more'} onClick={reminders.loadMore}>Load next page</button>}</section>}
  {selected&&<EwayDetail key={selected} bookingId={selected} source={source} roles={roles} close={()=>setSelected(null)} remindersReload={reminders.reload}/>}
 </div>;
}

function EwayDetail({bookingId,source,roles,close,remindersReload}:{bookingId:string;source:ReturnType<typeof eway>;roles:readonly OperatorRole[];close:()=>void;remindersReload:()=>void}){
 const current=useResource(bookingId,signal=>source.read(bookingId,signal));const history=usePagedResource(bookingId+'-history',(cursor,signal)=>source.history(bookingId,{limit:50,cursor},signal));const command=useCommand(value=>source.execute(value));
 if(current.phase==='loading')return <Loading label="Loading e-way record…"/>;if(current.phase==='error')return <Failure label="E-way record is unavailable." retry={current.reload}/>;const value=current.value!;const refresh=()=>{current.reload();history.reload();remindersReload();};
 async function run(next:EwayCommand){try{await command.run(source.intent(next));refresh();}catch{/* notice */}}
 return <section className="card ops-card ops-detail"><div className="u-between"><div><h2 className="t-headline-sm">Booking e-way record</h2><span className="ops-mono">{bookingId}</span></div><button className="btn btn-text" onClick={close}>Close detail</button></div><EwayStateView value={value}/>
  {writable(roles)&&(!value.record?<CaptureForm bookingId={bookingId} run={run} busy={command.phase==='pending'}/>:<><CorrectionForm bookingId={bookingId} record={value.record} run={run} busy={command.phase==='pending'}/><EstimateForm bookingId={bookingId} record={value.record} run={run} busy={command.phase==='pending'}/></>)}<CommandNotice phase={command.phase} code={command.error?.code} retry={command.canRetry?()=>{void command.retry().then(refresh).catch(()=>{});}:undefined}/>
  <section><h3>Immutable revision history</h3>{history.phase==='loading'?<p role="status">Loading history…</p>:history.phase==='error'?<button className="btn btn-outlined" onClick={history.reload}>Retry history</button>:history.phase==='empty'?<p role="status">No e-way revisions recorded.</p>:<><ul className="ops-list">{history.items.map(record=><li className="ops-row" key={record.record_id}><span className="ops-row-main"><b>Version {record.version}</b><span>{record.external?.reference??'No external reference'} · {record.declaration?formatMoney(record.declaration.value_paise):'No declared value'}</span><span className="ops-note">Captured {formatKolkata(record.captured_at)}{record.reason_code?` · ${record.reason_code.replaceAll('_',' ')}`:''}</span></span></li>)}</ul>{history.page.has_more&&<button className="btn btn-outlined" disabled={history.phase==='more'} onClick={history.loadMore}>Load next page</button>}</>}</section>
 </section>;
}

function EwayStateView({value}:{value:EwayCurrent}){const r=value.record,s=value.state;return <><div className="ops-facts"><Fact label="Record" value={s.reference_state}/><Fact label="Official validity" value={s.official_validity_state.replaceAll('_',' ')}/><Fact label="ShippingCo estimate" value={s.estimate_state}/><Fact label="Verification" value={s.verification_state.replaceAll('_',' ')}/><Fact label="Applicability" value={s.applicability_state}/><Fact label="Value check" value={s.value_check_state.replaceAll('_',' ')}/></div><p className={s.reminder_reasons.length?'ops-alert':'ops-success'} role="status">{s.reminder_reasons.length?`Review: ${s.reminder_reasons.map(reason=>reason.replaceAll('_',' ')).join(', ')}`:'The server returned no reminder reasons at this evaluation time.'}</p><p className="ops-note">Evaluated {formatKolkata(s.evaluated_at)} · policy {s.policy.state==='approved'?`${s.policy.id} v${s.policy.version}`:'no approved policy'} · applicability remains server-reported, never inferred by this UI.</p>{r&&<div className="ops-facts"><Fact label="Record version" value={r.version}/><Fact label="External reference" value={r.external?.reference??'Not recorded'}/><Fact label="Official until" value={r.external?.official_valid_until?formatKolkata(r.external.official_valid_until):'Unknown'}/><Fact label="Declared value" value={r.declaration?formatMoney(r.declaration.value_paise):'Unknown'}/><Fact label="Vehicle" value={r.vehicle_number??'Not in this projection'}/><Fact label="Distance" value={r.distance_km?`${r.distance_km} km`:'Not in this projection'}/><Fact label="Estimated until" value={r.estimate?formatKolkata(r.estimate.estimated_valid_until):'Absent'}/></div>}{r?.estimate&&<p className="ops-alert"><b>{r.estimate.label}</b><br/>Calculated {r.estimate.estimate_calculated_at?formatKolkata(r.estimate.estimate_calculated_at):'time unavailable'} from saved policy version {r.estimate.estimate_policy_version}.</p>}</>}

function CaptureForm({bookingId,run,busy}:{bookingId:string;run:(command:EwayCommand)=>Promise<void>;busy:boolean}){const fields=useCaptureFields();async function submit(event:React.FormEvent){event.preventDefault();const body=fields.capture();if(Object.values(body).every(value=>value===null))return;await run({kind:'create',bookingId,body});}return <section><h3>Capture external observation</h3><p className="ops-note">No fixed reference length, legal threshold or validity rule is assumed. The server validates policy-neutral input.</p><form className="ops-form" onSubmit={event=>{void submit(event);}}><CaptureFields fields={fields}/><button className="btn btn-filled" disabled={busy||!fields.valid}>Create record</button></form></section>}

function CorrectionForm({bookingId,record,run,busy}:{bookingId:string;record:EwayRecord;run:(command:EwayCommand)=>Promise<void>;busy:boolean}){const [target,setTarget]=useState<'declaration'|'external'|'vehicle_number'|'distance_km'>('external'),[clear,setClear]=useState(false),[reason,setReason]=useState<'metadata_correction'|'source_extension'|'declaration_correction'>('metadata_correction'),[reasonRef,setReasonRef]=useState('');const fields=useCaptureFields();
 async function submit(event:React.FormEvent){event.preventDefault();let patch:Partial<EwayCapture>;const captured=fields.capture();if(target==='declaration')patch={declaration:clear?null:captured.declaration};else if(target==='external')patch={external:clear?null:captured.external};else if(target==='vehicle_number')patch={vehicle_number:clear?null:captured.vehicle_number};else patch={distance_km:clear?null:captured.distance_km};await run({kind:'correct',bookingId,body:{...patch,expected_version:record.version,reason_code:reason,reason_ref:reasonRef}});}
 return <section><h3>Correct one captured field</h3><p className="ops-note">Omitted fields remain unchanged. “Clear selected field” sends an explicit null and preserves prior revisions.</p><form className="ops-form" onSubmit={event=>{void submit(event);}}><div className="ops-form-grid"><SelectField label="Correction target" value={target} onChange={value=>setTarget(value as typeof target)} options={[{value:'external',label:'External observation (atomic)'},{value:'declaration',label:'Declaration'},{value:'vehicle_number',label:'Vehicle number'},{value:'distance_km',label:'Distance'}]}/><SelectField label="Controlled reason" value={reason} onChange={value=>setReason(value as typeof reason)} options={['metadata_correction','source_extension','declaration_correction'].map(value=>({value,label:value.replaceAll('_',' ')}))}/><TextField label="Reason reference" value={reasonRef} onChange={setReasonRef} required/></div><label className="ops-check"><input type="checkbox" checked={clear} onChange={event=>setClear(event.target.checked)}/> Clear selected field</label>{!clear&&<CaptureFields fields={fields} only={target}/>}<button className="btn btn-outlined" disabled={busy||!reasonRef.trim()||(!clear&&!fields.validFor(target))}>Save correction</button></form></section>}

function EstimateForm({bookingId,record,run,busy}:{bookingId:string;record:EwayRecord;run:(command:EwayCommand)=>Promise<void>;busy:boolean}){const [starts,setStarts]=useState(''),[reason,setReason]=useState('');const instant=localInputToInstant(starts);return <section><h3>Request ShippingCo estimate</h3><p className="ops-note">Requires saved distance and an approved server policy. It never changes official validity.</p><form className="ops-form" onSubmit={event=>{event.preventDefault();if(instant)void run({kind:'estimate',bookingId,body:{expected_version:record.version,reason_ref:reason,starts_at:instant}});}}><div className="ops-form-grid"><TextField label="Estimate starts at (local)" type="datetime-local" value={starts} onChange={setStarts}/><TextField label="Reason reference" value={reason} onChange={setReason}/></div><button className="btn btn-outlined" disabled={busy||!instant||!reason.trim()}>Calculate with approved policy</button></form></section>}

function useCaptureFields(){const [amount,setAmount]=useState(''),[declarationSource,setDeclarationSource]=useState(''),[issuer,setIssuer]=useState(''),[reference,setReference]=useState(''),[sourceRef,setSourceRef]=useState(''),[issued,setIssued]=useState(''),[officialUntil,setOfficialUntil]=useState(''),[validityEvidence,setValidityEvidence]=useState(''),[vehicle,setVehicle]=useState(''),[distance,setDistance]=useState('');const paise=rupeesToPaise(amount),issuedAt=localInputToInstant(issued),untilAt=localInputToInstant(officialUntil),distanceNumber=Number(distance);
 const declaration=paise!==null&&declarationSource.trim()?{value_paise:paise,source_ref:declarationSource.trim()}:null;const external=issuer.trim()&&reference.trim()?{issuer:issuer.trim(),reference:reference.trim(),source_ref:sourceRef.trim()||null,issued_at:issued?issuedAt:null,official_valid_until:officialUntil?untilAt:null,validity_evidence_ref:validityEvidence.trim()||null}:null;const distanceValue=distance&&Number.isSafeInteger(distanceNumber)&&distanceNumber>0?distanceNumber:null;
 const capture=():EwayCapture=>({declaration,external,vehicle_number:vehicle.trim()||null,distance_km:distanceValue});const validFor=(target:'declaration'|'external'|'vehicle_number'|'distance_km')=>target==='declaration'?declaration!==null:target==='external'?external!==null&&(!issued||issuedAt!==null)&&(!officialUntil||untilAt!==null):target==='vehicle_number'?Boolean(vehicle.trim()):distanceValue!==null;return {amount,setAmount,declarationSource,setDeclarationSource,issuer,setIssuer,reference,setReference,sourceRef,setSourceRef,issued,setIssued,officialUntil,setOfficialUntil,validityEvidence,setValidityEvidence,vehicle,setVehicle,distance,setDistance,capture,validFor,valid:Object.values(capture()).some(value=>value!==null)};}
type CaptureState=ReturnType<typeof useCaptureFields>;
function CaptureFields({fields,only}:{fields:CaptureState;only?:'declaration'|'external'|'vehicle_number'|'distance_km'}){return <div className="ops-form-grid">{(!only||only==='declaration')&&<><TextField label="Declared value (₹)" value={fields.amount} onChange={fields.setAmount}/><TextField label="Declaration source reference" value={fields.declarationSource} onChange={fields.setDeclarationSource}/></>}{(!only||only==='external')&&<><TextField label="External issuer" value={fields.issuer} onChange={fields.setIssuer}/><TextField label="External reference" value={fields.reference} onChange={fields.setReference}/><TextField label="Source reference (optional)" value={fields.sourceRef} onChange={fields.setSourceRef}/><TextField label="Issued at (local, optional)" type="datetime-local" value={fields.issued} onChange={fields.setIssued}/><TextField label="Official valid until (local, optional)" type="datetime-local" value={fields.officialUntil} onChange={fields.setOfficialUntil}/><TextField label="Validity evidence reference (optional)" value={fields.validityEvidence} onChange={fields.setValidityEvidence}/></>}{(!only||only==='vehicle_number')&&<TextField label="Vehicle number (optional)" value={fields.vehicle} onChange={fields.setVehicle}/>} {(!only||only==='distance_km')&&<TextField label="Distance km (optional)" type="number" min="1" max="100000" value={fields.distance} onChange={fields.setDistance}/>}</div>}
function Fact({label,value}:{label:string;value:React.ReactNode}){return <div className="ops-fact"><span className="ops-note">{label}</span><b>{value}</b></div>}
