import React,{useEffect,useMemo,useRef,useState,useSyncExternalStore} from 'react';
import type {OperatorRole,FinancialProposalContext,FinancialProposalInput,FinancialRequestDto,FinancialRequestDetail,FinancialOwnRequest,FinancialChangeKind,FinancialDocumentInput,ReceivingAccountDto,ReceiptMethod} from '@shippingco/shared';
import {financialChangeKinds,financialComponentKeys} from '@shippingco/shared';
import type {ScopeController} from '../operator/scope';
import {scopedApi} from '../data-access/scoped-api';
import {financialWorkflow,type FinancialWorkflowSource} from '../data-access/financial-workflow';
import {financialAudit} from '../data-access/financial-audit';
import {receivingAccounts} from '../data-access/money-receipts';
import type {CommandIntent} from '../data-access/command-intent';
import {TextField,SelectField} from '../components/m3/Input';
import {useCommand,useResource,usePagedResource} from './hooks';
import {CommandNotice,Empty,Failure,Loading} from './AsyncState';
import {FinancialAuditView,exactMoney,financialLabels} from './FinancialAudit';
import {formatKolkata,rupeesToPaise,kolkataInputToInstant} from './format';
const has=(roles:readonly OperatorRole[],...allowed:OperatorRole[])=>roles.some(role=>allowed.includes(role));
const validId=(value:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value);
const componentLabels={pre_tax:'Pre-tax charge',taxable:'Taxable base',cgst:'CGST',sgst:'SGST',igst:'IGST',rounding:'Rounding'};
type Run=(intent:CommandIntent,target:string|null)=>Promise<void>;
export default function Financials({controller,roles}:{controller:ScopeController;roles:readonly OperatorRole[]}) {
 useSyncExternalStore(controller.subscribe,controller.snapshot,controller.snapshot);
 if(!has(roles,'operator','franchise_admin','org_admin','accountant')||!controller.runtime.ticket().authority)return <Empty title="Financial access unavailable" body="Select an authorized franchise to continue."/>;
 return <FinancialWorkspace key={controller.runtime.ticket().generation} controller={controller} roles={roles}/>;
}
function FinancialWorkspace({controller,roles}:{controller:ScopeController;roles:readonly OperatorRole[]}) {
 const api=useMemo(()=>scopedApi(controller),[controller]),source=useMemo(()=>financialWorkflow(api),[api]),audit=useMemo(()=>financialAudit(api),[api]),accounts=useMemo(()=>receivingAccounts(api),[api]);
 const canRequest=has(roles,'operator','franchise_admin'),canRead=has(roles,'franchise_admin','org_admin','accountant'),canDecide=has(roles,'franchise_admin');
 const [selected,setSelected]=useState<string|null>(null),[reference,setReference]=useState(''),[revision,setRevision]=useState(0),[amending,setAmending]=useState<FinancialOwnRequest|null>(null),[auditLocked,setAuditLocked]=useState(false),[blocked,setBlocked]=useState(false);
 const command=useCommand(source.execute),locked=auditLocked||command.phase==='pending'||command.phase==='uncertain',target=useRef<string|null>(null);
 const current=useResource((selected??'none')+'-'+revision,signal=>selected?(canRead?source.detail(selected,signal):source.own(selected,signal)):Promise.resolve(null));
 useEffect(()=>{const leave=(event:BeforeUnloadEvent)=>{if(locked){event.preventDefault();event.returnValue='';}};
 const navigate=(event:MouseEvent)=>{if(locked&&event.target instanceof Element&&event.target.closest('a[href]')){event.preventDefault();event.stopPropagation();setBlocked(true);}};
 const change=(event:Event)=>{if(locked&&event.target instanceof Element&&event.target.matches('select[aria-label="Franchise"]')){event.stopPropagation();(event.target as HTMLSelectElement).value=api.franchise;setBlocked(true);}};
 window.addEventListener('beforeunload',leave);document.addEventListener('click',navigate,true);document.addEventListener('change',change,true);
 return()=>{window.removeEventListener('beforeunload',leave);document.removeEventListener('click',navigate,true);document.removeEventListener('change',change,true);};},[locked,api.franchise]);
 const saved=(id:string)=>{if(target.current==='policy'){setRevision(value=>value+1);return;}setSelected(target.current??id);setAmending(null);setRevision(value=>value+1);};
 const run:Run=async(intent,id)=>{target.current=id;try{const value=await command.run(intent);if(controller.runtime.isCurrent(api.scope))saved(value.id);}catch{/* CommandNotice retains the safe outcome and original intent. */}};
 const retry=()=>{void command.retry().then(value=>{if(value&&controller.runtime.isCurrent(api.scope))saved(value.id);}).catch(()=>{});};
 const open=(id:string)=>{if(!locked){command.reset();setSelected(id);setAmending(null);setRevision(value=>value+1);}};
 return <div className="ops-page"><section className="card ops-card"><h1 id="workspace-title" tabIndex={-1} className="t-headline-sm">Financial approvals and refunds</h1><p>Propose a financial change, review its source amounts, then record its approved effect.</p><p className="ops-note">Financial cancellation does not cancel physical delivery. Recording a refund does not send money or verify bank settlement. Issued receipts and original tax evidence remain available.</p>
 <form className="ops-form" aria-label="Open financial request" onSubmit={event=>{event.preventDefault();if(validId(reference.trim()))open(reference.trim());}}><TextField label="Financial request reference" value={reference} onChange={setReference} disabled={locked}/><button className="btn btn-outlined" disabled={locked||!validId(reference.trim())}>Open saved request</button></form>
 <CommandNotice phase={command.phase} code={command.error?.code} retry={command.canRetry?retry:undefined}/>{blocked&&locked&&<p role="alert">Reconcile the retained request before changing franchise or leaving this workspace.</p>}
 {!locked&&<button className="btn btn-text" onClick={()=>{command.reset();setRevision(value=>value+1);current.reload();}}>Refresh current request state</button>}</section>
 {canDecide&&<PolicyConfiguration key={'policy-'+revision} source={source} locked={locked} run={run}/>}
 {selected&&current.phase==='loading'&&<Loading label="Loading live financial request…"/>}{selected&&current.phase==='error'&&<Failure retry={current.reload} label="This financial request is unavailable in the selected franchise."/>}
 {current.value&&<RequestEvidence value={current.value} canDecide={canDecide} canAmend={canRequest} self={api.scope.authority!.userId} locked={locked} source={source} accounts={accounts} run={run} amend={request=>{command.reset();setAmending({request,document_links:current.value?.document_links??[]});}}/>}
 {canRequest&&<ProposalForm key={(amending?.request.id??'new')+'-'+revision} source={source} locked={locked} run={run} amendment={amending} cancelAmend={()=>setAmending(null)}/>}
 {canRead&&<FinancialAuditView source={audit} canExport={has(roles,'franchise_admin','org_admin','accountant')} openRequest={open} parentLocked={command.phase==='pending'||command.phase==='uncertain'} busyChanged={setAuditLocked}/>}
 </div>;
}
function ProposalForm({source,locked,run,amendment,cancelAmend}:{source:FinancialWorkflowSource;locked:boolean;run:Run;amendment:FinancialOwnRequest|null;cancelAmend:()=>void}) {
 const previous=amendment?.request;
 const [booking,setBooking]=useState(previous?.booking_id??''),[loaded,setLoaded]=useState<string|null>(previous?.booking_id??null),[kind,setKind]=useState<FinancialChangeKind>(previous?.kind??'discount'),[reason,setReason]=useState<string>(previous?.reason??'customer_agreement');
 const [amounts,setAmounts]=useState<Record<string,string>>(Object.fromEntries(financialComponentKeys.map(key=>[key,previous?decimal(previous[key]):'0']))),[refund,setRefund]=useState(previous?decimal(previous.refund):''),[correction,setCorrection]=useState(previous?.refund_correction_of??''),[links,setLinks]=useState<FinancialDocumentInput[]>(amendment?.document_links.map(({kind,receipt_id,external_ref})=>({kind,receipt_id,external_ref}))??[]),[error,setError]=useState('');
 const observation=useResource(loaded??'none',signal=>loaded?source.context(loaded,signal):Promise.resolve(null));
 const reasons=kind==='discount'?['customer_agreement','service_recovery']:kind==='cancellation'?['booking_cancelled']:kind==='correction'?['incorrect_charge']:kind==='refund'?['customer_refund']:['incorrect_refund_recording'];
 const choose=(value:string)=>{const next=value as FinancialChangeKind;setKind(next);setReason(next==='discount'?'customer_agreement':next==='cancellation'?'booking_cancelled':next==='correction'?'incorrect_charge':next==='refund'?'customer_refund':'incorrect_refund_recording');setError('');};
 async function submit(context:FinancialProposalContext){
  setError('');const reductions=Object.fromEntries(financialComponentKeys.map(key=>[key,kind==='cancellation'?Number(context.components[key]):kind==='refund'||kind==='refund_correction'?0:key==='rounding'?signedPaise(amounts[key]??''):rupeesToPaise(amounts[key]??'')])) as Record<typeof financialComponentKeys[number],number|null>;
  const refunded=kind==='refund'||kind==='refund_correction'?rupeesToPaise(refund):0;
  if(Object.values(reductions).some(value=>value===null||!Number.isSafeInteger(value))||refunded===null){setError('Enter exact rupee amounts with at most two decimal places.');return;}
  const c=reductions as Record<typeof financialComponentKeys[number],number>,delta=BigInt(c.pre_tax)+BigInt(c.cgst)+BigInt(c.sgst)+BigInt(c.igst)+BigInt(c.rounding),remaining=Object.fromEntries(financialComponentKeys.map(key=>[key,BigInt(context.components[key])-BigInt(c[key])]));
  if(kind==='refund'||kind==='refund_correction'){
   const cap=kind==='refund'?context.position.refundable_credit:context.refund_targets.find(row=>row.id===correction)?.remaining_paise;
   if(!refunded||cap===undefined||BigInt(refunded)>BigInt(cap)){setError('Choose an available original refund and an amount within its remaining correction, or an actual refund within the available credit.');return;}
  }else if(delta<=0n||delta>BigInt(context.position.gross)||c.taxable>c.pre_tax||remaining.taxable!>remaining.pre_tax!||financialComponentKeys.some(key=>key==='rounding'?remaining[key]!< -99n||remaining[key]!>99n:remaining[key]!<0n)){setError('Reductions must fit the current component amounts and taxable base.');return;}
  const input:FinancialProposalInput={booking_id:context.booking_id,expected_version:context.expected_version,payment_version:context.payment_version,kind,reason:reason as FinancialProposalInput['reason'],...c,refund:refunded,refund_correction_of:kind==='refund_correction'?correction:null,document_links:links};
  try{await run(amendment?source.amend(amendment.request.id,input):source.request(input),null);}catch{setError('Refresh current source state before preparing a replacement.');}
 }
 return <section className="card ops-card"><h2 className="t-title-lg">{amendment?'Amend my pending proposal':'New financial proposal'}</h2><p className="ops-note">Amounts are component reductions. An amendment supersedes the pending proposal and needs a fresh decision. Every submission retains the source financial and payment versions.</p>
 <form className="ops-form" aria-label="Load proposal booking" onSubmit={event=>{event.preventDefault();if(validId(booking.trim())){setLoaded(booking.trim());observation.reload();}}}><TextField label="Proposal booking reference" value={booking} onChange={setBooking} disabled={locked||!!amendment}/><button className="btn btn-outlined" disabled={locked||!validId(booking.trim())}>Load current booking amounts</button></form>
 {loaded&&observation.phase==='loading'&&<Loading label="Loading selected booking amounts…"/>}{loaded&&observation.phase==='error'&&<Failure retry={observation.reload} label="Booking amounts are unavailable in this franchise."/>}
 {observation.value&&<><p>Current charge {exactMoney(observation.value.position.gross)} · outstanding {exactMoney(observation.value.position.outstanding)} · available refund credit {exactMoney(observation.value.position.refundable_credit)}</p><p>Financial version {observation.value.expected_version} · payment version {observation.value.payment_version}</p>
 <form className="ops-form" aria-label="Submit financial proposal" onSubmit={event=>{event.preventDefault();void submit(observation.value!);}}><SelectField label="Proposed action" value={kind} onChange={choose} disabled={locked} options={financialChangeKinds.map(value=>({value,label:financialLabels[value]}))}/><SelectField label="Proposal reason" value={reason} onChange={setReason} disabled={locked} options={reasons.map(value=>({value,label:value.replaceAll('_',' ')}))}/>
 {(kind==='discount'||kind==='correction')&&<div className="ops-form-grid">{financialComponentKeys.map(key=><TextField key={key} label={componentLabels[key]+' reduction (₹)'} value={amounts[key]??'0'} onChange={value=>setAmounts({...amounts,[key]:value})} inputMode="decimal" disabled={locked} helper={'Current '+decimal(observation.value!.components[key])+' rupees'}/>)}</div>}
 {kind==='cancellation'&&<p>Cancel the entire remaining charge of {exactMoney(observation.value.position.gross)}. Recorded collections remain held until a separate approved actual refund.</p>}
 {kind==='refund_correction'&&<SelectField label="Original refund to correct" value={correction} onChange={setCorrection} disabled={locked} options={[{value:'',label:'Choose original refund'},...observation.value.refund_targets.map(row=>({value:row.id,label:row.id+' · remaining '+exactMoney(row.remaining_paise)}))]}/>}
 {(kind==='refund'||kind==='refund_correction')&&<TextField label={kind==='refund'?'Actual refund amount (₹)':'Incorrectly recorded refund amount to restore (₹)'} value={refund} onChange={setRefund} inputMode="decimal" disabled={locked} helper={kind==='refund_correction'?'Restores held credit; records no new transfer.':'Records money already returned after approval; it does not initiate a transfer.'}/>}
 <DocumentFields links={links} setLinks={setLinks} locked={locked}/>{error&&<p role="alert">{error}</p>}<button className="btn btn-filled" disabled={locked}>{amendment?'Submit amended proposal':'Submit for financial approval'}</button></form></>}
 {amendment&&<button className="btn btn-text" disabled={locked} onClick={cancelAmend}>Cancel amendment draft</button>}</section>;
}
function decimal(value:string){const amount=BigInt(value),abs=amount<0n?-amount:amount;return `${amount<0n?'-':''}${abs/100n}.${(abs%100n).toString().padStart(2,'0')}`;}
function signedPaise(value:string){const negative=value.startsWith('-'),number=rupeesToPaise(negative?value.slice(1):value);return number===null?null:negative?-number:number;}
function DocumentFields({links,setLinks,locked}:{links:FinancialDocumentInput[];setLinks:(value:FinancialDocumentInput[])=>void;locked:boolean}) {
 return <fieldset disabled={locked} className="ops-form"><legend>Source documents (optional, up to ten)</legend><p className="ops-note">Issued receipt links are checked in this franchise. Invoice and credit-note references remain labelled unverified.</p>{links.map((link,index)=><div className="ops-form-grid" key={index}><SelectField label={'Document '+(index+1)+' kind'} value={link.kind} onChange={value=>setLinks(links.map((row,i)=>i===index?{kind:value as FinancialDocumentInput['kind']}:row))} options={['issued_receipt','external_invoice','external_credit_note'].map(value=>({value,label:value.replaceAll('_',' ')}))}/><TextField label={'Document '+(index+1)+' reference'} value={link.receipt_id??link.external_ref??''} onChange={value=>setLinks(links.map((row,i)=>i===index?{kind:row.kind,...row.kind==='issued_receipt'?{receipt_id:value.trim()}:{external_ref:value.trim()}}:row))}/><button type="button" className="btn btn-text" onClick={()=>setLinks(links.filter((_,i)=>i!==index))}>Remove document {index+1}</button></div>)}<button className="btn btn-text" type="button" disabled={locked||links.length>=10} onClick={()=>setLinks([...links,{kind:'issued_receipt',receipt_id:''}])}>Add source document</button></fieldset>;
}
function RequestEvidence({value,canDecide,canAmend,self,locked,source,accounts,run,amend}:{value:FinancialOwnRequest|FinancialRequestDetail;canDecide:boolean;canAmend:boolean;self:string;locked:boolean;source:FinancialWorkflowSource;accounts:ReturnType<typeof receivingAccounts>;run:Run;amend:(request:FinancialRequestDto)=>void}) {
 const request=value.request,detail='before' in value?value:null,heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{heading.current?.focus();},[request.id,request.version]);
 return <section className="card ops-card"><h2 ref={heading} tabIndex={-1} className="t-title-lg">Live {financialLabels[request.kind].toLowerCase()} request · {request.outcome}</h2><dl className="history-facts"><dt>Request</dt><dd className="ops-mono">{request.id}</dd><dt>Booking</dt><dd className="ops-mono">{request.booking_id}</dd><dt>Proposed by</dt><dd className="ops-mono">{request.actor_id}</dd><dt>Recorded</dt><dd>{formatKolkata(request.recorded_at)}</dd><dt>Reason</dt><dd>{request.reason.replaceAll('_',' ')}</dd><dt>Source versions</dt><dd>Financial {request.expected_version} · payment {request.payment_version}</dd><dt>Policy revision</dt><dd className="ops-mono">{request.policy_id??'No configured policy'}</dd><dt>Refund amount</dt><dd>{exactMoney(request.refund)}</dd>{financialComponentKeys.map(key=><React.Fragment key={key}><dt>{componentLabels[key]} reduction</dt><dd>{decimal(request[key])} rupees</dd></React.Fragment>)}<dt>Corrects refund</dt><dd className="ops-mono">{request.refund_correction_of??'None'}</dd></dl>
 {detail&&<><h3>Server preview from the saved source versions</h3><dl className="history-facts">{(['gross','held','outstanding','refundable_credit'] as const).map(key=><React.Fragment key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{exactMoney(detail.before[key])} → {exactMoney(detail.proposed[key])}</dd></React.Fragment>)}</dl><p className="ops-note">This preview uses the proposal's original source versions. Applying requires unchanged live source versions and policy.</p><ul className="ops-list" aria-label="Live decision history">{detail.decisions.map(row=><li key={row.id}>{row.outcome} · {row.actor_id} · {formatKolkata(row.recorded_at)}</li>)}</ul></>}
 <ul className="ops-list" aria-label="Live source documents">{value.document_links.map((row,index)=><li key={index}>{row.kind.replaceAll('_',' ')} · {row.receipt_id??row.external_ref} · {row.qualification==='issued_source'?'Issued source receipt':'Unverified external reference'}</li>)}</ul>
 {canAmend&&request.outcome==='pending'&&request.actor_id===self&&<button className="btn btn-outlined" disabled={locked} onClick={()=>amend(request)}>Amend my pending proposal</button>}
 {canDecide&&detail&&request.outcome==='pending'&&<><p className="ops-note">The server enforces the configured review threshold and self-approval policy. A cash-close approval does not qualify this decision.</p><button className="btn btn-filled" disabled={locked} onClick={()=>{void run(source.decide(request.id,'approved'),request.id);}}>Approve financial proposal</button><button className="btn btn-outlined" disabled={locked} onClick={()=>{void run(source.decide(request.id,'rejected'),request.id);}}>Reject financial proposal</button></>}
 {canDecide&&detail&&request.outcome==='approved'&&(request.kind==='refund'?<RefundApply request={request} source={source} accounts={accounts} locked={locked} run={run}/>:<button className="btn btn-filled" disabled={locked} onClick={()=>{void run(source.apply(request.id,{expected_version:1}),request.id);}}>Apply approved financial change</button>)}
 </section>;
}
function RefundApply({request,source,accounts,locked,run}:{request:FinancialRequestDto;source:FinancialWorkflowSource;accounts:ReturnType<typeof receivingAccounts>;locked:boolean;run:Run}) {
 const list=usePagedResource('refund-accounts',(cursor,signal)=>accounts.list(cursor??undefined,signal).then(value=>({items:value.items,page:{has_more:value.next_cursor!==null,next_cursor:value.next_cursor}})));
 const [accountId,setAccountId]=useState(''),[method,setMethod]=useState<ReceiptMethod>('cash'),[occurred,setOccurred]=useState(''),[beneficiary,setBeneficiary]=useState(''),[reference,setReference]=useState(''),[error,setError]=useState('');
 const account:ReceivingAccountDto|undefined=list.items.find(row=>row.id===accountId&&row.active);
 function submit(){const instant=kolkataInputToInstant(occurred),ref=/^[A-Za-z0-9][A-Za-z0-9:_-]{0,127}$/;
 if(!account||!account.methods.includes(method)||!instant||Date.parse(instant)>Date.now()||!ref.test(beneficiary)||!ref.test(reference)){setError('Choose an active source account and method, a past Kolkata time, and valid private beneficiary and transfer references.');return;}
 setError('');void run(source.apply(request.id,{expected_version:1,refund_evidence:{account_id:account.id,expected_account_version:account.version,method,occurred_at:instant,returned_to_ref:beneficiary,transfer_ref:reference}}),request.id);
 }
 return <><h3>Record actual refund of {exactMoney(request.refund)}</h3><p className="ops-note">Record the actual return using private evidence. These references do not establish provider settlement and are excluded from the shared audit.</p>{list.phase==='loading'?<Loading label="Loading refund source accounts…"/>:list.phase==='error'?<Failure retry={list.reload} label="Refund source accounts unavailable."/>:<form className="ops-form" aria-label="Record approved actual refund" onSubmit={event=>{event.preventDefault();submit();}}><SelectField label="Refund source account" value={accountId} disabled={locked} onChange={value=>{setAccountId(value);const a=list.items.find(row=>row.id===value);setMethod(a?.methods[0]??'cash');}} options={[{value:'',label:'Choose source account'},...list.items.filter(row=>row.active).map(row=>({value:row.id,label:row.name}))]}/><SelectField label="Actual return method" value={method} onChange={value=>setMethod(value as ReceiptMethod)} disabled={locked||!account} options={(account?.methods??[]).map(value=>({value,label:value==='other'?account!.other_method_name??'Other':value.replaceAll('_',' ')}))}/><TextField label="Actual refund time (Kolkata)" type="datetime-local" value={occurred} onChange={setOccurred} disabled={locked}/><TextField label="Private beneficiary reference" value={beneficiary} onChange={setBeneficiary} disabled={locked}/><TextField label="Private actual transfer reference" value={reference} onChange={setReference} disabled={locked}/>{error&&<p role="alert">{error}</p>}<button className="btn btn-filled" disabled={locked}>Record approved actual refund</button></form>}{list.page.has_more&&<button className="btn btn-text" disabled={locked||list.phase==='more'} onClick={list.loadMore}>More refund source accounts</button>}</>;
}

function PolicyConfiguration({source,locked,run}:{source:FinancialWorkflowSource;locked:boolean;run:Run}) {
 const state=useResource('financial-policy',signal=>source.policy(signal)),[enabled,setEnabled]=useState('true');
 useEffect(()=>{if(state.value?.policy)setEnabled(String(state.value.policy.enabled));},[state.value]);
 return <section className="card ops-card"><h2 className="t-title-lg">Franchise financial approval policy</h2><p className="ops-note">Every request needs an admin decision. A different admin must approve the submitter's request. There is no preset monetary threshold for additional review. Quote-price tolerances are unchanged.</p>
 {state.phase==='loading'?<Loading label="Loading current financial policy…"/>:state.phase==='error'?<Failure retry={state.reload} label="Financial policy unavailable."/>:state.value&&<><p>Policy revision: {state.value.policy?.version??'Not configured'} · workflow writes: {state.value.writes_enabled?'Enabled by server rollout':'Disabled by server rollout'}</p><p className="ops-note">Saving appends an immutable policy revision. Pending requests need their creator to amend against the new policy. An approved request under an older policy cannot be applied; prepare a new proposal with fresh source versions. Disabling retains approval governance; it does not reopen legacy adjustment writes.</p><form className="ops-form" aria-label="Configure financial approval policy" onSubmit={event=>{event.preventDefault();void run(source.configurePolicy({expected_version:state.value!.policy?.version??0,enabled:enabled==='true',discount_review_threshold_paise:null,allow_self_approval:false}),'policy');}}><SelectField label="Financial approval policy state" value={enabled} onChange={setEnabled} disabled={locked} options={[{value:'true',label:'Enable approved policy'},{value:'false',label:'Disable new approvals and applications'}]}/><button className="btn btn-outlined" disabled={locked}>Save approved financial policy revision</button></form></>}
 </section>;
}
