import React,{useEffect,useRef,useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {financialAuditKinds,financialAuditStatuses,type FinancialAuditPage,type FinancialAuditRow,type FinancialAuditFilter} from '@shippingco/shared';
import type {FinancialAuditSource} from '../data-access/financial-audit';
import {TextField,SelectField} from '../components/m3/Input';
import {useCommand} from './hooks';
import {CommandNotice,Loading} from './AsyncState';
import {formatKolkata} from './format';
export const financialLabels:Record<FinancialAuditRow['kind'],string>={discount:'Discount',cancellation:'Financial cancellation',correction:'Charge correction',refund:'Actual refund record',refund_correction:'Correct refund record',request_amendment:'Amended proposal',price_override:'Price override',collection_correction:'Correct collection',receipt_correction:'Release bill allocation',deletion_denied:'Deletion denied'};
export const exactMoney=(paise:string|null)=>paise===null?'Unknown':`₹${(BigInt(paise)/100n).toLocaleString('en-IN')}.${(BigInt(paise)%100n).toString().padStart(2,'0')}`;
export function FinancialAuditView({source,canExport,openRequest,parentLocked=false,busyChanged}:{source:FinancialAuditSource;canExport:boolean;openRequest:(id:string)=>void;parentLocked?:boolean;busyChanged?:(busy:boolean)=>void}) {
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const [from,setFrom]=useState(today),[to,setTo]=useState(today),[kind,setKind]=useState(''),[status,setStatus]=useState(''),[actor,setActor]=useState(''),[booking,setBooking]=useState('');
 const [params,setParams]=useSearchParams(),id=params.get('finance_snapshot'),[revision,setRevision]=useState(0),[page,setPage]=useState<FinancialAuditPage|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[detail,setDetail]=useState<FinancialAuditRow|null>(null);
 const command=useCommand(source.execute),locked=parentLocked||busy||command.phase==='pending'||command.phase==='uncertain',heading=useRef<HTMLHeadingElement>(null),returnFocus=useRef<HTMLElement|null>(null),lifetime=useRef({generation:0});
 useEffect(()=>{const guard=lifetime.current;guard.generation++;return()=>{guard.generation++;};},[]);
 useEffect(()=>{busyChanged?.(busy||command.phase==='pending'||command.phase==='uncertain');return()=>busyChanged?.(false);},[busy,command.phase,busyChanged]);
 useEffect(()=>{if(detail)heading.current?.focus();},[detail]);
 const failure=()=>setNotice('Financial evidence is unavailable, expired or changed. Check access and retry the saved snapshot.');
 useEffect(()=>{lifetime.current.generation++;const abort=new AbortController();setPage(null);setDetail(null);setBusy(false);if(!id)return()=>abort.abort();setBusy(true);
  void source.page(id,0,abort.signal).then(value=>{if(!abort.signal.aborted){setPage(value);const f=value.snapshot.filter;setFrom(f.from_day);setTo(f.to_day);setKind(f.kind??'');setStatus(f.status??'');setActor(f.actor_id??'');setBooking(f.booking_id??'');}}).catch(()=>{if(!abort.signal.aborted)failure();}).finally(()=>{if(!abort.signal.aborted)setBusy(false);});return()=>abort.abort();
 },[id,revision,source]);
 async function capture(retry=false){if(parentLocked||busy||command.phase==='pending')return;setNotice('');const generation=lifetime.current.generation;
  try{const filter:FinancialAuditFilter={from_day:from,to_day:to,sort:'confirmed_desc',kind:(kind||null) as FinancialAuditFilter['kind'],status:(status||null) as FinancialAuditFilter['status'],actor_id:actor.trim()||null,booking_id:booking.trim()||null};const result=await(retry?command.retry():command.run(source.intent(filter)));if(result&&generation===lifetime.current.generation){setParams({finance_snapshot:result.snapshot.id});setNotice('Audit snapshot saved. Detail, counts and CSV use this capture.');}}
  catch{if(generation===lifetime.current.generation)failure();}
 }
 async function more(){if(!page||page.next_offset===null||locked)return;setBusy(true);const generation=lifetime.current.generation;try{const value=await source.page(page.snapshot.id,page.next_offset);if(generation===lifetime.current.generation)setPage({...value,rows:[...page.rows,...value.rows]});}catch{if(generation===lifetime.current.generation)failure();}finally{if(generation===lifetime.current.generation)setBusy(false);}}
 async function inspect(row:FinancialAuditRow,button:HTMLElement){if(!page||locked)return;setBusy(true);returnFocus.current=button;const generation=lifetime.current.generation;try{const value=await source.detail(page.snapshot.id,row.id);if(generation===lifetime.current.generation)setDetail(value.row);}catch{if(generation===lifetime.current.generation)failure();}finally{if(generation===lifetime.current.generation)setBusy(false);}}
 async function download(){if(!page||!canExport||locked)return;setBusy(true);const generation=lifetime.current.generation;try{const value=await source.export(page.snapshot.id);if(generation!==lifetime.current.generation)return;const url=URL.createObjectURL(new Blob([value.csv],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=`financial-audit-${value.snapshot.id}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Matching audit CSV ready. Check your downloads.');}catch{if(generation===lifetime.current.generation)failure();}finally{if(generation===lifetime.current.generation)setBusy(false);}}
 return <div className="ops-page"><section className="card ops-card"><h1 className="t-headline-sm">Financial review audit</h1><p className="ops-note">Capture recorded actions in this franchise. Each amount uses its labelled basis; audit counts are not a sum of money transferred.</p>
 <form className="ops-form" aria-label="Financial audit filters" onSubmit={event=>{event.preventDefault();void capture();}}><div className="ops-form-grid">
 <TextField label="From recorded day" type="date" value={from} onChange={setFrom} disabled={locked}/><TextField label="Through recorded day" type="date" value={to} onChange={setTo} disabled={locked}/>
 <SelectField label="Action kind" value={kind} onChange={setKind} disabled={locked} options={[{value:'',label:'All actions'},...financialAuditKinds.map(value=>({value,label:financialLabels[value]}))]}/>
 <SelectField label="Captured status" value={status} onChange={setStatus} disabled={locked} options={[{value:'',label:'All statuses'},...financialAuditStatuses.map(value=>({value,label:value}))]}/>
 <TextField label="Actor reference (optional)" value={actor} onChange={setActor} disabled={locked}/><TextField label="Booking reference (optional)" value={booking} onChange={setBooking} disabled={locked}/></div>
 <button className="btn btn-filled" disabled={locked}>Capture financial audit</button></form>
 <CommandNotice phase={command.phase} code={command.error?.code} retry={command.canRetry?()=>{void capture(true);}:undefined}/>{notice&&<p role="status" aria-live="polite">{notice}</p>}
 {id&&<button className="btn btn-text" disabled={locked} onClick={()=>{command.reset();setRevision(value=>value+1);}}>Reload saved audit</button>}
 </section>{busy&&<Loading label="Loading captured financial evidence…"/>}
 {page&&<section className="card ops-card"><h2 className="t-title-lg">{page.snapshot.count} captured actions</h2><p>Captured {formatKolkata(page.snapshot.as_of)} · expires {formatKolkata(page.snapshot.expires_at)}</p><p className="ops-note">Status is from this snapshot. Open a live request to review its current state before deciding or applying it.</p>
 <ul className="ops-list" aria-label="Captured action counts">{Object.entries(page.snapshot.counts).map(([action,count])=><li key={action}>{financialLabels[action as FinancialAuditRow['kind']]}: {count}</li>)}</ul>
 <button className="btn btn-outlined" disabled={!canExport||locked} onClick={()=>{void download();}}>Download matching financial CSV</button>
 {!page.rows.length?<p role="status">No financial actions match these filters. CSV contains headers.</p>:<ul className="ops-list" aria-label="Financial audit actions">{page.rows.map(row=><li className="ops-row" key={row.id}><div className="ops-row-main"><b>{financialLabels[row.kind]} · {row.status}</b><span className="ops-mono">{row.source_id}</span><span>{row.amount_basis.replaceAll('_',' ')}: {exactMoney(row.before_paise)} → {exactMoney(row.proposed_paise)}</span><span>{formatKolkata(row.recorded_at)}</span></div><button className="btn btn-outlined" disabled={locked} onClick={event=>{void inspect(row,event.currentTarget);}}>View {financialLabels[row.kind].toLowerCase()} evidence {row.source_id.slice(-8)}</button></li>)}</ul>}
 {page.next_offset!==null&&<button className="btn btn-text" disabled={locked} onClick={()=>{void more();}}>More captured actions</button>}</section>}
 {detail&&<section className="card ops-card" aria-labelledby="financial-evidence-title"><h2 id="financial-evidence-title" ref={heading} tabIndex={-1} className="t-title-lg">Captured {financialLabels[detail.kind].toLowerCase()} evidence</h2><dl className="history-facts">
 <dt>Source</dt><dd>{detail.source_type.replaceAll('_',' ')} <span className="ops-mono">{detail.source_id}</span></dd><dt>Actor</dt><dd className="ops-mono">{detail.actor_id}</dd><dt>Reason</dt><dd>{detail.reason.replaceAll('_',' ')}</dd><dt>Recorded</dt><dd>{formatKolkata(detail.recorded_at)}</dd><dt>Amount basis</dt><dd>{detail.amount_basis.replaceAll('_',' ')}</dd><dt>Before</dt><dd>{exactMoney(detail.before_paise)}</dd><dt>Proposed</dt><dd>{exactMoney(detail.proposed_paise)}</dd><dt>Approval basis</dt><dd>{detail.approval_basis.replaceAll('_',' ')}</dd><dt>Review threshold</dt><dd>{detail.approval_threshold_paise===null?(detail.approval_basis==='financial_policy'?'No preset monetary threshold':'Unknown or not configured'):exactMoney(detail.approval_threshold_paise)}</dd><dt>Linked original</dt><dd className="ops-mono">{detail.correction_of??'None recorded'}</dd></dl>
 <ul className="ops-list" aria-label="Captured approval history">{detail.decisions.map(decision=><li key={decision.id}>{decision.outcome} · <span className="ops-mono">{decision.actor_id}</span> · {formatKolkata(decision.recorded_at)}</li>)}</ul>
 <ul className="ops-list" aria-label="Source documents">{detail.document_links.map((link,index)=><li key={index}>{link.kind.replaceAll('_',' ')} · <span className="ops-mono">{link.receipt_id??link.external_ref}</span> · {link.qualification==='issued_source'?'Issued source receipt':'Unverified external reference'}</li>)}</ul>
 {detail.source_type==='financial_request'&&<button className="btn btn-outlined" disabled={locked} onClick={()=>openRequest(detail.source_id)}>Open live financial request</button>}
 <button className="btn btn-text" onClick={()=>{setDetail(null);returnFocus.current?.focus();}}>Close captured evidence</button></section>}
 </div>;
}
