import React,{useMemo,useState} from 'react';
import type { LotDto,LotMembershipDto,LotMembershipResult,OperatorRole } from '@shippingco/shared';
import type { ScopeController } from '../operator/scope';
import { scopedApi } from '../data-access/scoped-api';
import { lots } from '../data-access/lots';
import { useCommand,usePagedResource,useResource } from './hooks';
import { CommandNotice,Empty,Failure,Loading } from './AsyncState';
import { formatKolkata } from './format';
import { SelectField,TextField } from '../components/m3/Input';
import { Msym } from '../components/m3/Icon';

const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const canWrite=(roles:readonly OperatorRole[])=>roles.some(role=>['franchise_admin','operator','dispatcher'].includes(role));
export default function Lots({controller,roles}:{controller:ScopeController;roles:readonly OperatorRole[]}){
 const api=useMemo(()=>scopedApi(controller),[controller]),source=useMemo(()=>lots(api),[api]);
 const [state,setState]=useState<'active'|'archived'>('active'),[selected,setSelected]=useState<string|null>(null);
 const page=usePagedResource(state,(cursor,signal)=>source.list({state,limit:50,cursor},signal));
 return <div className="ops-page"><section className="card ops-card"><div className="u-between"><div><h1 className="t-headline-sm">Lots</h1><p className="ops-note">Server-owned parcel groups. Archive retains history; there is no delete action.</p></div><button className="btn btn-outlined" onClick={page.reload}><Msym name="refresh"/>Refresh</button></div><SelectField label="Lot state" value={state} onChange={value=>{setState(value as typeof state);setSelected(null);}} options={[{value:'active',label:'Active lots'},{value:'archived',label:'Archived lots'}]}/></section>
  {state==='active'&&canWrite(roles)&&<CreateLot source={source} confirmed={page.reload}/>}
  {page.phase==='loading'?<Loading label="Loading lots…"/>:page.phase==='error'?<Failure label="Lots could not be loaded." retry={page.reload}/>:page.phase==='empty'?<Empty icon="layers" title={`No ${state} lots`} body={state==='active'?'Create a bounded operational group when parcels are ready.':'Archived lot history will appear here.'}/>:<section className="card ops-card"><ul className="ops-list">{page.items.map(lot=><li className="ops-row" key={lot.id}><span className="ops-row-main"><b>{lot.code} · {lot.name}</b><span>{lot.destination_key}</span><span className="ops-note">{lot.active_member_count} active members · version {lot.version} · {formatKolkata(lot.updated_at)}</span></span><button className="btn btn-text" onClick={()=>setSelected(lot.id)}>Open</button></li>)}</ul>{page.page.has_more&&<button className="btn btn-outlined" disabled={page.phase==='more'} onClick={page.loadMore}>{page.phase==='more'?'Loading…':'Load next page'}</button>}</section>}
  {selected&&<LotDetail key={selected} lotId={selected} source={source} roles={roles} close={()=>setSelected(null)} listReload={page.reload}/>}
 </div>;
}

function CreateLot({source,confirmed}:{source:ReturnType<typeof lots>;confirmed:()=>void}){
 const [name,setName]=useState(''),[destination,setDestination]=useState('');const command=useCommand<LotDto|LotMembershipResult>(value=>source.execute(value));
 async function submit(event:React.FormEvent){event.preventDefault();try{await command.run(source.intent({kind:'create',body:{name:name.trim(),destination_key:destination.trim()}}));setName('');setDestination('');confirmed();}catch{/* notice */}}
 return <section className="card ops-card"><h2 className="t-title-lg">Create lot</h2><form className="ops-form" onSubmit={event=>{void submit(event);}}><div className="ops-form-grid"><TextField label="Lot name" value={name} onChange={setName} required/><TextField label="Destination key" value={destination} onChange={setDestination} required helper="Use the server-approved routing destination key."/></div><button className="btn btn-filled" disabled={command.phase==='pending'||!name.trim()||!destination.trim()}>Create lot</button></form><CommandNotice phase={command.phase} code={command.error?.code} retry={command.canRetry?()=>{void command.retry().then(confirmed).catch(()=>{});}:undefined}/></section>;
}

function LotDetail({lotId,source,roles,close,listReload}:{lotId:string;source:ReturnType<typeof lots>;roles:readonly OperatorRole[];close:()=>void;listReload:()=>void}){
 const detail=useResource(lotId,signal=>source.read(lotId,signal));
 const members=usePagedResource(lotId+'-members',(cursor,signal)=>source.memberships(lotId,{state:'active',limit:50,cursor},signal));
 const command=useCommand<LotDto|LotMembershipResult>(value=>source.execute(value));
 const [name,setName]=useState(''),[parcelId,setParcelId]=useState(''),[moveParcel,setMoveParcel]=useState<LotMembershipDto|null>(null),[targetLot,setTargetLot]=useState(''),[targetVersion,setTargetVersion]=useState(''),[ungrouped,setUngrouped]=useState<string|null>(null);
 if(detail.phase==='loading')return <Loading label="Loading lot detail…"/>;if(detail.phase==='error')return <Failure label="Lot detail is unavailable." retry={detail.reload}/>;
 const lot=detail.value!;const write=canWrite(roles)&&lot.state==='active';const refresh=()=>{detail.reload();members.reload();listReload();};
 async function run(intent:Parameters<typeof command.run>[0]){try{await command.run(intent);setUngrouped(null);refresh();setParcelId('');setMoveParcel(null);setTargetLot('');setTargetVersion('');}catch{/* notice */}}
 async function remove(member:LotMembershipDto){try{await command.run(source.intent({kind:'remove',lotId:lot.id,parcelId:member.parcel_id,body:{expected_version:lot.version,membership_id:member.id}}));try{const current=await source.currentMembership(member.parcel_id);setUngrouped(current===null?member.parcel_id:null);}finally{refresh();}}catch{/* notice */}}
 return <section className="card ops-card ops-detail" aria-labelledby="lot-detail-title"><div className="u-between"><div><h2 id="lot-detail-title" className="t-headline-sm">{lot.code} · {lot.name}</h2><span className="ops-pill">{lot.state}</span></div><button className="btn btn-text" onClick={close}>Close detail</button></div><div className="ops-facts"><Fact label="Destination" value={lot.destination_key}/><Fact label="Server version" value={lot.version}/><Fact label="Active members" value={lot.active_member_count}/><Fact label="Updated" value={formatKolkata(lot.updated_at)}/></div>
  {write&&<><form className="ops-form" onSubmit={event=>{event.preventDefault();void run(source.intent({kind:'update',lotId:lot.id,body:{expected_version:lot.version,name:name.trim()||lot.name}}));}}><div className="ops-form-grid"><TextField label="New lot name" value={name} onChange={setName} placeholder={lot.name}/><span className="ops-actions"><button className="btn btn-outlined" disabled={command.phase==='pending'||!name.trim()}>Save name</button>{roles.includes('franchise_admin')&&<button type="button" className="btn btn-text" disabled={command.phase==='pending'} onClick={()=>{void run(source.intent({kind:'archive',lotId:lot.id,body:{expected_version:lot.version}}));}}>Archive lot</button>}</span></div></form><form className="ops-form" onSubmit={event=>{event.preventDefault();void run(source.intent({kind:'add',lotId:lot.id,body:{expected_version:lot.version,parcel_id:parcelId}}));}}><div className="ops-form-grid"><TextField label="Parcel ID to add (UUID)" value={parcelId} onChange={setParcelId}/><button className="btn btn-filled" disabled={command.phase==='pending'||!uuid.test(parcelId)}>Add parcel</button></div></form></>}
  <CommandNotice phase={command.phase} code={command.error?.code} retry={command.canRetry?()=>{void command.retry().then(refresh).catch(()=>{});}:undefined}/>{ungrouped&&<p className="ops-success" role="status">Server confirms parcel <span className="ops-mono">{ungrouped}</span> is now ungrouped.</p>}
  <section><h3>Active memberships</h3>{members.phase==='loading'?<p role="status">Loading memberships…</p>:members.phase==='error'?<button className="btn btn-outlined" onClick={members.reload}>Retry memberships</button>:members.phase==='empty'?<p role="status">This lot has no active memberships.</p>:<><ul className="ops-list">{members.items.map(member=><MemberRow key={member.id} member={member} lot={lot} write={write} busy={command.phase==='pending'} remove={()=>{void remove(member);}} move={()=>setMoveParcel(member)}/>)}</ul>{members.page.has_more&&<button className="btn btn-outlined" disabled={members.phase==='more'} onClick={members.loadMore}>Load next page</button>}</>}</section>
  {moveParcel&&<form className="ops-form ops-alert" onSubmit={event=>{event.preventDefault();void run(source.intent({kind:'move',lotId:lot.id,parcelId:moveParcel.parcel_id,body:{expected_version:lot.version,membership_id:moveParcel.id,target_lot_id:targetLot,expected_target_version:Number(targetVersion)}}));}}><h3>Move exact membership</h3><p className="ops-note">The destination version is read from its authoritative detail. A stale version returns a safe conflict.</p><div className="ops-form-grid"><TextField label="Target active lot ID (UUID)" value={targetLot} onChange={setTargetLot}/><TextField label="Target lot version" type="number" min="1" value={targetVersion} onChange={setTargetVersion}/></div><div className="ops-actions"><button className="btn btn-filled" disabled={!uuid.test(targetLot)||!Number.isSafeInteger(Number(targetVersion))||Number(targetVersion)<1}>Confirm move</button><button type="button" className="btn btn-text" onClick={()=>setMoveParcel(null)}>Cancel</button></div></form>}
 </section>;
}
function MemberRow({member,lot,write,busy,remove,move}:{member:LotMembershipDto;lot:LotDto;write:boolean;busy:boolean;remove:()=>void;move:()=>void}){return <li className="ops-row"><span className="ops-row-main"><b className="ops-mono">{member.parcel_id}</b><span className="ops-note">Membership {member.id} · since {formatKolkata(member.started_at)}</span></span>{write&&<span className="ops-row-actions"><button className="btn btn-outlined" disabled={busy||lot.state!=='active'} onClick={move}>Move</button><button className="btn btn-text" disabled={busy||lot.state!=='active'} onClick={remove}>Remove</button></span>}</li>}
function Fact({label,value}:{label:string;value:React.ReactNode}){return <div className="ops-fact"><span className="ops-note">{label}</span><b>{value}</b></div>}
