import {useLocation} from 'react-router-dom';
import React,{useEffect,useMemo,useState} from 'react';
import type {CustomerDto,MoneyReceiptResult,OperatorRole,ReceiptAllocationInput,ReceiptMethod,ReceivingAccountDto} from '@shippingco/shared';
import type {ScopeController} from '../operator/scope';
import {scopedApi} from '../data-access/scoped-api';
import {moneyReceipts,receivingAccounts} from '../data-access/money-receipts';
import {customers} from '../data-access/customers';
import {useCommand,usePagedResource,useResource} from './hooks';
import {CommandNotice,Empty,Failure,Loading} from './AsyncState';
import {TextField,SelectField} from '../components/m3/Input';
import {formatMoney,formatKolkata,instantToKolkataInput,kolkataInputToInstant,rupeesToPaise} from './format';
const has=(roles:readonly OperatorRole[],...wanted:OperatorRole[])=>roles.some(role=>wanted.includes(role));
const methodLabels:Record<ReceiptMethod,string>={cash:'Cash',upi:'UPI',card:'Card',bank_transfer:'Bank transfer',other:'Named other method'};
const methods=Object.keys(methodLabels) as ReceiptMethod[];
const paged=<T,>(value:{items:T[];next_cursor:string|null})=>({items:value.items,page:{has_more:value.next_cursor!==null,next_cursor:value.next_cursor}});
type Source=ReturnType<typeof moneyReceipts>;
type ReceiptCustomer=Pick<CustomerDto,'id'|'name'>;
type Bill=Awaited<ReturnType<Source['bills']>>['items'][number];
export default function MoneyReceipts({controller,roles}:{controller:ScopeController;roles:readonly OperatorRole[]}){
 if(!has(roles,'operator','franchise_admin','accountant','org_admin'))return <Empty title="Receipt access unavailable" body="This role cannot record or read customer receipts."/>;
 return <ReceiptWorkspace controller={controller} roles={roles}/>;
}
function ReceiptWorkspace({controller,roles}:{controller:ScopeController;roles:readonly OperatorRole[]}){
 const location=useLocation(),parameters=useMemo(()=>new URLSearchParams(location.search),[location.search]),linkedCustomer=parameters.get('customer_id'),linkedContext=parameters.get('context')==='paid_counter'?'paid_counter':'to_pay';
 const api=useMemo(()=>scopedApi(controller),[controller]),source=useMemo(()=>moneyReceipts(api),[api]),accounts=useMemo(()=>receivingAccounts(api),[api]),customerSource=useMemo(()=>customers(api),[api]);
 const canChooseCustomer=has(roles,'operator','franchise_admin');
 const [receiptReference,setReceiptReference]=useState(''),[requestedReceipt,setRequestedReceipt]=useState<string|null>(null);
 const [search,setSearch]=useState(''),[query,setQuery]=useState(''),[customer,setCustomer]=useState<ReceiptCustomer|null>(null),[selected,setSelected]=useState<string|null>(null),[revision,setRevision]=useState(0),[accountLocked,setAccountLocked]=useState(false),[navigationBlocked,setNavigationBlocked]=useState(false);
 const command=useCommand(intent=>source.execute(intent)),locked=command.phase==='pending'||command.phase==='uncertain'||accountLocked;
 const preselected=useResource(linkedCustomer??'none',signal=>canChooseCustomer&&linkedCustomer&&/^[0-9a-f-]{36}$/.test(linkedCustomer)?customerSource.read(linkedCustomer,signal):Promise.resolve(null));
 useEffect(()=>{if(preselected.value)setCustomer(preselected.value);},[preselected.value]);
 const referenced=useResource('reference-'+requestedReceipt,signal=>requestedReceipt?source.read(requestedReceipt,signal):Promise.resolve(null));
 useEffect(()=>{if(referenced.value){setCustomer({id:referenced.value.receipt.customer_id,name:'Customer '+referenced.value.receipt.customer_id});setSelected(referenced.value.receipt.id);}},[referenced.value]);
 const matches=usePagedResource(query,(cursor,signal)=>query?customerSource.search('name',query,signal,cursor??undefined):Promise.resolve({items:[],page:{has_more:false,next_cursor:null}}));
 const accountList=usePagedResource('accounts',(cursor,signal)=>accounts.list(cursor??undefined,signal).then(paged));
 useEffect(()=>{const prevent=(event:BeforeUnloadEvent)=>{if(locked){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent);},[locked]);
 useEffect(()=>{const prevent=(event:MouseEvent)=>{if(locked&&event.target instanceof Element&&event.target.closest('a[href]')){event.preventDefault();event.stopPropagation();setNavigationBlocked(true);}};document.addEventListener('click',prevent,true);return()=>document.removeEventListener('click',prevent,true);},[locked]);
 const refresh=()=>{setRevision(value=>value+1);accountList.reload();};
 const confirmed=(result:MoneyReceiptResult|null)=>{if(result){setSelected(result.receipt_id);refresh();}};
 const run=async(intent:Parameters<Source['execute']>[0])=>{const result=await command.run(intent);confirmed(result);return result;};
 return <div className="ops-page"><section className="card ops-card"><h1 id="workspace-title" tabIndex={-1} className="t-headline-sm">Money receipts</h1><p>Record actual money once, then apply it to this customer's bills. Unallocated money remains a customer advance.</p><p className="ops-note">Manual evidence is unverified. A screenshot or bank reference alone does not establish settlement.</p>
  {canChooseCustomer&&<form className="ops-form" aria-label="Find receipt customer" onSubmit={event=>{event.preventDefault();setQuery(search.trim());}}><TextField label="Customer name prefix" value={search} onChange={setSearch} disabled={locked} helper="At least three letters or digits; search within this franchise."/><button className="btn btn-outlined" disabled={locked||search.trim().length<3}>Search customers</button></form>}
  {query&&matches.phase==='loading'?<Loading label="Searching customers…"/>:matches.phase==='error'?<Failure retry={matches.reload} label="Customer search unavailable."/>:<ul className="ops-list">{matches.items.map(row=><li key={row.id}><button className="btn btn-text" disabled={locked} onClick={()=>{command.reset();setCustomer(row);setSelected(null);}}>{row.name} · {row.phone_display}</button></li>)}</ul>}{matches.page.has_more&&<button className="btn btn-text" disabled={locked||matches.phase==='more'} onClick={matches.loadMore}>More customers</button>}
  {!canChooseCustomer&&<form className="ops-form" aria-label="Open finance receipt" onSubmit={event=>{event.preventDefault();setCustomer(null);setSelected(null);setRequestedReceipt(receiptReference.trim());}}><TextField label="Receipt reference" value={receiptReference} onChange={setReceiptReference} disabled={locked} helper="Use the saved receipt ID supplied for this selected franchise; no customer-directory search."/><button className="btn btn-outlined" disabled={locked||!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(receiptReference.trim())}>Open finance receipt</button></form>}
  {requestedReceipt&&referenced.phase==='loading'&&<Loading label="Loading referenced receipt…"/>}
  {requestedReceipt&&referenced.phase==='error'&&<Failure retry={referenced.reload} label="The receipt is unavailable in this franchise."/>}
  {customer&&<p role="status">Selected customer: <b>{customer.name}</b></p>}
  {navigationBlocked&&locked&&<p role="alert">Finish or reconcile the retained request before leaving this receipt workspace.</p>}
  <CommandNotice phase={command.phase} code={command.error?.code} retry={command.canRetry?()=>{void command.retry().then(confirmed).catch(()=>{});}:undefined}/>
  {!locked&&<button className="btn btn-text" onClick={()=>{command.reset();refresh();}}>Refresh saved receipt state</button>}
 </section>
 {accountList.phase==='loading'?<Loading label="Loading receiving accounts…"/>:accountList.phase==='error'?<Failure retry={accountList.reload} label="Receiving accounts unavailable."/>:has(roles,'franchise_admin')?<AccountConfiguration source={accounts} items={accountList.items} refreshed={accountList.reload} parentLocked={command.phase==='pending'||command.phase==='uncertain'} busyChanged={setAccountLocked}/>:null}
 {accountList.page.has_more&&<button className="btn btn-text" onClick={accountList.loadMore} disabled={accountList.phase==='more'}>More receiving accounts</button>}
 {canChooseCustomer&&linkedCustomer&&preselected.phase==='error'&&<Failure retry={preselected.reload} label="The linked customer is unavailable in this franchise."/>}
 {customer&&<CustomerReceipts key={customer.id} source={source} customer={customer} accounts={accountList.items} roles={roles} selected={selected} select={setSelected} revision={revision} locked={locked} run={run} self={api.scope.authority!.userId} initialContext={linkedContext}/>}
 </div>;
}
function CustomerReceipts({source,customer,accounts,roles,selected,select,revision,locked,run,self,initialContext}:{source:Source;customer:ReceiptCustomer;accounts:ReceivingAccountDto[];roles:readonly OperatorRole[];selected:string|null;select:(id:string)=>void;revision:number;locked:boolean;run:(intent:Parameters<Source['execute']>[0])=>Promise<MoneyReceiptResult>;self:string;initialContext:'paid_counter'|'to_pay'}){
 const bills=usePagedResource(customer.id+'-bills-'+revision,(cursor,signal)=>source.bills(customer.id,cursor??undefined,signal).then(paged)),receipts=usePagedResource(customer.id+'-receipts-'+revision,(cursor,signal)=>source.list(customer.id,cursor??undefined,signal).then(paged));
 const writable=has(roles,'operator','franchise_admin');
 return <><section className="card ops-card"><h2>Customer bills</h2>{bills.phase==='loading'?<Loading label="Loading current bills…"/>:bills.phase==='error'?<Failure retry={bills.reload} label="Current bills unavailable."/>:<ul className="ops-list">{bills.items.map(bill=><li key={bill.booking_id} className="ops-row"><span className="ops-row-main">Booking {bill.booking_id}<span className="ops-note">Outstanding {formatMoney(bill.outstanding_paise)} · payment version {bill.expected_payment_version}</span></span></li>)}</ul>}{bills.page.has_more&&<button className="btn btn-text" disabled={locked||bills.phase==='more'} onClick={bills.loadMore}>More bills</button>}</section>
 {writable&&bills.phase!=='loading'&&bills.phase!=='error'&&<RecordReceipt key={'record-'+revision} source={source} customer={customer} accounts={accounts.filter(a=>a.active)} bills={bills.items} locked={locked} run={run} self={self} initialContext={initialContext}/>}
 <section className="card ops-card"><h2>Saved money receipts</h2>{receipts.phase==='loading'?<Loading label="Loading saved receipts…"/>:receipts.phase==='error'?<Failure retry={receipts.reload} label="Saved receipts unavailable."/>:!receipts.items.length?<Empty title="No recorded receipts" body="A new receipt can be held entirely as an advance."/>:<ul className="ops-list">{receipts.items.map(receipt=><li className="ops-row" key={receipt.receipt_id}><span className="ops-row-main"><b>{formatMoney(receipt.received_paise)} received</b><span>Applied {formatMoney(receipt.allocated_paise)} · Advance {formatMoney(receipt.unallocated_paise)}</span><span className="ops-note">Receipt {receipt.receipt_id} · version {receipt.version}</span></span><button className="btn btn-outlined" disabled={locked} onClick={()=>select(receipt.receipt_id)}>Open receipt</button></li>)}</ul>}{receipts.page.has_more&&<button className="btn btn-text" disabled={locked||receipts.phase==='more'} onClick={receipts.loadMore}>More receipts</button>}</section>
 {selected&&<ReceiptDetail key={selected+'-'+revision} id={selected} source={source} roles={roles} bills={bills.items} locked={locked} run={run}/>}
 </>;
}
function AllocationFields({bills,amounts,setAmounts,disabled}:{bills:Bill[];amounts:Record<string,string>;setAmounts:(value:Record<string,string>)=>void;disabled:boolean}){
 return <fieldset disabled={disabled} className="ops-form"><legend>Apply to bills (optional for a new receipt)</legend>{bills.filter(b=>b.outstanding_paise>0).map(bill=><TextField key={bill.booking_id} label={'Apply to booking '+bill.booking_id.slice(-8)} aria-label={'Apply to booking '+bill.booking_id} error={amounts[bill.booking_id]?.trim()&&(!rupeesToPaise(amounts[bill.booking_id]!)||rupeesToPaise(amounts[bill.booking_id]!)!>bill.outstanding_paise)?'Enter a positive amount within this bill’s outstanding balance.':undefined} value={amounts[bill.booking_id]??''} inputMode="decimal" onChange={value=>setAmounts({...amounts,[bill.booking_id]:value})} helper={'Booking '+bill.booking_id+' · Outstanding '+formatMoney(bill.outstanding_paise)}/>)}</fieldset>;
}
function allocationInput(bills:Bill[],amounts:Record<string,string>,context:'paid_counter'|'to_pay'='to_pay'):ReceiptAllocationInput[]|null{
 const result:ReceiptAllocationInput[]=[];
 for(const bill of bills){const value=amounts[bill.booking_id];if(!value?.trim())continue;const amount=rupeesToPaise(value);if(!amount||amount>bill.outstanding_paise)return null;result.push({booking_id:bill.booking_id,amount_paise:amount,context,expected_payment_version:bill.expected_payment_version});}
 return result.length>50||result.reduce((sum,a)=>sum+BigInt(a.amount_paise),0n)>BigInt(Number.MAX_SAFE_INTEGER)?null:result;
}
function RecordReceipt({source,customer,accounts,bills,locked,run,self,initialContext}:{source:Source;customer:ReceiptCustomer;accounts:ReceivingAccountDto[];bills:Bill[];locked:boolean;run:(intent:Parameters<Source['execute']>[0])=>Promise<MoneyReceiptResult>;self:string;initialContext:'paid_counter'|'to_pay'}){
 const [context,setContext]=useState<'paid_counter'|'to_pay'>(initialContext);
 const [accountId,setAccountId]=useState(''),[method,setMethod]=useState<ReceiptMethod>('cash'),[amount,setAmount]=useState(''),[external,setExternal]=useState(''),[occurred,setOccurred]=useState(()=>instantToKolkataInput(new Date().toISOString())??''),[receiver,setReceiver]=useState(self),[amounts,setAmounts]=useState<Record<string,string>>({});
 const people=usePagedResource('receivers',(cursor,signal)=>source.receivers(cursor??undefined,signal).then(paged));
 const account=accounts.find(a=>a.id===accountId),input=allocationInput(bills,amounts,context),paise=rupeesToPaise(amount),time=kolkataInputToInstant(occurred),applied=input?.reduce((sum,a)=>sum+BigInt(a.amount_paise),0n)??0n;
 const valid=account&&account.methods.includes(method)&&paise&&time&&Date.parse(time)<=Date.now()&&input&&applied<=BigInt(paise)&&people.items.some(p=>p.id===receiver)&&external.length<=128;
 async function submit(event:React.FormEvent){event.preventDefault();if(!valid||!account||!paise||!time||!input)return;try{await run(source.record({customer_id:customer.id,account_id:account.id,expected_account_version:account.version,method,amount_paise:paise,currency:'INR',receiver_id:receiver,custodian_id:receiver,occurred_at:time,external_reference:external.trim()||null,allocations:input}));}catch{/* parent retains the exact uncertain intent */}}
 return <section className="card ops-card"><h2>Record money received</h2>{!accounts.length?<p role="status">An administrator must configure a receiving account or cash drawer first.</p>:<form className="ops-form" onSubmit={event=>{void submit(event);}}><fieldset disabled={locked}><div className="ops-form-grid"><TextField label="Amount received (₹)" error={amount.trim()&&!paise?'Enter a positive amount within the supported range, with at most two decimals.':undefined} value={amount} onChange={setAmount} inputMode="decimal" required/><SelectField label="Receiving account / cash drawer" value={accountId} onChange={value=>{setAccountId(value);setMethod(accounts.find(a=>a.id===value)?.methods[0]??'cash');}} options={[{value:'',label:'Select receiving destination'},...accounts.map(a=>({value:a.id,label:a.name}))]}/><SelectField label="Receipt method" value={method} onChange={value=>setMethod(value as ReceiptMethod)} options={(account?.methods??[]).map(m=>({value:m,label:m==='other'?account?.other_method_name??'Named other':methodLabels[m]}))}/><TextField label="Money received at (Asia/Kolkata)" error={occurred&&(!time||Date.parse(time)>Date.now())?'Enter a valid time when money was received, up to the current time.':undefined} type="datetime-local" value={occurred} onChange={setOccurred} required/><SelectField label="Receiver / initial custodian" value={receiver} onChange={setReceiver} options={people.items.map(p=>({value:p.id,label:p.label}))}/><TextField label="Private external reference (optional)" value={external} onChange={setExternal} maxLength={128} helper="No card number, CVV, banking password or screenshot verification claim."/></div></fieldset>
 {people.phase==='error'&&<Failure retry={people.reload} label="Eligible receivers unavailable."/>}{people.page.has_more&&<button type="button" className="btn btn-text" disabled={locked} onClick={people.loadMore}>More eligible receivers</button>}
 <SelectField label="Payment context" value={context} disabled={locked} onChange={value=>setContext(value as typeof context)} options={[{value:'to_pay',label:'To Pay bill collection'},{value:'paid_counter',label:'Paid at counter'}]}/>
 <AllocationFields bills={bills} amounts={amounts} setAmounts={setAmounts} disabled={locked}/>{input===null&&<p role="alert">Review bill amounts and the supported allocation limit.</p>}{paise&&input&&applied>BigInt(paise)&&<p role="alert">Applied bill amounts exceed the money received. Reduce the applications or correct the receipt amount.</p>}<p role="status">Applied {formatMoney(Number(applied))} · Remaining advance {formatMoney(paise&&applied<=BigInt(paise)?paise-Number(applied):0)}</p><button className="btn btn-filled" disabled={locked||!valid}>Confirm money received</button></form>}</section>;
}
function ReceiptDetail({id,source,roles,bills,locked,run}:{id:string;source:Source;roles:readonly OperatorRole[];bills:Bill[];locked:boolean;run:(intent:Parameters<Source['execute']>[0])=>Promise<MoneyReceiptResult>}){
 const balance=useResource(id,signal=>source.balance(id,signal)),history=usePagedResource(id+'-history',(cursor,signal)=>source.history(id,cursor??undefined,signal).then(paged)),finance=has(roles,'org_admin','franchise_admin','accountant');
 const evidence=useResource(id+'-'+finance,signal=>finance?source.read(id,signal):Promise.resolve(null));
 const [amounts,setAmounts]=useState<Record<string,string>>({}),[target,setTarget]=useState(''),[release,setRelease]=useState(''),[reason,setReason]=useState<'incorrect_amount'|'duplicate_recording'|'collection_not_received'>('incorrect_amount');
 if(balance.phase==='loading')return <Loading label="Loading receipt balance…"/>;if(balance.phase==='error')return <Failure retry={balance.reload} label="Receipt balance unavailable."/>;
 const result=balance.value!,allocations=allocationInput(bills,amounts),applied=allocations?.reduce((sum,a)=>sum+BigInt(a.amount_paise),0n)??0n,entry=history.items.find(a=>a.id===target),paise=rupeesToPaise(release);
 async function apply(event:React.FormEvent){event.preventDefault();if(!allocations?.length||applied>BigInt(result.unallocated_paise))return;try{await run(source.allocate(id,{expected_version:result.version,allocations}));}catch{/* parent notice */}}
 async function correct(event:React.FormEvent){event.preventDefault();if(!entry||!paise||paise>entry.amount_paise-entry.released_paise)return;try{await run(source.correct(id,{expected_version:result.version,allocation_id:entry.id,amount_paise:paise,currency:'INR',reason_code:reason}));}catch{/* parent notice */}}
 return <section className="card ops-card"><h2>Receipt {id}</h2><p>Received {formatMoney(result.received_paise)} · Applied {formatMoney(result.allocated_paise)} · Advance {formatMoney(result.unallocated_paise)}</p>
 {finance&&(evidence.phase==='loading'?<Loading label="Loading private finance evidence…"/>:evidence.phase==='error'?<Failure retry={evidence.reload} label="Private evidence unavailable."/>:evidence.value&&<dl className="ops-facts"><div><dt>Actual money received</dt><dd>{formatKolkata(evidence.value.receipt.occurred_at)}</dd></div><div><dt>Server recorded</dt><dd>{formatKolkata(evidence.value.receipt.recorded_at)}</dd></div><div><dt>Method / receiving account</dt><dd>{methodLabels[evidence.value.receipt.method]} · {evidence.value.receipt.account_id}</dd></div><div><dt>Receiver / initial custodian</dt><dd>{evidence.value.receipt.receiver_id}</dd></div><div><dt>Private reference</dt><dd>{evidence.value.receipt.external_reference??'Not supplied'}</dd></div><div><dt>Verification</dt><dd>Manually recorded · unverified</dd></div></dl>)}
 {has(roles,'operator','franchise_admin')&&result.unallocated_paise>0&&<form className="ops-form" onSubmit={event=>{void apply(event);}}><h3>Apply existing advance</h3><p>This applies funds already received and creates no new inflow.</p><AllocationFields bills={bills} amounts={amounts} setAmounts={setAmounts} disabled={locked}/>{allocations===null&&<p role="alert">Review bill amounts and the supported allocation limit.</p>}{allocations&&applied>BigInt(result.unallocated_paise)&&<p role="alert">These applications exceed the available advance. Reduce the selected bill amounts.</p>}<button className="btn btn-filled" disabled={locked||!allocations?.length||applied>BigInt(result.unallocated_paise)}>Apply advance to selected bills</button></form>}
 <h3>Allocation history</h3>{history.phase==='loading'?<Loading label="Loading allocation history…"/>:history.phase==='error'?<Failure retry={history.reload} label="Allocation history unavailable."/>:<ul className="ops-list">{history.items.map(a=><li className="ops-row" key={a.id}><span className="ops-row-main"><b>{a.kind==='allocation'?'Applied':'Released'} {formatMoney(a.amount_paise)}</b><span>Booking {a.booking_id} · version {a.version}</span><span className="ops-note">{formatKolkata(a.recorded_at)} · {a.id}{a.kind==='allocation'?' · released '+formatMoney(a.released_paise):' · original '+a.release_of}</span></span></li>)}</ul>}{history.page.has_more&&<button className="btn btn-text" disabled={locked} onClick={history.loadMore}>More allocation history</button>}
 {has(roles,'franchise_admin')&&<form className="ops-form" onSubmit={event=>{void correct(event);}}><h3>Release an incorrect allocation</h3><p>The original evidence stays saved. Released funds return to this customer's advance; this does not refund cash.</p><fieldset disabled={locked}><div className="ops-form-grid"><SelectField label="Original allocation" value={target} onChange={setTarget} options={[{value:'',label:'Select saved allocation'},...history.items.filter(a=>a.kind==='allocation'&&a.released_paise<a.amount_paise).map(a=>({value:a.id,label:a.booking_id+' · available '+formatMoney(a.amount_paise-a.released_paise)}))]}/><TextField label="Release amount (₹)" error={release.trim()&&(!paise||(entry&&paise>entry.amount_paise-entry.released_paise))?'Enter a positive amount within the original allocation’s remaining releasable funds.':undefined} value={release} onChange={setRelease} inputMode="decimal"/><SelectField label="Correction reason" value={reason} onChange={value=>setReason(value as typeof reason)} options={[{value:'incorrect_amount',label:'Incorrect amount'},{value:'duplicate_recording',label:'Duplicate recording'},{value:'collection_not_received',label:'Collection not received'}]}/></div></fieldset><button className="btn btn-outlined" disabled={locked||!entry||!paise||paise>entry.amount_paise-entry.released_paise}>Release allocation (admin)</button></form>}
 </section>;
}
function AccountConfiguration({source,items,refreshed,parentLocked,busyChanged}:{source:ReturnType<typeof receivingAccounts>;items:ReceivingAccountDto[];refreshed:()=>void;parentLocked:boolean;busyChanged:(value:boolean)=>void}){
 const [id,setId]=useState<string|null>(null),[name,setName]=useState(''),[selected,setSelected]=useState<ReceiptMethod[]>(['cash']),[other,setOther]=useState(''),[active,setActive]=useState(true);
 const command=useCommand(intent=>source.execute(intent)),ownLocked=command.phase==='pending'||command.phase==='uncertain',locked=ownLocked||parentLocked,account=items.find(a=>a.id===id);
 useEffect(()=>{busyChanged(ownLocked);return()=>busyChanged(false);},[ownLocked,busyChanged]);
 const choose=(a:ReceivingAccountDto|null)=>{command.reset();setId(a?.id??null);setName(a?.name??'');setSelected(a?.methods??['cash']);setOther(a?.other_method_name??'');setActive(a?.active??true);};
 const toggle=(method:ReceiptMethod)=>{if(method==='cash'){setSelected(['cash']);return;}setSelected(current=>current.includes(method)?current.filter(m=>m!==method):[...current.filter(m=>m!=='cash'),method]);};
 async function submit(event:React.FormEvent){event.preventDefault();try{await command.run(source.configure(id,{name:name.trim(),methods:selected,other_method_name:selected.includes('other')?other.trim():null,active,expected_version:account?.version??0}));refreshed();choose(null);}catch{/* exact retry retained */}}
 return <section className="card ops-card"><h2>Receiving accounts (administrator)</h2><ul className="ops-list">{items.map(a=><li key={a.id} className="ops-row"><span className="ops-row-main">{a.name} · {a.active?'Active':'Inactive'} · version {a.version}</span><button className="btn btn-text" disabled={locked} onClick={()=>choose(a)}>Edit account</button></li>)}</ul><button className="btn btn-text" disabled={locked} onClick={()=>choose(null)}>New receiving account</button>
 <form className="ops-form" onSubmit={event=>{void submit(event);}}><fieldset disabled={locked}><legend>{id?'Append account revision':'Configure receiving destination'}</legend><TextField label="Account / drawer name" value={name} onChange={setName} maxLength={120} required/><fieldset><legend>Allowed methods (cash has its own drawer)</legend>{methods.map(m=><label key={m}><input type="checkbox" checked={selected.includes(m)} onChange={()=>toggle(m)}/>{methodLabels[m]} </label>)}</fieldset>{selected.includes('other')&&<TextField label="Named other method" value={other} onChange={setOther} maxLength={60} required/>}<label><input type="checkbox" checked={active} onChange={event=>setActive(event.target.checked)}/>Active for new receipts</label></fieldset><button className="btn btn-outlined" disabled={locked||!name.trim()||!selected.length||(selected.includes('other')&&!other.trim())}>Save receiving account</button></form><CommandNotice phase={command.phase} code={command.error?.code} retry={command.canRetry?()=>{void command.retry().then(()=>{refreshed();choose(null);}).catch(()=>{});}:undefined}/>
 </section>;
}
