import React,{useMemo,useState} from 'react';
import type { OperatorRole,RouteDto,RouteEventInput,RouteEventResult } from '@shippingco/shared';
import type { ScopeController } from '../operator/scope';
import { scopedApi } from '../data-access/scoped-api';
import { routes } from '../data-access/routes';
import { useCommand,usePagedResource,useResource } from './hooks';
import { CommandNotice,Empty,Failure,Loading } from './AsyncState';
import { formatKolkata,localInputToInstant } from './format';
import { SelectField,TextField } from '../components/m3/Input';
import { Msym } from '../components/m3/Icon';

const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const canWrite=(roles:readonly OperatorRole[])=>roles.some(role=>['franchise_admin','operator','dispatcher'].includes(role));
const modeOptions=['road','rail','air','sea'].map(value=>({value,label:value}));
export default function Routes({controller,roles}:{controller:ScopeController;roles:readonly OperatorRole[]}){
 const api=useMemo(()=>scopedApi(controller),[controller]),source=useMemo(()=>routes(api),[api]);
 const [state,setState]=useState<RouteDto['state']|'all'>('all'),[selected,setSelected]=useState<string|null>(null);
 const page=usePagedResource(state,(cursor,signal)=>source.list({state:state==='all'?undefined:state,limit:50,cursor},signal));
 return <div className="ops-page"><section className="card ops-card"><div className="u-between"><div><h1 className="t-headline-sm">Routes</h1><p className="ops-note">Planning manifests are editable. Finalization freezes a snapshot; it does not record departure.</p></div><button className="btn btn-outlined" onClick={page.reload}><Msym name="refresh"/>Refresh</button></div><SelectField label="Route state" value={state} onChange={value=>{setState(value as typeof state);setSelected(null);}} options={[{value:'all',label:'All states'},{value:'planning',label:'Planning'},{value:'finalized',label:'Finalized'},{value:'archived',label:'Archived'}]}/></section>
  {canWrite(roles)&&<RouteEditor source={source} confirmed={page.reload}/>}
  {page.phase==='loading'?<Loading label="Loading routes…"/>:page.phase==='error'?<Failure label="Routes could not be loaded." retry={page.reload}/>:page.phase==='empty'?<Empty icon="alt_route" title="No routes on this page" body="Create a planning route or choose another server state."/>:<section className="card ops-card"><ul className="ops-list">{page.items.map(route=><li className="ops-row" key={route.id}><span className="ops-row-main"><b>{route.origin} → {route.destination}</b><span>{route.mode} · {formatKolkata(route.scheduled_departure_at)}</span><span className="ops-note">{route.state} · version {route.version}</span></span><button className="btn btn-text" onClick={()=>setSelected(route.id)}>Open</button></li>)}</ul>{page.page.has_more&&<button className="btn btn-outlined" disabled={page.phase==='more'} onClick={page.loadMore}>Load next page</button>}</section>}
  {selected&&<RouteDetail key={selected} routeId={selected} source={source} roles={roles} close={()=>setSelected(null)} listReload={page.reload}/>}
 </div>;
}

function RouteEditor({source,confirmed}:{source:ReturnType<typeof routes>;confirmed:()=>void}){
 const [origin,setOrigin]=useState(''),[destination,setDestination]=useState(''),[mode,setMode]=useState<RouteDto['mode']>('road'),[carrier,setCarrier]=useState(''),[departure,setDeparture]=useState('');const command=useCommand<RouteDto|RouteEventResult>(value=>source.execute(value));const instant=localInputToInstant(departure);
 async function submit(event:React.FormEvent){event.preventDefault();if(!instant)return;try{await command.run(source.intent({kind:'create',body:{origin:origin.trim(),destination:destination.trim(),mode,carrier_code:carrier.trim()||null,scheduled_departure_at:instant}}));setOrigin('');setDestination('');setCarrier('');setDeparture('');confirmed();}catch{/* notice */}}
 return <section className="card ops-card"><h2 className="t-title-lg">Create planning route</h2><form className="ops-form" onSubmit={event=>{void submit(event);}}><div className="ops-form-grid"><TextField label="Origin" value={origin} onChange={setOrigin}/><TextField label="Destination" value={destination} onChange={setDestination}/><SelectField label="Mode" value={mode} onChange={value=>setMode(value as RouteDto['mode'])} options={modeOptions}/><TextField label="Carrier code (optional)" value={carrier} onChange={value=>setCarrier(value.toUpperCase())}/><TextField label="Scheduled departure (local)" type="datetime-local" value={departure} onChange={setDeparture}/></div><button className="btn btn-filled" disabled={!origin.trim()||!destination.trim()||!instant||command.phase==='pending'}>Create route</button></form><CommandNotice phase={command.phase} code={command.error?.code} retry={command.canRetry?()=>{void command.retry().then(confirmed).catch(()=>{});}:undefined}/></section>;
}

function RouteDetail({routeId,source,roles,close,listReload}:{routeId:string;source:ReturnType<typeof routes>;roles:readonly OperatorRole[];close:()=>void;listReload:()=>void}){
 const detail=useResource(routeId,signal=>source.read(routeId,signal));const manifest=useResource(routeId+'-manifest',signal=>source.manifest(routeId,undefined,{limit:100},signal));const latest=useResource(routeId+'-events',signal=>source.latest(routeId,signal));const command=useCommand<RouteDto|RouteEventResult>(value=>source.execute(value));
 const [sourceKind,setSourceKind]=useState<'lot'|'parcel'>('lot'),[sourceId,setSourceId]=useState(''),[historicalId,setHistoricalId]=useState(''),[historical,setHistorical]=useState<Awaited<ReturnType<typeof source.manifest>>|null>(null),[historyError,setHistoryError]=useState(false);
 if(detail.phase==='loading')return <Loading label="Loading route detail…"/>;if(detail.phase==='error')return <Failure label="Route detail is unavailable." retry={detail.reload}/>;const route=detail.value!,write=canWrite(roles)&&route.state==='planning';
 const refresh=()=>{detail.reload();manifest.reload();latest.reload();listReload();};async function run(intent:Parameters<typeof command.run>[0]){try{await command.run(intent);setSourceId('');refresh();}catch{/* notice */}}
 async function inspect(event:React.FormEvent){event.preventDefault();setHistoryError(false);try{setHistorical(await source.manifest(route.id,historicalId,{limit:100}));}catch{setHistorical(null);setHistoryError(true);}}
 return <section className="card ops-card ops-detail"><div className="u-between"><div><h2 className="t-headline-sm">{route.origin} → {route.destination}</h2><span className="ops-pill">{route.state}</span></div><button className="btn btn-text" onClick={close}>Close detail</button></div><div className="ops-facts"><Fact label="Version" value={route.version}/><Fact label="Mode" value={route.mode}/><Fact label="Scheduled" value={formatKolkata(route.scheduled_departure_at)}/><Fact label="Current manifest" value={route.current_manifest_id}/></div>
  {write&&<RoutePlanning route={route} source={source} command={command} run={run} sourceKind={sourceKind} setSourceKind={setSourceKind} sourceId={sourceId} setSourceId={setSourceId} roles={roles}/>}<CommandNotice phase={command.phase} code={command.error?.code} retry={command.canRetry?()=>{void command.retry().then(refresh).catch(()=>{});}:undefined}/>
  <section><h3>Current manifest</h3>{manifest.phase==='loading'?<p role="status">Loading manifest…</p>:manifest.phase==='error'?<button className="btn btn-outlined" onClick={manifest.reload}>Retry manifest</button>:<Manifest data={manifest.value!} writable={write} busy={command.phase==='pending'} detach={(parcelId,lotId)=>{void run(source.intent(lotId?{kind:'detach_lot',routeId:route.id,lotId,body:{expected_version:route.version}}:{kind:'detach_parcel',routeId:route.id,parcelId,body:{expected_version:route.version}}));}}/>}</section>
  <RouteEventForm route={route} manifest={manifest.value?.manifest??null} roles={roles} source={source} command={command} confirmed={refresh}/>
  <section><h3>Latest route event and ETA</h3>{latest.phase==='loading'?<p role="status">Loading latest event…</p>:latest.phase==='error'?<button className="btn btn-outlined" onClick={latest.reload}>Retry event read</button>:!latest.value!.latest?<p role="status">No route events recorded.</p>:<div className="ops-facts"><Fact label="Event" value={latest.value!.latest!.kind}/><Fact label="Effective" value={formatKolkata(latest.value!.latest!.effective_at)}/><Fact label="ETA state" value={latest.value!.latest!.eta.state}/><Fact label="Server revised ETA" value={latest.value!.latest!.eta.revised_at?formatKolkata(latest.value!.latest!.eta.revised_at):'Unavailable'}/><Fact label="Absolute delay" value={`${latest.value!.latest!.eta.total_delay_minutes} min`}/></div>}</section>
  <form className="ops-form" onSubmit={event=>{void inspect(event);}}><h3>Inspect retained manifest</h3><div className="ops-form-grid"><TextField label="Historical manifest ID (UUID)" value={historicalId} onChange={setHistoricalId}/><button className="btn btn-outlined" disabled={!uuid.test(historicalId)}>Load snapshot</button></div>{historyError&&<p role="alert">The snapshot could not be loaded for this route and scope.</p>}</form>{historical&&<Manifest data={historical} writable={false} busy={false} detach={()=>{}}/>}
 </section>;
}

function RoutePlanning({route,source,command,run,sourceKind,setSourceKind,sourceId,setSourceId,roles}:{route:RouteDto;source:ReturnType<typeof routes>;command:ReturnType<typeof useCommand<RouteDto|RouteEventResult>>;run:(intent:Parameters<typeof command.run>[0])=>Promise<void>;sourceKind:'lot'|'parcel';setSourceKind:(value:'lot'|'parcel')=>void;sourceId:string;setSourceId:(value:string)=>void;roles:readonly OperatorRole[]}){
 const [origin,setOrigin]=useState(route.origin),[destination,setDestination]=useState(route.destination),[mode,setMode]=useState(route.mode),[carrier,setCarrier]=useState(route.carrier_code??''),[departure,setDeparture]=useState(route.scheduled_departure_at.slice(0,16));const instant=localInputToInstant(departure);
 return <section><h3>Planning controls</h3><form className="ops-form" onSubmit={event=>{event.preventDefault();if(instant)void run(source.intent({kind:'update',routeId:route.id,body:{expected_version:route.version,origin,destination,mode,carrier_code:carrier||null,scheduled_departure_at:instant}}));}}><div className="ops-form-grid"><TextField label="Origin" value={origin} onChange={setOrigin}/><TextField label="Destination" value={destination} onChange={setDestination}/><SelectField label="Mode" value={mode} onChange={value=>setMode(value as RouteDto['mode'])} options={modeOptions}/><TextField label="Carrier code" value={carrier} onChange={value=>setCarrier(value.toUpperCase())}/><TextField label="Scheduled departure" type="datetime-local" value={departure} onChange={setDeparture}/></div><button className="btn btn-outlined" disabled={!instant||command.phase==='pending'}>Save metadata</button></form><form className="ops-form" onSubmit={event=>{event.preventDefault();void run(source.intent(sourceKind==='lot'?{kind:'attach_lot',routeId:route.id,body:{expected_version:route.version,lot_id:sourceId}}:{kind:'attach_parcel',routeId:route.id,body:{expected_version:route.version,parcel_id:sourceId}}));}}><div className="ops-form-grid"><SelectField label="Manifest source" value={sourceKind} onChange={value=>setSourceKind(value as typeof sourceKind)} options={[{value:'lot',label:'Lot snapshot'},{value:'parcel',label:'Direct parcel'}]}/><TextField label={`${sourceKind==='lot'?'Lot':'Parcel'} ID (UUID)`} value={sourceId} onChange={setSourceId}/></div><button className="btn btn-filled" disabled={!uuid.test(sourceId)||command.phase==='pending'}>Attach source</button></form><div className="ops-actions"><button className="btn btn-filled" disabled={command.phase==='pending'} onClick={()=>{void run(source.intent({kind:'finalize',routeId:route.id,body:{expected_version:route.version}}));}}>Finalize manifest</button>{roles.includes('franchise_admin')&&<button className="btn btn-text" disabled={command.phase==='pending'} onClick={()=>{void run(source.intent({kind:'archive',routeId:route.id,body:{expected_version:route.version}}));}}>Archive planning route</button>}</div></section>;
}

function Manifest({data,writable,busy,detach}:{data:Awaited<ReturnType<ReturnType<typeof routes>['manifest']>>;writable:boolean;busy:boolean;detach:(parcelId:string,lotId?:string)=>void}){return <div><p className="ops-note">Manifest {data.manifest.id} · version {data.manifest.version} · {data.manifest.finalized?'frozen':'planning'} · {data.manifest.parcel_count} parcels</p>{data.items.length===0?<p role="status">No manifest parcels.</p>:<ul className="ops-list">{data.items.map(item=><li className="ops-row" key={item.parcel_id}><span className="ops-row-main"><b className="ops-mono">{item.parcel_id}</b><span className="ops-note">{item.sources.map(source=>source.kind==='lot'?`lot ${source.lot_id} / membership ${source.lot_membership_id}`:'direct parcel').join(' · ')}</span></span>{writable&&<span className="ops-row-actions">{item.sources.map(source=><button key={source.source_id} className="btn btn-text" disabled={busy} onClick={()=>detach(item.parcel_id,source.kind==='lot'?source.lot_id:undefined)}>Detach {source.kind}</button>)}</span>}</li>)}</ul>}{data.page.has_more&&<p className="ops-note">More manifest items exist. Narrow operational decisions to loaded evidence or use the next cursor through the API.</p>}</div>}

function RouteEventForm({route,manifest,roles,source,command,confirmed}:{route:RouteDto;manifest:{id:string;version:number;finalized:boolean}|null;roles:readonly OperatorRole[];source:ReturnType<typeof routes>;command:ReturnType<typeof useCommand<RouteDto|RouteEventResult>>;confirmed:()=>void}){
 const [kind,setKind]=useState<RouteEventInput['kind']>(roles.includes('dispatcher')?'departure':'delay'),[effective,setEffective]=useState(''),[evidence,setEvidence]=useState(''),[eta,setEta]=useState(''),[delay,setDelay]=useState('0');const effectiveAt=localInputToInstant(effective),etaAt=localInputToInstant(eta);
 if(route.state!=='finalized'||!manifest?.finalized||!roles.some(role=>['franchise_admin','operator','dispatcher'].includes(role)))return null;
 const exactManifest=manifest;
 const options=(roles.includes('dispatcher')?['departure','delay','arrival']:['delay','arrival']).map(value=>({value,label:value}));
 async function submit(event:React.FormEvent){event.preventDefault();if(!effectiveAt)return;const base={kind,expected_version:route.version,manifest_id:exactManifest.id,manifest_version:exactManifest.version,effective_at:effectiveAt,evidence_ref:evidence};let body:RouteEventInput=base;if(kind==='departure')body={...base,base_eta_at:etaAt};else if(kind==='delay')body={...base,total_delay_minutes:Number(delay)};try{await command.run(source.intent({kind:'event',routeId:route.id,body}));confirmed();setEvidence('');setEffective('');}catch{/* notice */}}
 return <section><h3>Record route event</h3><p className="ops-note">Delay is the new absolute total, not an increment. Server time ordering and the exact finalized manifest are authoritative.</p><form className="ops-form" onSubmit={event=>{void submit(event);}}><div className="ops-form-grid"><SelectField label="Event" value={kind} onChange={value=>setKind(value as RouteEventInput['kind'])} options={options}/><TextField label="Effective time (local)" type="datetime-local" value={effective} onChange={setEffective}/><TextField label="Evidence reference (UUID)" value={evidence} onChange={setEvidence}/>{kind==='departure'&&<TextField label="Base route-leg ETA (local, optional)" type="datetime-local" value={eta} onChange={setEta}/>} {kind==='delay'&&<TextField label="Absolute total delay (minutes)" type="number" min="0" max="43200" value={delay} onChange={setDelay}/>}</div><button className="btn btn-filled" disabled={command.phase==='pending'||!effectiveAt||!uuid.test(evidence)||(kind==='departure'&&Boolean(eta)&&!etaAt)||(kind==='delay'&&(!Number.isSafeInteger(Number(delay))||Number(delay)<0||Number(delay)>43200))}>Record {kind}</button></form></section>;
}
function Fact({label,value}:{label:string;value:React.ReactNode}){return <div className="ops-fact"><span className="ops-note">{label}</span><b>{value}</b></div>}
