import React from 'react';
import {afterEach,describe,it,expect,vi} from 'vitest';
import {act,cleanup,fireEvent,render,screen} from '@testing-library/react';
import {MemoryRouter} from 'react-router-dom';
import type {CashbookRequestDto,OperatorRole} from '@shippingco/shared';
import Cashbook from '../operations/Cashbook';
import {cashbook,cashbookDetail,cashbookPosition,cashbookReportPage,cashHandoverDetail} from '../data-access/cashbook';
import {createScopeController} from '../operator/scope';
import {scopedApi} from '../data-access/scoped-api';
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const org=id(1),franchise=id(2),user=id(3),requestId=id(4),now='2026-10-01T12:00:00.000Z';
const location={id:id(10),revision_id:id(11),version:1,name:'Synthetic till',active:true,kind:'cash',account_id:id(12),account_revision_id:id(13),account_version:1,methods:['cash'],custodian_id:user,recorded_at:now};
const original:CashbookRequestDto={id:requestId,actor_id:user,recorded_at:now,payment_method:'cash',kind:'expense',source_location_id:location.id,source_revision_id:location.revision_id,target_location_id:null,target_revision_id:null,expected_source_version:9,amount_paise:50000,currency:'INR',category:'supplies',payee:'Synthetic payee',responsible_employee_id:user,reason:'Synthetic expense',occurred_at:now};
const review={id:id(20),request_id:requestId,decision:'approved',reason:'Reviewed proof',actor_id:id(9),recorded_at:now,version:2,attachments:[]};
const effect={id:id(21),request_id:requestId,decision_id:review.id,actor_id:user,recorded_at:now,version:3,legs:[{location_id:location.id,direction:'out',amount_paise:'50000'}]};
const position={as_of:now,source_version:9,unknown_sources:0,locations:[{location_id:location.id,known_inflows_paise:'500000',known_outflows_paise:'50000',known_recorded_paise:'450000',available_paise:'440000',pending_reserved_paise:'10000',shortfall_paise:'0',unknown_sources:0,state:'recorded'}]};
const handoverRequest={id:id(30),actor_id:id(8),recorded_at:now,version:1,source_location_id:id(14),source_revision_id:id(15),target_location_id:location.id,target_revision_id:location.revision_id,expected_source_version:9,amount_paise:20000,currency:'INR',reason:'Cash custody',occurred_at:now};
const handover={request:handoverRequest,version:1,accepted_paise:0,remaining_paise:20000,ended_paise:0,state:'requested',current_source_version:9,commands:[],next_cursor:null};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});
function fixture(actor=user){let request={...original,actor_id:actor},decision:typeof review|null=null,applied:typeof effect|null=null,h=structuredClone(handover),lose=false,lost=false;const writes:{path:string;body:Record<string,unknown>;key:string}[]=[];
 const fetcher=vi.fn(async(path:string,options:RequestInit={})=>{const url=new URL(path,'https://fictional.example.test');if(url.pathname==='/auth/bootstrap')return json({csrf_token:'synthetic_csrf'});
 if(options.method==='POST'){const body=JSON.parse(String(options.body)),key=(options.headers as Record<string,string>)['Idempotency-Key'];writes.push({path:url.pathname,body,key});let result:unknown;
 if(url.pathname.endsWith('/cashbook/requests')){request={...original,...body};result=request;}
 else if(url.pathname.endsWith('/decisions')){decision={...review,actor_id:user};result=decision;}
 else if(url.pathname.endsWith('/apply')){applied=effect;result=effect;}
 else if(url.pathname.endsWith('/commands')){const amount=Number(body.amount_paise),c={id:id(31),handover_id:h.request.id,version:2,kind:'accept',amount_paise:amount,currency:'INR',reason:body.reason,actor_id:user,recorded_at:now,accepted_paise:amount,remaining_paise:20000-amount,ended_paise:0,state:'partially_accepted',legs:[{location_id:id(14),direction:'out',amount_paise:String(amount)},{location_id:location.id,direction:'in',amount_paise:String(amount)}]};h={...h,...c,commands:[c]} as unknown as typeof h;result=c;}
 else throw new Error('Unexpected mutation path');if(lose&&!lost){lost=true;throw new TypeError('Synthetic lost response after save');}return json(result);}
 if(url.pathname.endsWith('/cashbook/locations'))return json({items:[location],next_cursor:null});
 if(url.pathname.endsWith('/money-receipt-receivers'))return json({items:[{id:user,label:'Synthetic operator'}],next_cursor:null});
 if(url.pathname.endsWith('/cashbook/handovers'))return json({items:[{...h.request,...h,request:undefined,commands:undefined,next_cursor:undefined}],next_cursor:null,current_source_version:9});
 if(url.pathname.includes('/cashbook/handovers/'))return json(h);
 if(url.pathname.endsWith('/cashbook/requests'))return json({as_of:now,items:[{...request,payment_method:request.payment_method??null,correction_of:request.correction_of??null,corrected_by:null,state:applied?'applied':decision?.decision??'requested',version:applied?3:decision?2:1}],next_cursor:null,current_source_version:9});
 if(url.pathname.includes('/cashbook/requests/'))return json({request,decision,effect:applied,version:applied?3:decision?2:1,private_extra:'DO_NOT_RENDER'});
 if(url.pathname.includes('/cashbook/locations/'))return json(location);
 throw new Error('Unexpected read path');});vi.stubGlobal('fetch',fetcher);return {writes,fetcher,lose(){lose=true;},applied(amount:number){request.amount_paise=amount;decision=review;applied=effect;}};
}
function controller(){const c=createScopeController();c.runtime.bind({userId:user,organizationId:org,franchiseId:franchise,permissions:'operator'});return c;}
function view(roles:OperatorRole[]){const c=controller();render(<MemoryRouter><a href="/business">Workspace link</a><select aria-label="Franchise"><option value={franchise}>First</option><option value={id(50)}>Second</option></select><Cashbook controller={c} roles={roles}/></MemoryRouter>);return c;}
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
describe('cashbook protocol integrity',()=>{
 it('rejects mismatched approvals, self approval and application linked to rejected evidence',()=>{expect(cashbookDetail({request:original,decision:review,effect,version:3})).toMatchObject({version:3});for(const decision of [{...review,request_id:id(99)},{...review,actor_id:user},{...review,decision:'rejected'}])expect(()=>cashbookDetail({request:original,decision,effect,version:3})).toThrow();expect(()=>cashbookDetail({request:original,decision:review,effect:{...effect,decision_id:id(99)},version:3})).toThrow();});
 it('checks integer position conservation, reservations and uncertainty without converting totals to floats',()=>{expect(cashbookPosition(position)).toEqual(position);expect(()=>cashbookPosition({...position,locations:[{...position.locations[0],available_paise:'440001'}]})).toThrow();expect(()=>cashbookPosition({...position,locations:[{...position.locations[0],known_recorded_paise:'449999'}]})).toThrow();expect(cashbookPosition({...position,locations:[{...position.locations[0],known_inflows_paise:'0',known_outflows_paise:'100',known_recorded_paise:'-100',pending_reserved_paise:'0',shortfall_paise:'100',available_paise:'0',state:'exception'}]})).toBeDefined();});
 it('requires paired acceptance legs and conserves the whole handover even when history is paged',()=>{expect(cashHandoverDetail(handover)).toEqual(handover);expect(()=>cashHandoverDetail({...handover,remaining_paise:19999})).toThrow();const c={id:id(31),handover_id:id(30),version:2,kind:'accept',amount_paise:10000,currency:'INR',reason:'Received',actor_id:user,recorded_at:now,accepted_paise:10000,remaining_paise:10000,ended_paise:0,state:'partially_accepted',legs:[{location_id:id(14),direction:'out',amount_paise:'10000'},{location_id:location.id,direction:'in',amount_paise:'9999'}]};expect(()=>cashHandoverDetail({...handover,version:2,accepted_paise:10000,remaining_paise:10000,state:'partially_accepted',commands:[c]})).toThrow();});
 it('rejects source totals and cutoff mismatches and strips private extra report fields',()=>{const row={id:`expense:${requestId}:${location.id}`,source_kind:'expense',source_id:requestId,payment_method:'cash',location_id:location.id,account_id:location.account_id,direction:'out',amount_paise:'50000',occurred_at:now,recorded_at:now,actor_id:user,request_id:requestId,correction_of:null,unknown_reason:null,private_payee:'DO_NOT_RENDER'};const snapshot={id:id(40),schema_version:1,definition:'cashbook_sources_v1',organization_id:org,franchise_id:franchise,timezone:'Asia/Kolkata',filter:{from_day:'2026-10-01',to_day:'2026-10-01',sort:'occurred_asc',payment_method:null,kind:null,location_id:null},as_of:now,expires_at:'2026-10-02T12:00:00.000Z',count:1,totals:{count:1,known_inflows_paise:'0',known_outflows_paise:'50000',known_net_paise:'-50000',unknown_inflows_paise:'0',unknown_outflows_paise:'0',unknown_sources:0},position};const page={snapshot,rows:[row],next_offset:null};expect(JSON.stringify(cashbookReportPage(page))).not.toContain('DO_NOT_RENDER');expect(()=>cashbookReportPage({...page,snapshot:{...snapshot,totals:{...snapshot.totals,known_outflows_paise:'49999',known_net_paise:'-49999'}}})).toThrow();expect(()=>cashbookReportPage({...page,snapshot:{...snapshot,as_of:'2026-10-01T12:01:00.000Z'}})).toThrow();});
 it('rejects wrong returned request intent and clears stale scope before transport',async()=>{fixture();const c=controller(),source=cashbook(scopedApi(c)),intent=source.submit({...original,amount_paise:50000});const old=globalThis.fetch;vi.stubGlobal('fetch',vi.fn(async(path:string,options:RequestInit={})=>path.endsWith('/auth/bootstrap')?json({csrf_token:'synthetic_csrf'}):options.method==='POST'?json({...original,amount_paise:49999}):old(path,options)));await expect(source.executeRequest(intent)).rejects.toMatchObject({kind:'protocol'});act(()=>c.clear('signed_out'));const calls=vi.mocked(fetch).mock.calls.length;await expect(source.executeRequest(intent)).rejects.toMatchObject({code:'SCOPE_CHANGED'});expect(vi.mocked(fetch).mock.calls).toHaveLength(calls);});
});
describe('cashbook production UI with scoped adapters and controlled transport',()=>{
 it('retains the exact uncertain expense and blocks navigation until same-key replay',async()=>{const f=fixture();f.lose();const c=view(['operator']);await screen.findByRole('form',{name:'Cashbook request'});await screen.findByRole('option',{name:'Synthetic operator'});fireEvent.change(screen.getByLabelText('Source cash location'),{target:{value:location.id}});fireEvent.change(screen.getByLabelText('Amount (₹)'),{target:{value:'500.01'}});fireEvent.change(screen.getByLabelText('Private payee'),{target:{value:'Synthetic payee'}});fireEvent.change(screen.getByLabelText('Responsible employee'),{target:{value:user}});fireEvent.change(screen.getByLabelText('Occurred at (Kolkata)'),{target:{value:'2026-10-01T17:30'}});fireEvent.change(screen.getByLabelText('Reason'),{target:{value:'Synthetic expense'}});fireEvent.submit(screen.getByRole('form',{name:'Cashbook request'}));await screen.findByText(/The outcome is uncertain/);expect(screen.getByLabelText('Amount (₹)')).toBeDisabled();expect(fireEvent.click(screen.getByText('Workspace link'))).toBe(false);fireEvent.change(screen.getByLabelText('Franchise'),{target:{value:id(50)}});expect(screen.getByLabelText('Franchise')).toHaveValue(franchise);fireEvent.click(screen.getByRole('button',{name:'Retry same request'}));await screen.findByRole('heading',{name:'Saved request'});expect(f.writes).toHaveLength(2);expect(f.writes[1]).toEqual(f.writes[0]);expect(f.writes[0]!.body).toMatchObject({expected_source_version:9,amount_paise:50001,payment_method:'cash',occurred_at:now});expect(screen.queryByText('DO_NOT_RENDER')).not.toBeInTheDocument();act(()=>c.clear('signed_out'));expect(screen.queryByText('Synthetic payee')).not.toBeInTheDocument();});
 it('requires another admin to review and applies the original request instead of the returned decision id',async()=>{const f=fixture(id(8));view(['franchise_admin']);fireEvent.click(await screen.findByRole('button',{name:/expense · .*requested/}));await screen.findByRole('button',{name:'Record review'});fireEvent.change(screen.getByLabelText('Review reason'),{target:{value:'Reviewed proof'}});fireEvent.click(screen.getByRole('button',{name:'Record review'}));fireEvent.click(await screen.findByRole('button',{name:'Apply exact approved request'}));await screen.findByRole('button',{name:'Request recording correction'});expect(f.writes.map(w=>w.path)).toEqual(['/api/v1/cashbook/requests/'+requestId+'/decisions','/api/v1/cashbook/requests/'+requestId+'/apply']);expect(f.writes[1]!.body).toEqual({decision_id:review.id,expected_version:2});cleanup();fixture();view(['franchise_admin']);fireEvent.click(await screen.findByRole('button',{name:/expense · .*requested/}));await screen.findByText('A different franchise admin must review your request.');expect(screen.queryByRole('button',{name:'Record review'})).not.toBeInTheDocument();});
 it('allows the current receiving custodian to accept part of the reservation with captured versions',async()=>{const f=fixture();view(['operator']);fireEvent.click(screen.getByRole('button',{name:'Cash custody'}));fireEvent.click(await screen.findByRole('button',{name:/requested · remaining/}));await screen.findByRole('form',{name:'Acknowledge cash handover'});fireEvent.change(screen.getByLabelText('Actually received cash (₹)'),{target:{value:'100'}});fireEvent.change(screen.getByLabelText('Custody response reason'),{target:{value:'Actually received'}});fireEvent.submit(screen.getByRole('form',{name:'Acknowledge cash handover'}));await screen.findByText(/00000000-0000-4000-8000-000000000030 · partially accepted/);expect(f.writes[0]!.body).toEqual({kind:'accept',amount_paise:10000,reason:'Actually received',expected_version:1,expected_source_version:9,currency:'INR'});});
 it('keeps every paise in a recording correction and retains the original occurrence evidence',async()=>{const f=fixture();f.applied(999999999999999);view(['franchise_admin']);fireEvent.click(await screen.findByRole('button',{name:/expense · .*applied/}));fireEvent.click(await screen.findByRole('button',{name:'Request recording correction'}));expect(screen.getByLabelText('Replacement recorded amount (₹; zero annuls)')).toHaveValue('9999999999999.99');expect(screen.getByLabelText('Occurred at (Kolkata)')).toBeDisabled();fireEvent.change(screen.getByLabelText('Replacement recorded amount (₹; zero annuls)'),{target:{value:'0'}});fireEvent.change(screen.getByLabelText('Reason'),{target:{value:'Correct mistaken recorded expense'}});fireEvent.submit(screen.getByRole('form',{name:'Cashbook request'}));await screen.findByText('Recording correction of '+requestId+'. Original evidence remains unchanged.');expect(f.writes[0]!.body).toMatchObject({correction_of:requestId,amount_paise:0,occurred_at:now,source_location_id:location.id,expected_source_version:9});});
 it('keeps finance readers free of expense and custody mutation forms',async()=>{for(const role of ['org_admin','accountant'] as OperatorRole[]){fixture();view([role]);await screen.findByRole('button',{name:/expense · .*requested/});expect(screen.queryByRole('form',{name:'Cashbook request'})).not.toBeInTheDocument();expect(screen.queryByRole('form',{name:'Request cash handover'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Record review'})).not.toBeInTheDocument();cleanup();}});
});
