// Fictional public DTOs only. Never imported by a production entry point.
export const id = (n: number) => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
export const org=id(1), A=id(2), B=id(3), customerId=id(4), bookingId=id(5), now='2099-01-01T00:00:00.000Z', expiry='2099-01-01T01:00:00.000Z';
export const context={user_id:id(6),state:'ready',active_franchise_id:A,franchises:[A,B].map((f,i)=>({id:f,display_name:`Counter ${i?'B':'A'}`,organization:{id:org,display_name:'Synthetic Courier'},roles:['operator','franchise_admin']}))};
export const customer={id:customerId,name:'Synthetic Sender',phone:'+12025550100',phone_display:'+1 202-555-0100',address:'19 Synthetic Lane',version:1,created_at:now,updated_at:now};
export const quote={id:id(7),proposal:true,rate_version_id:id(8),rate_version_number:1,rule_id:id(9),freight_suggestion_paise:12551,freight_paise:12551,packing_paise:249,variance_paise:0,subtotal_paise:12800,override_status:'none',expires_at:expiry};
export const intent={id:id(10),quote_id:quote.id,fingerprint:'synthetic',created_at:now,expires_at:expiry,jurisdiction_status:'known'};
export const evidence={policy_id:id(11),policy_version:1,rule_id:'SYN_RULE',classification:'SYN_CLASS',treatment:'taxable',supplier_state:'27',place_of_supply:'27',jurisdiction:'intra',pre_tax_paise:12800,taxable_basis_paise:12800,cgst_paise:320,sgst_paise:320,igst_paise:0,tax_total_paise:640,unrounded_payable_paise:13440,rounding_adjustment_paise:-40,final_payable_paise:13400,allocation:'largest_remainder_v1',components:[{id:'C',kind:'CGST',numerator:1,denominator:40,exact_numerator:'12800',exact_denominator:'40',amount_paise:320},{id:'S',kind:'SGST',numerator:1,denominator:40,exact_numerator:'12800',exact_denominator:'40',amount_paise:320}]};
export const tax={...evidence,id:id(12),proposal:true,intent_id:intent.id,quote_id:quote.id,resolution_id:null,registration:'unregistered',approval_ref:'SYN_APPROVAL',source_ref:'SYN_SOURCE',rule_evidence_ref:'SYN_RULE',time_rule:'contemporaneous_v1',proposed_tax_point_at:now,created_at:now,expires_at:expiry,fingerprint:'synthetic'};
export const booking={id:bookingId,version:1,state:'active',organization_id:org,franchise_id:A,customer:{source_customer_id:customerId,source_customer_version:1,name:customer.name},charges:{confirmed_at:now,tax:evidence},payment_obligation:{id:id(13),currency:'INR',total_paise:13400,collected_paise:0,outstanding_paise:13400,state:'uncollected'},parcels:[{id:id(14),docket:'SYN-33',weight_grams:999,status:'booked'}]};
export const receipt={id:id(15),number:'RCT-0000000000000000033',schema_version:1,version:1,booking_id:bookingId,issued_at:now,currency:'INR',kind:'booking_charge',booking_receipt_id:null,correction_of:null,issuer:{organization_name:'Synthetic Courier',franchise_name:'Original Counter',franchise_code:'SYN',supplier_gstin:'27ABCDE1234F1Z5',supplier_state:'27'},booking:{customer_name:customer.name,confirmed_at:now,service:'standard',parcels:[{docket:'SYN-33',weight_grams:999}]},charges:{freight_paise:12551,packing_paise:249,tax:evidence}};
export const balance={booking_id:bookingId,obligation_id:id(13),currency:'INR',gross_paise:13400,collected_paise:13400,outstanding_paise:0,state:'settled',version:1};
export const json=(v:unknown,status=200)=>new Response(JSON.stringify(v),{status,headers:{'Content-Type':'application/json'}});
export function deferred<T>() { let resolve!:(v:T)=>void; const promise=new Promise<T>(r=>{resolve=r;});return {promise,resolve}; }
