import {afterEach,describe,expect,it,vi} from 'vitest';
import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import type {ExpenseAttachmentDto,ExpenseAttachmentIntent} from '@shippingco/shared';
import {createExpenseAttachmentClient,createAttachmentClient,expenseAttachmentMetadata,attachmentMetadata,type ExpenseAttachmentClient} from '../data-access/attachments';
import {ExpenseAttachmentUploader} from '../components/m3/AttachmentUploader';
import {createScopeRuntime} from '../data-access/scope-runtime';
import {ApiFailure} from '../data-access/errors';
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,org=id(1),franchise=id(2),user=id(3),requestId=id(4),fileId=id(5),now='2026-10-01T12:00:00.000Z';
const dto:ExpenseAttachmentDto={id:fileId,expense_request_id:requestId,purpose:'expense_evidence',kind:'audio',filename:'voice-note.wav',size_bytes:4,media_type:'audio/wav',state:'ready',scan_state:'clean',retention_class:'operational_evidence',version:4,created_at:now,upload_expires_at:'2026-10-02T12:00:00.000Z',linked_at:now};
const pending={...dto,state:'pending_upload',scan_state:'pending',linked_at:null} as ExpenseAttachmentDto;
const intent:ExpenseAttachmentIntent={purpose:'expense_evidence',kind:'audio',media_type:'audio/wav',size_bytes:4,sha256:'a'.repeat(64)};
function runtime(){const r=createScopeRuntime();r.bind({userId:user,organizationId:org,franchiseId:franchise,permissions:'operator'});return r;}
function setup(){const r=runtime(),client={list:vi.fn().mockResolvedValue([]),initiate:vi.fn().mockResolvedValue(pending),upload:vi.fn().mockResolvedValue({...pending,state:'quarantined'}),finalize:vi.fn().mockResolvedValue(dto),cancel:vi.fn().mockResolvedValue({...pending,state:'canceled'}),bytes:vi.fn().mockResolvedValue(new Blob(['test'],{type:'audio/wav'}))} satisfies ExpenseAttachmentClient;
 const NativeURL=URL;class TestURL extends NativeURL{static override createObjectURL=vi.fn(()=> 'blob:synthetic-proof');static override revokeObjectURL=vi.fn();}vi.stubGlobal('URL',TestURL);let next=100;vi.stubGlobal('crypto',{randomUUID:()=>id(next++),subtle:{digest:async()=>new Uint8Array(32).buffer}});const file=new File(['test'],'PRIVATE_PAYEE_SECRET.wav',{type:'audio/wav'});Object.defineProperty(file,'arrayBuffer',{value:async()=>new Uint8Array([1,2,3,4]).buffer});return {r,client,file};}
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();});
describe('expense attachment parent and byte boundaries',()=>{
 it('rejects booking evidence and parent fields while projecting only expense metadata',()=>{expect(expenseAttachmentMetadata({...dto,url:'https://private.invalid',object_key:'PRIVATE_PAYEE_SECRET'})).toEqual(dto);expect(()=>expenseAttachmentMetadata({...dto,booking_id:requestId})).toThrow();expect(()=>expenseAttachmentMetadata({...dto,purpose:'parcel_proof'})).toThrow();expect(()=>attachmentMetadata(dto)).toThrow();expect(()=>expenseAttachmentMetadata({...dto,state:'ready',scan_state:'pending'})).toThrow();});
 it('uses only the expense parent route and rejects mismatched parent/command identities as uncertain',async()=>{const api={request:vi.fn().mockResolvedValue(dto)},r=runtime(),client=createExpenseAttachmentClient(r,requestId,api);await client.initiate(intent,id(10));expect(api.request.mock.calls[0]![0]).toBe(`/api/v1/cashbook/requests/${requestId}/attachments/uploads?organization_id=${org}&franchise_id=${franchise}`);api.request.mockResolvedValue({items:[{...dto,expense_request_id:id(99)}]});await expect(client.list()).rejects.toMatchObject({kind:'protocol'});api.request.mockResolvedValue({...dto,expense_request_id:id(99)});await expect(client.initiate(intent,id(11))).rejects.toMatchObject({kind:'protocol',dispatched:true});api.request.mockResolvedValue({...dto,id:id(99)});await expect(client.finalize(fileId,id(12))).rejects.toMatchObject({kind:'protocol',dispatched:true});expect(()=>client.initiate({...intent,parcel_id:id(9)} as ExpenseAttachmentIntent,id(13))).toThrow();const booking=createAttachmentClient(r,requestId,api);api.request.mockResolvedValue(dto);await expect(booking.initiate({...intent,purpose:'shipment_evidence'},id(14))).rejects.toMatchObject({kind:'protocol'});});
 it('rejects booking grant URLs and wrong-parent/foreign URLs before sending credentials',async()=>{const r=runtime(),prefix=`/api/v1/cashbook/requests/${requestId}/attachments/${fileId}/content?organization_id=${org}&franchise_id=${franchise}&grant=synthetic`,api={request:vi.fn()},fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);const client=createExpenseAttachmentClient(r,requestId,api);for(const url of [prefix.replace(`/cashbook/requests/${requestId}`,`/bookings/${requestId}`),prefix.replace(requestId,id(99)),'https://foreign.invalid'+prefix]){api.request.mockResolvedValue({url,expires_at:now});await expect(client.bytes(fileId,id(15))).rejects.toMatchObject({kind:'protocol'});}expect(fetcher).not.toHaveBeenCalled();});
 it('uses exact expense binary content path, current CSRF and parent-projected upload result',async()=>{const r=runtime(),api={request:vi.fn().mockResolvedValue({csrf_token:'synthetic_csrf'})},xhr={upload:{},open:vi.fn(),setRequestHeader:vi.fn(),send:vi.fn(),abort:vi.fn(),status:200,responseText:JSON.stringify({...pending,state:'quarantined'})} as unknown as XMLHttpRequest,client=createExpenseAttachmentClient(r,requestId,api,()=>xhr),file=new Blob(['test'],{type:'audio/wav'}),controller=new AbortController(),result=client.upload(fileId,file,()=>{},controller.signal);await waitFor(()=>expect(xhr.send).toHaveBeenCalled());expect(xhr.open).toHaveBeenCalledWith('PUT',`/api/v1/cashbook/requests/${requestId}/attachments/uploads/${fileId}/content?organization_id=${org}&franchise_id=${franchise}`);expect(xhr.withCredentials).toBe(true);expect(xhr.setRequestHeader).toHaveBeenCalledWith('X-CSRF-Token','synthetic_csrf');xhr.onload?.({} as ProgressEvent);expect(await result).toMatchObject({expense_request_id:requestId,state:'quarantined'});});
 it('aborts expense transport on scope change and refuses a new franchise rebind',async()=>{const r=runtime(),api={request:vi.fn()},client=createExpenseAttachmentClient(r,requestId,api);r.invalidate();r.bind({userId:user,organizationId:org,franchiseId:id(99),permissions:'operator'});await expect(client.list()).rejects.toMatchObject({code:'SCOPE_CHANGED'});expect(api.request).not.toHaveBeenCalled();});
 it('bounds bytes and rejects an empty response or a late response after current scope loss',async()=>{const r=runtime(),api={request:vi.fn().mockResolvedValue({url:`/api/v1/cashbook/requests/${requestId}/attachments/${fileId}/content?organization_id=${org}&franchise_id=${franchise}&grant=synthetic`,expires_at:now})},client=createExpenseAttachmentClient(r,requestId,api),fetcher=vi.fn().mockResolvedValue(new Response(new Uint8Array(0),{headers:{'content-type':'audio/wav'}}));vi.stubGlobal('fetch',fetcher);await expect(client.bytes(fileId,id(16))).rejects.toMatchObject({code:'ATTACHMENT_CONTENT_MISMATCH'});fetcher.mockResolvedValue(new Response(new Uint8Array(8388609),{headers:{'content-type':'audio/wav'}}));await expect(client.bytes(fileId,id(17))).rejects.toMatchObject({code:'ATTACHMENT_LIMIT_EXCEEDED'});let resolve!:(r:Response)=>void;fetcher.mockImplementation(()=>new Promise<Response>(r=>{resolve=r;}));const bytes=client.bytes(fileId,id(18));await waitFor(()=>expect(fetcher).toHaveBeenCalledTimes(3));r.invalidate();resolve(new Response('test',{headers:{'content-type':'audio/wav'}}));await expect(bytes).rejects.toMatchObject({code:'SCOPE_CHANGED'});});
});
describe('private expense proof UI lifecycle',()=>{
 it('retains uncertain initiation and cancellation identities until durable cleanup is confirmed',async()=>{const {r,client,file}=setup(),activity=vi.fn();client.initiate.mockRejectedValueOnce(new ApiFailure('TEMPORARILY_UNAVAILABLE',{kind:'network',dispatched:true}));client.cancel.mockRejectedValueOnce(new ApiFailure('TEMPORARILY_UNAVAILABLE',{kind:'network',dispatched:true}));render(<ExpenseAttachmentUploader client={client} runtime={r} canUpload canCancel locked={false} onActivity={activity}/>);await screen.findByText('Private files. Up to 8 MiB each.');fireEvent.change(screen.getByLabelText('Choose voice note'),{target:{files:[file]}});await screen.findByRole('button',{name:'Retry attachment'});expect(activity).toHaveBeenLastCalledWith(true);fireEvent.click(screen.getByRole('button',{name:'Cancel attachment upload'}));await screen.findByRole('button',{name:'Retry same attachment cancellation'});expect(client.initiate.mock.calls[1]).toEqual(client.initiate.mock.calls[0]);fireEvent.click(screen.getByRole('button',{name:'Retry same attachment cancellation'}));await screen.findByText('Upload canceled. Temporary bytes will be cleaned.');expect(client.cancel.mock.calls[1]).toEqual(client.cancel.mock.calls[0]);expect(activity).toHaveBeenLastCalledWith(false);expect(client.upload).not.toHaveBeenCalled();});
 it('reconciles ready evidence after an uncertain cancellation without replacing the original cancellation key',async()=>{const {r,client}=setup(),activity=vi.fn();client.list.mockResolvedValue([pending]);client.cancel.mockRejectedValue(new ApiFailure('TEMPORARILY_UNAVAILABLE',{kind:'network',dispatched:true}));render(<ExpenseAttachmentUploader client={client} runtime={r} canUpload canCancel locked={false} onActivity={activity}/>);await screen.findByRole('button',{name:'Cancel attachment upload'});fireEvent.click(screen.getByRole('button',{name:'Cancel attachment upload'}));await screen.findByRole('button',{name:'Retry same attachment cancellation'});client.list.mockResolvedValue([dto]);fireEvent.click(screen.getByRole('button',{name:'Refresh attachment evidence'}));await screen.findByText('Saved securely');expect(activity).toHaveBeenLastCalledWith(false);fireEvent.click(screen.getByRole('button',{name:'Preview attachment'}));await waitFor(()=>expect(document.querySelector('audio')).not.toBeNull());expect(client.cancel).toHaveBeenCalledTimes(1);});
 it('allows finance proof read without upload, retry or cancel and never locks review on another creator’s unsettled metadata',async()=>{const {r,client}=setup(),activity=vi.fn();client.list.mockResolvedValue([{...pending,id:id(6),state:'quarantined'},dto]);render(<ExpenseAttachmentUploader client={client} runtime={r} canUpload={false} canCancel={false} locked={false} onActivity={activity}/>);await screen.findByText('Saved securely');expect(screen.queryByRole('button',{name:'Photo'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Retry attachment'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Cancel attachment upload'})).not.toBeInTheDocument();expect(activity).not.toHaveBeenCalledWith(true);fireEvent.click(screen.getByRole('button',{name:'Preview attachment'}));await waitFor(()=>expect(document.querySelector('audio')).not.toBeNull());});
 it('freezes new evidence after review and purges previews on scope loss',async()=>{const {r,client,file}=setup(),view=render(<ExpenseAttachmentUploader client={client} runtime={r} canUpload canCancel locked={false}/>);await screen.findByText('Private files. Up to 8 MiB each.');fireEvent.change(screen.getByLabelText('Choose voice note'),{target:{files:[file]}});await screen.findByText('Saved securely');view.rerender(<ExpenseAttachmentUploader client={client} runtime={r} canUpload={false} canCancel={false} locked={false}/>);expect(screen.queryByRole('button',{name:'Photo'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Cancel attachment upload'})).not.toBeInTheDocument();expect(client.initiate.mock.calls[0]![0]).toMatchObject({purpose:'expense_evidence'});expect(client.initiate.mock.calls[0]![0]).not.toHaveProperty('parcel_id');expect(screen.queryByText(file.name)).not.toBeInTheDocument();act(()=>r.invalidate());expect(document.querySelector('audio')).toBeNull();expect(URL.revokeObjectURL).toHaveBeenCalled();});
});
