import React from 'react';
import { afterEach,describe,expect,it,vi } from 'vitest';
import { act,fireEvent,render,screen } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { createScopeController } from '../operator/scope';
import { scopedApi } from '../data-access/scoped-api';
import { parcels } from '../data-access/parcels';
import { lots } from '../data-access/lots';
import { routes } from '../data-access/routes';
import { eway } from '../data-access/eway';
import OperationsDashboard from '../operations/Dashboard';
import Packages from '../operations/Packages';
import Lots from '../operations/Lots';
import Routes from '../operations/Routes';
import Eway from '../operations/Eway';

const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const org=id(1),franchise=id(2),user=id(3),parcelId=id(4),bookingId=id(5),lotId=id(6),membershipId=id(7),routeId=id(8),manifestId=id(9),now='2099-01-01T00:00:00.000Z';
const page=(items:unknown[])=>({items,page:{has_more:false,next_cursor:null}});
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});
const controller=()=>{const value=createScopeController();value.runtime.bind({userId:user,organizationId:org,franchiseId:franchise,permissions:'operator'});return value;};
const parcel={id:parcelId,booking_id:bookingId,version:1,status:'booked',custody:'awaiting_intake',docket:'SYN-34',weight_grams:800,confirmed_at:now,sender:{source_customer_id:id(10),source_customer_version:1,name:'Synthetic Sender',phone:'+12025550100',phone_display:'+1 202-555-0100',address:'Synthetic address'},recipient:{name:'Synthetic Recipient',phone_normalized:'+12025550101',phone_display:'+1 202-555-0101',address:'Synthetic destination'}};
const lot={id:lotId,code:'LOT-SYN-34',name:'Synthetic East',destination_key:'SYN-EAST',state:'active',version:1,created_at:now,updated_at:now,archived_at:null,active_member_count:1};
const route={id:routeId,origin:'Synthetic Origin',destination:'Synthetic Destination',mode:'road',carrier_code:null,scheduled_departure_at:now,state:'finalized',version:4,current_manifest_id:manifestId,created_at:now,updated_at:now};
const state={reference_state:'recorded',official_validity_state:'unknown',estimate_state:'estimated',verification_state:'unverified_external',verified_at:null,applicability_state:'unknown',value_check_state:'unknown',reminder_reasons:['official_validity_unknown'],evaluated_at:now,policy:{state:'approved',id:id(20),version:1,effective_from:now,source_ref:'SYN-POLICY',approval_ref:'SYN-APPROVAL'}};

afterEach(()=>{vi.unstubAllGlobals();});

describe('production operational adapters',()=>{
 it('projects parcel data, rejects malformed success and binds exact scoped command identity',async()=>{
  const fetcher=vi.fn().mockResolvedValueOnce(json(page([{...parcel,private_secret:'discard'}]))).mockResolvedValueOnce(json(page([{...parcel,status:'invented'}])));vi.stubGlobal('fetch',fetcher);const scope=controller(),source=parcels(scopedApi(scope));
  const value=await source.list({docket:'SYN-34',status:'booked'});expect(value.items[0]).toEqual(parcel);expect(JSON.stringify(value)).not.toContain('private_secret');expect(String(fetcher.mock.calls[0][0])).toContain(`organization_id=${org}&franchise_id=${franchise}&docket=SYN-34&status=booked`);
  await expect(source.list()).rejects.toMatchObject({kind:'protocol'});const intent=source.intent({kind:'check_in',parcelId,body:{expected_version:1,evidence_ref:id(11),location_ref:id(12)}});expect(intent).toMatchObject({operation:'api.v1.parcels.check_in',expectedVersion:1});expect(intent.path).toContain(`/api/v1/parcels/${parcelId}/check-in`);
 });
 it('builds versioned lot/route/e-way intents and accepts the restricted accountant e-way projection',async()=>{
  const restricted={booking_id:bookingId,record:{record_id:id(30),booking_id:bookingId,version:2,declaration:{value_paise:5000,source_ref:'SYN-DECL'},external:{issuer:'synthetic_portal',reference:'AB-7',source_ref:null,issued_at:null,official_valid_until:null,validity_evidence_ref:null,provenance:'external_observation',verification_state:'unverified_external',verified_at:null},estimate:null,captured_at:now},state};vi.stubGlobal('fetch',vi.fn().mockResolvedValue(json({...restricted,private_vehicle:'discard'})));const api=scopedApi(controller()),lotSource=lots(api),routeSource=routes(api),ewaySource=eway(api);
  expect(lotSource.intent({kind:'remove',lotId,parcelId,body:{expected_version:3,membership_id:membershipId}})).toMatchObject({operation:'api.v1.lots.membership.remove',expectedVersion:3});
  expect(routeSource.intent({kind:'event',routeId,body:{kind:'delay',expected_version:4,manifest_id:manifestId,manifest_version:2,effective_at:now,evidence_ref:id(31),total_delay_minutes:45}})).toMatchObject({operation:'api.v1.routes.event',expectedVersion:4});
  expect(ewaySource.intent({kind:'estimate',bookingId,body:{expected_version:2,reason_ref:'SYN-REASON',starts_at:now}})).toMatchObject({operation:'api.v1.eway.estimate',expectedVersion:2});
  const value=await ewaySource.read(bookingId);expect(value.record?.external?.reference).toBe('AB-7');expect(value.record?.vehicle_number).toBeUndefined();expect(JSON.stringify(value)).not.toContain('private_vehicle');
 });
});

describe('production operational screens',()=>{
 it('announces dashboard loading then renders bounded accessible cards and an honest empty result',async()=>{
  let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});vi.stubGlobal('fetch',vi.fn(async()=>{await gate;return json(page([]));}));render(<MemoryRouter><OperationsDashboard controller={controller()} roles={['operator']} workspaceName="Synthetic Counter"/></MemoryRouter>);
  expect(screen.getByRole('status')).toHaveTextContent('Loading operational workspace');await act(async()=>release());await screen.findByRole('heading',{name:'No records on the current pages'});expect(screen.getByRole('heading',{name:'Synthetic Counter'})).toBeVisible();expect(screen.getAllByRole('link')).toHaveLength(4);expect(screen.getAllByText('0').length).toBeGreaterThan(0);
 });
 it('offers controlled dashboard retry after an API failure without local fallback',async()=>{
  let failing=true;vi.stubGlobal('fetch',vi.fn(async()=>failing?json({error:{code:'TEMPORARILY_UNAVAILABLE'}},503):json(page([]))));render(<MemoryRouter><OperationsDashboard controller={controller()} roles={['operator']} workspaceName="Synthetic Counter"/></MemoryRouter>);expect(await screen.findByRole('alert')).toHaveTextContent('No local changes were made');failing=false;fireEvent.click(screen.getByRole('button',{name:/Retry/}));await screen.findByRole('heading',{name:'No records on the current pages'});expect(localStorage.length).toBe(0);
 });
 it('uses guarded package actions, omits OTP/delivered bypasses and refreshes To-Pay from a fresh ledger read',async()=>{
  let collected=false,paymentReads=0;const fetcher=vi.fn(async(path:string,options:RequestInit={})=>{if(path==='/auth/bootstrap')return json({csrf_token:'synthetic-csrf'});if(path.includes('/parcels?'))return json(page([parcel]));if(path.includes(`/parcels/${parcelId}/timeline`))return json({items:[]});if(path.includes(`/parcels/${parcelId}/lot-membership`))return json(null);if(path.includes(`/parcels/${parcelId}?`))return json(parcel);if(path.includes(`/bookings/${bookingId}/payments`)){if(options.method==='POST'){const body=JSON.parse(String(options.body));collected=true;return json({payment:{booking_id:bookingId,obligation_id:id(40),currency:'INR',gross_paise:10000,collected_paise:10000,outstanding_paise:0,state:'settled',version:2},entry:{id:id(41),kind:'collection',amount_paise:body.amount_paise,currency:'INR',context:'to_pay',method:'cash',collection_reference:body.collection_reference,reversal_of:null,reason_code:null,version:1,occurred_at:now}});}paymentReads++;return json({booking_id:bookingId,obligation_id:id(40),currency:'INR',gross_paise:10000,collected_paise:collected?10000:0,outstanding_paise:collected?0:10000,state:collected?'settled':'uncollected',version:collected?2:1});}throw new Error(`Unexpected ${path}`);});vi.stubGlobal('fetch',fetcher);render(<MemoryRouter><Packages controller={controller()} roles={['operator','franchise_admin']}/></MemoryRouter>);fireEvent.click(await screen.findByRole('button',{name:'Open'}));await screen.findByText('To-Pay ledger');expect(screen.getByRole('button',{name:'check in'})).toBeVisible();expect(screen.queryByText(/OTP/i)).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:/delivered/i})).not.toBeInTheDocument();
  fireEvent.change(screen.getByLabelText(/Amount received/),{target:{value:'100'}});fireEvent.click(screen.getByRole('button',{name:'Confirm money received'}));await screen.findByText('settled');expect(paymentReads).toBeGreaterThanOrEqual(2);
 });
 it('removes the exact lot membership with the keyboard-reachable action and confirms ungrouped from the server',async()=>{
  let removed=false;const member={id:membershipId,lot_id:lotId,parcel_id:parcelId,started_at:now,ended_at:null,end_reason:null};vi.stubGlobal('fetch',vi.fn(async(path:string,options:RequestInit={})=>{if(path==='/auth/bootstrap')return json({csrf_token:'synthetic-csrf'});if(path.includes('/lots?'))return json(page([{...lot,active_member_count:removed?0:1,version:removed?2:1}]));if(path.includes(`/lots/${lotId}/memberships`))return json(page(removed?[]:[member]));if(path.includes(`/lots/${lotId}?`))return json({...lot,active_member_count:removed?0:1,version:removed?2:1});if(path.includes(`/lots/${lotId}/parcels/${parcelId}/remove`)&&options.method==='POST'){removed=true;return json({lots:[{...lot,version:2,active_member_count:0}],membership:null});}if(path.includes(`/parcels/${parcelId}/lot-membership`))return json(null);throw new Error(`Unexpected ${path}`);}));render(<MemoryRouter><Lots controller={controller()} roles={['franchise_admin']}/></MemoryRouter>);fireEvent.click(await screen.findByRole('button',{name:'Open'}));const remove=await screen.findByRole('button',{name:'Remove'});remove.focus();expect(remove).toHaveFocus();fireEvent.click(remove);expect(await screen.findByText(/is now ungrouped/)).toHaveTextContent(parcelId);
 });
 it('re-reads and displays the server ETA after a full route component remount without inferring parcel delivery',async()=>{
  let revision=0,eventReads=0;const manifest={manifest:{id:manifestId,route_id:routeId,version:2,finalized:true,parcel_count:1,created_at:now},items:[{parcel_id:parcelId,sources:[{kind:'direct',source_id:id(50)}]}],page:{has_more:false,next_cursor:null}};vi.stubGlobal('fetch',vi.fn(async(path:string)=>{if(path.includes('/routes?'))return json(page([route]));if(path.includes(`/routes/${routeId}/parcels`))return json(manifest);if(path.includes(`/routes/${routeId}/events`)){eventReads++;return json({route_id:routeId,version:4,latest:{event_id:id(51),route_id:routeId,version:4,manifest_id:manifestId,manifest_version:2,kind:'delay',effective_at:now,updated_count:1,skipped_count:0,eta:{state:'available',base_at:now,revised_at:revision?'2099-01-01T02:00:00.000Z':'2099-01-01T01:00:00.000Z',total_delay_minutes:revision?120:60}}});}if(path.includes(`/routes/${routeId}?`))return json(route);throw new Error(`Unexpected ${path}`);}));const first=render(<MemoryRouter><Routes controller={controller()} roles={['read_only']}/></MemoryRouter>);fireEvent.click(await screen.findByRole('button',{name:'Open'}));await screen.findByText('60 min');expect(screen.queryByRole('button',{name:/delivered/i})).not.toBeInTheDocument();first.unmount();revision=1;render(<MemoryRouter><Routes controller={controller()} roles={['read_only']}/></MemoryRouter>);fireEvent.click(await screen.findByRole('button',{name:'Open'}));await screen.findByText('120 min');expect(eventReads).toBe(2);
 });
 it('separates official e-way validity from a labelled estimate and renders an unverified short external reference',async()=>{
  const record={record_id:id(60),booking_id:bookingId,version:2,declaration:null,external:{issuer:'synthetic_portal',reference:'AB-7',source_ref:null,issued_at:null,official_valid_until:null,validity_evidence_ref:null,provenance:'external_observation',verification_state:'unverified_external',verified_at:null},estimate:{estimated_valid_until:'2099-01-02T00:00:00.000Z',estimate_policy_id:id(20),estimate_policy_version:1,provenance:'shippingco_estimate',label:'ShippingCo estimate — verify on the government portal'},captured_at:now};const reminder={booking_id:bookingId,record_id:record.record_id,version:2,external_reference:'AB-7',state};vi.stubGlobal('fetch',vi.fn(async(path:string)=>{if(path.includes('/eway/reminders'))return json(page([reminder]));if(path.includes(`/bookings/${bookingId}/eway/history`))return json(page([record]));if(path.includes(`/bookings/${bookingId}/eway`))return json({booking_id:bookingId,record,state});throw new Error(`Unexpected ${path}`);}));render(<MemoryRouter><Eway controller={controller()} roles={['accountant']}/></MemoryRouter>);fireEvent.click(await screen.findByRole('button',{name:'Open'}));expect((await screen.findAllByText('AB-7')).length).toBeGreaterThan(0);expect(screen.getByText('unverified external')).toBeVisible();expect(screen.getByText('ShippingCo estimate — verify on the government portal')).toBeVisible();expect(screen.getAllByText('Unknown').length).toBeGreaterThan(0);expect(screen.queryByText(/12 digit/i)).not.toBeInTheDocument();
 });
});
