import type {CashLocationDto,CashLocationInput,CashbookRequestInput,CashbookRequestDto,CashbookDecisionDto,CashbookRequestDetail,CashbookApplyInput,CashbookEffectDto,CashbookPositionSnapshot,CashHandoverInput,CashHandoverCommandInput,CashHandoverDetail,CashbookReportPage} from '@shippingco/shared';
import {object,uuid,text,instant,integer,choice,array,nullable,optional,protocol,type Decoder} from './dto';
import type {ScopedApi} from './scoped-api';
import type {CommandIntent} from './command-intent';
const method=choice('cash','upi','card','bank_transfer','other'),kind=choice('expense','opening_float','owner_funds','deposit','withdrawal'),category=choice('rent','utilities','supplies','transport','maintenance','other'),state=choice('requested','approved','rejected','applied');
const amount:Decoder<string>=v=>typeof v==='string'&&/^(?:0|[1-9][0-9]{0,24})$/.test(v)?v:protocol(),signed:Decoder<string>=v=>typeof v==='string'&&/^(?:0|-?[1-9][0-9]{0,24})$/.test(v)?v:protocol();
const leg=object({location_id:uuid,direction:choice('in','out'),amount_paise:amount});
const locationShape=object({id:uuid,revision_id:uuid,version:integer(1),name:text,active:choice(true,false),kind:choice('cash','noncash'),account_id:uuid,account_revision_id:uuid,account_version:integer(1),methods:array(method,4),custodian_id:nullable(uuid),recorded_at:instant});
const location:Decoder<CashLocationDto>=value=>{const r=locationShape(value);if(!r.methods.length||new Set(r.methods).size!==r.methods.length||(r.kind==='cash')!==(r.custodian_id!==null)||(r.kind==='cash')!==(r.methods.length===1&&r.methods[0]==='cash'))return protocol();return r;};
const requestShape=object({id:uuid,actor_id:uuid,recorded_at:instant,payment_method:optional(nullable(method)),correction_of:optional(nullable(uuid)),kind,source_location_id:uuid,source_revision_id:uuid,target_location_id:nullable(uuid),target_revision_id:nullable(uuid),expected_source_version:integer(),amount_paise:integer(),currency:choice('INR'),category:nullable(category),payee:nullable(text),responsible_employee_id:uuid,reason:text,occurred_at:instant});
export const cashbookRequest:Decoder<CashbookRequestDto>=value=>{const r=requestShape(value),paired=r.kind==='deposit'||r.kind==='withdrawal';if(paired!==(r.target_location_id!==null)||paired!==(r.target_revision_id!==null)||r.target_location_id===r.source_location_id||(r.kind==='expense')!==(r.payment_method!=null)||(r.kind==='expense')!==(r.category!==null)||(r.kind==='expense')!==(r.payee!==null)||!r.correction_of&&r.amount_paise===0)return protocol();return r;};
const digest:Decoder<string>=v=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v)?v:protocol();
const decision:Decoder<CashbookDecisionDto>=object({id:uuid,request_id:uuid,decision:choice('approved','rejected'),reason:text,actor_id:uuid,recorded_at:instant,version:choice(2),attachments:optional(array(object({id:uuid,version:integer(1),sha256:digest}),10))});
const effectShape=object({id:uuid,request_id:uuid,decision_id:uuid,actor_id:uuid,recorded_at:instant,version:choice(3),legs:array(leg,2)});
export const cashbookEffect:Decoder<CashbookEffectDto>=value=>{const r=effectShape(value);if(r.legs.some(l=>BigInt(l.amount_paise)===0n)||new Set(r.legs.map(l=>l.location_id)).size!==r.legs.length||r.legs.length===2&&(r.legs[0]!.direction===r.legs[1]!.direction||r.legs[0]!.amount_paise!==r.legs[1]!.amount_paise))return protocol();return r;};
const detailShape=object({request:cashbookRequest,decision:nullable(decision),effect:nullable(cashbookEffect),version:choice(1,2,3)});
export const cashbookDetail:Decoder<CashbookRequestDetail>=value=>{const r=detailShape(value);if(r.version!==(r.effect?3:r.decision?2:1)||r.decision&&(r.decision.request_id!==r.request.id||r.decision.actor_id===r.request.actor_id)||r.effect&&(!r.decision||r.decision.decision!=='approved'||r.effect.request_id!==r.request.id||r.effect.decision_id!==r.decision.id))return protocol();return r;};
const positionShape=object({as_of:instant,source_version:integer(),unknown_sources:integer(),locations:array(object({location_id:uuid,known_inflows_paise:amount,known_outflows_paise:amount,known_recorded_paise:signed,available_paise:amount,pending_reserved_paise:amount,shortfall_paise:amount,unknown_sources:integer(),state:choice('recorded','incomplete','exception')}),1000)});
export const cashbookPosition:Decoder<CashbookPositionSnapshot>=value=>{const r=positionShape(value);if(new Set(r.locations.map(l=>l.location_id)).size!==r.locations.length)return protocol();for(const l of r.locations){const recorded=BigInt(l.known_recorded_paise),reserved=BigInt(l.pending_reserved_paise),available=recorded-reserved,shortfall=available<0n?-available:0n;if(BigInt(l.known_inflows_paise)-BigInt(l.known_outflows_paise)!==recorded||BigInt(l.shortfall_paise)!==shortfall||BigInt(l.available_paise)>(available>0n?available:0n)||l.state!==(shortfall>0n?'exception':l.unknown_sources?'incomplete':'recorded'))return protocol();}return r;};
const item=object({id:uuid,payment_method:nullable(method),kind,category:nullable(category),amount_paise:integer(),currency:choice('INR'),source_location_id:uuid,target_location_id:nullable(uuid),responsible_employee_id:uuid,actor_id:uuid,occurred_at:instant,recorded_at:instant,state,version:choice(1,2,3),correction_of:nullable(uuid),corrected_by:nullable(uuid)});
const inboxShape=object({as_of:instant,items:array(item),next_cursor:nullable(uuid),current_source_version:integer()});
const inbox:Decoder<ReturnType<typeof inboxShape>>=value=>{const r=inboxShape(value);if(new Set(r.items.map(x=>x.id)).size!==r.items.length||r.items.some(x=>x.version!==(x.state==='applied'?3:x.state==='requested'?1:2)||(x.kind==='expense')!==(x.payment_method!==null)||(x.kind==='expense')!==(x.category!==null)||(x.kind==='deposit'||x.kind==='withdrawal')!==(x.target_location_id!==null)||x.target_location_id===x.source_location_id||!x.correction_of&&x.amount_paise===0))return protocol();return r;};
const handoverRequest=object({id:uuid,actor_id:uuid,recorded_at:instant,version:choice(1),source_location_id:uuid,source_revision_id:uuid,target_location_id:uuid,target_revision_id:uuid,expected_source_version:integer(),amount_paise:integer(1),currency:choice('INR'),reason:text,occurred_at:instant});
const validHandover=(r:{amount_paise:number;accepted_paise:number;remaining_paise:number;ended_paise:number;state:string;version:number})=>BigInt(r.accepted_paise)+BigInt(r.remaining_paise)+BigInt(r.ended_paise)===BigInt(r.amount_paise)&&(r.state==='requested'?r.version===1&&r.accepted_paise===0&&r.ended_paise===0:r.version>=2&&(r.state==='partially_accepted'?r.accepted_paise>0&&r.remaining_paise>0&&r.ended_paise===0:r.state==='accepted'?r.remaining_paise===0&&r.ended_paise===0:r.remaining_paise===0&&r.ended_paise>0));
const hstate=choice('requested','partially_accepted','accepted','rejected','cancelled'),command=object({id:uuid,handover_id:uuid,version:integer(2),kind:choice('accept','reject','cancel'),amount_paise:integer(),currency:choice('INR'),reason:text,actor_id:uuid,recorded_at:instant,accepted_paise:integer(),remaining_paise:integer(),ended_paise:integer(),state:choice('partially_accepted','accepted','rejected','cancelled'),legs:array(leg,2)});
const handoverShape=object({request:handoverRequest,version:integer(1),accepted_paise:integer(),remaining_paise:integer(),ended_paise:integer(),state:hstate,current_source_version:integer(),commands:array(command),next_cursor:nullable(integer(1))});
export const cashHandoverDetail:Decoder<CashHandoverDetail>=value=>{const r=handoverShape(value);if(!validHandover({...r,amount_paise:r.request.amount_paise})||r.request.source_location_id===r.request.target_location_id||BigInt(r.accepted_paise)+BigInt(r.remaining_paise)+BigInt(r.ended_paise)!==BigInt(r.request.amount_paise)||new Set(r.commands.map(c=>c.version)).size!==r.commands.length)return protocol();for(const c of r.commands){if(!validHandover({...c,amount_paise:r.request.amount_paise})||(c.kind==='accept'?(c.state!=='accepted'&&c.state!=='partially_accepted'||c.accepted_paise<c.amount_paise):c.state!==(c.kind==='reject'?'rejected':'cancelled'))||c.version===r.version&&['state','accepted_paise','remaining_paise','ended_paise'].some(k=>c[k as 'state']!==r[k as 'state']))return protocol();if(c.handover_id!==r.request.id||c.version>r.version||BigInt(c.accepted_paise)+BigInt(c.remaining_paise)+BigInt(c.ended_paise)!==BigInt(r.request.amount_paise))return protocol();if(c.kind==='accept'?(c.amount_paise<1||c.legs.length!==2||!c.legs.some(l=>l.location_id===r.request.source_location_id&&l.direction==='out'&&l.amount_paise===String(c.amount_paise))||!c.legs.some(l=>l.location_id===r.request.target_location_id&&l.direction==='in'&&l.amount_paise===String(c.amount_paise))):(c.amount_paise!==0||c.legs.length!==0))return protocol();}return r;};
const targets=object({source_location_id:uuid,source_revision_id:uuid,current_source_version:integer(),items:array(object({id:uuid,revision_id:uuid,name:text,custodian_id:uuid})),next_cursor:nullable(uuid)});
const handoverInboxShape=object({items:array(object({id:uuid,source_location_id:uuid,target_location_id:uuid,actor_id:uuid,amount_paise:integer(1),accepted_paise:integer(),remaining_paise:integer(),ended_paise:integer(),version:integer(1),state:hstate,occurred_at:instant,recorded_at:instant})),next_cursor:nullable(uuid),current_source_version:integer()});
const handoverInbox:Decoder<ReturnType<typeof handoverInboxShape>>=value=>{const r=handoverInboxShape(value);if(new Set(r.items.map(x=>x.id)).size!==r.items.length||r.items.some(x=>!validHandover(x)||x.source_location_id===x.target_location_id))return protocol();return r;};
const sourceKind=choice('receipt','refund','refund_correction','legacy_collection','legacy_collection_correction','expense','opening_float','owner_funds','deposit','withdrawal','correction','handover');
const reportFilter=object({from_day:text,to_day:text,sort:choice('occurred_asc','occurred_desc'),payment_method:nullable(method),kind:nullable(sourceKind),location_id:nullable(uuid)});
const totals=object({count:integer(),known_inflows_paise:amount,known_outflows_paise:amount,known_net_paise:signed,unknown_inflows_paise:amount,unknown_outflows_paise:amount,unknown_sources:integer()});
const snapshot=object({id:uuid,schema_version:choice(1),definition:choice('cashbook_sources_v1'),organization_id:uuid,franchise_id:uuid,timezone:choice('Asia/Kolkata'),filter:reportFilter,as_of:instant,expires_at:instant,count:integer(),totals,position:cashbookPosition});
const sourceRow=object({payment_method:nullable(method),id:text,source_kind:sourceKind,source_id:uuid,location_id:nullable(uuid),account_id:nullable(uuid),direction:choice('in','out'),amount_paise:amount,occurred_at:instant,recorded_at:instant,actor_id:uuid,request_id:nullable(uuid),correction_of:nullable(uuid),unknown_reason:nullable(text)});
const reportShape=object({snapshot,rows:array(sourceRow),next_offset:nullable(integer(1))});
export const cashbookReportPage:Decoder<CashbookReportPage>=value=>{const r=reportShape(value),s=r.snapshot;if(s.count!==s.totals.count||s.count<r.rows.length||s.position.as_of!==s.as_of||BigInt(s.totals.known_inflows_paise)-BigInt(s.totals.known_outflows_paise)!==BigInt(s.totals.known_net_paise)||new Set(r.rows.map(x=>x.id)).size!==r.rows.length||r.next_offset!==null&&r.next_offset>=s.count)return protocol();for(const row of r.rows){if(row.id!==`${row.source_kind}:${row.source_id}:${row.location_id??'unknown'}`||BigInt(row.amount_paise)===0n||(row.location_id===null)!==(row.unknown_reason!==null)||s.filter.kind!==null&&row.source_kind!==s.filter.kind||s.filter.payment_method!==null&&row.payment_method!==s.filter.payment_method||s.filter.location_id!==null&&row.location_id!==s.filter.location_id)return protocol();}if(s.count===r.rows.length){const known=r.rows.filter(x=>x.location_id!==null),unknown=r.rows.filter(x=>x.location_id===null),sum=(rows:typeof r.rows,direction:string)=>rows.filter(x=>x.direction===direction).reduce((n,x)=>n+BigInt(x.amount_paise),0n);if(sum(known,'in')!==BigInt(s.totals.known_inflows_paise)||sum(known,'out')!==BigInt(s.totals.known_outflows_paise)||sum(unknown,'in')!==BigInt(s.totals.unknown_inflows_paise)||sum(unknown,'out')!==BigInt(s.totals.unknown_outflows_paise)||unknown.length!==s.totals.unknown_sources||r.next_offset!==null)return protocol();}return r;};
function filter(query:Record<string,string|undefined>={}){const p=new URLSearchParams();for(const [k,v] of Object.entries(query))if(v!==undefined&&v!=='')p.set(k,v);return p.size?'&'+p:'';}
export function cashbook(api:ScopedApi){const path='/api/v1/cashbook',at=(suffix:string)=>api.path(path+suffix);return {
 capture:(input:{from_day:string;to_day:string;sort?:'occurred_asc'|'occurred_desc';payment_method?:string|null;kind?:string|null;location_id?:string|null})=>api.intent('cashbook.capture',at('/snapshots'),input),
 executeCapture:(intent:CommandIntent)=>api.execute(intent,value=>{const r=cashbookReportPage(value),sent=JSON.parse(intent.bodyJson);if(r.snapshot.organization_id!==api.organization||r.snapshot.franchise_id!==api.franchise||r.snapshot.filter.from_day!==sent.from_day||r.snapshot.filter.to_day!==sent.to_day||r.snapshot.filter.sort!==(sent.sort??'occurred_asc')||['payment_method','kind','location_id'].some(k=>r.snapshot.filter[k as 'kind']!==(sent[k]??null)))return protocol();return r;}),
 report:(id:string,offset=0,signal?:AbortSignal)=>api.read(at('/snapshots/'+uuid(id))+filter({offset:String(integer()(offset))}),value=>{const r=cashbookReportPage(value);if(r.snapshot.id!==id||r.snapshot.organization_id!==api.organization||r.snapshot.franchise_id!==api.franchise||r.rows.length!==Math.min(100,Math.max(0,r.snapshot.count-offset))||r.next_offset!==(offset+r.rows.length<r.snapshot.count?offset+r.rows.length:null))return protocol();return r;},signal),
 reportDetail:(id:string,rowId:string,signal?:AbortSignal)=>api.read(at('/snapshots/'+uuid(id)+'/rows/'+encodeURIComponent(text(rowId))),value=>{const r=object({snapshot,row:sourceRow})(value);if(r.snapshot.id!==id||r.row.id!==rowId||r.snapshot.organization_id!==api.organization||r.snapshot.franchise_id!==api.franchise)return protocol();return r;},signal),
 export:(id:string,signal?:AbortSignal)=>api.read(at('/snapshots/'+uuid(id)+'/export'),value=>{const csv:Decoder<string>=v=>typeof v==='string'&&v.length<=8*1024*1024?v:protocol(),r=object({snapshot,csv})(value);if(r.snapshot.id!==id||r.snapshot.organization_id!==api.organization||r.snapshot.franchise_id!==api.franchise)return protocol();return r;},signal),
 locations:(cursor?:string,signal?:AbortSignal)=>api.read(at('/locations')+filter({cursor}),value=>{const r=object({items:array(location),next_cursor:nullable(uuid)})(value);if(new Set(r.items.map(l=>l.id)).size!==r.items.length||r.items.some(l=>!l.methods.length||new Set(l.methods).size!==l.methods.length||(l.kind==='cash')!==(l.custodian_id!==null)||(l.kind==='cash')!==(l.methods.length===1&&l.methods[0]==='cash')))return protocol();return r;},signal),
 location:(id:string,signal?:AbortSignal)=>api.read(at('/locations/'+uuid(id)),value=>{const r=location(value);return r.id===id?r:protocol();},signal),
 configure:(id:string|null,input:CashLocationInput)=>api.intent('cashbook.configure',at('/locations'+(id?'/'+uuid(id)+'/revisions':'')),input),
 position:(signal?:AbortSignal)=>api.read(at('/position'),cashbookPosition,signal),
 requests:(query:{state?:string;cursor?:string;kind?:string;source_location_id?:string}={},signal?:AbortSignal)=>api.read(at('/requests')+filter(query),inbox,signal),
 detail:(id:string,signal?:AbortSignal)=>api.read(at('/requests/'+uuid(id)),value=>{const r=cashbookDetail(value);return r.request.id===id?r:protocol();},signal),
 submit:(input:CashbookRequestInput)=>api.intent('cashbook.request',at('/requests'),input),
 decide:(id:string,input:{decision:'approved'|'rejected';reason:string;expected_version:1})=>api.intent('cashbook.decide',at('/requests/'+uuid(id)+'/decisions'),input),
 apply:(id:string,input:CashbookApplyInput)=>api.intent('cashbook.apply',at('/requests/'+uuid(id)+'/apply'),input),
 executeConfigure:(intent:CommandIntent)=>api.execute(intent,value=>{const r=location(value),sent=JSON.parse(intent.bodyJson) as CashLocationInput;if(intent.operation!=='cashbook.configure'||sent.expected_version>0&&!intent.path.includes('/'+r.id+'/revisions')||r.version!==sent.expected_version+1||r.account_id!==sent.account_id||r.account_version!==sent.expected_account_version||r.custodian_id!==sent.custodian_id||r.name!==sent.name.trim()||r.active!==sent.active)return protocol();return r;}),
 executeRequest:(intent:CommandIntent)=>api.execute(intent,value=>{const r=cashbookRequest(value),sent=JSON.parse(intent.bodyJson) as CashbookRequestInput;if(r.actor_id!==api.scope.authority?.userId||Object.entries(sent).some(([k,v])=>JSON.stringify(r[k as keyof CashbookRequestDto]??null)!==JSON.stringify(v??null)))return protocol();return r;}),
 executeDecision:(intent:CommandIntent)=>api.execute(intent,value=>{const r=decision(value),sent=JSON.parse(intent.bodyJson);if(!intent.path.includes('/'+r.request_id+'/decisions')||r.actor_id!==api.scope.authority?.userId||r.decision!==sent.decision||r.reason!==sent.reason)return protocol();return r;}),
 executeApply:(intent:CommandIntent)=>api.execute(intent,value=>{const r=cashbookEffect(value),sent=JSON.parse(intent.bodyJson);if(!intent.path.includes('/'+r.request_id+'/apply')||r.actor_id!==api.scope.authority?.userId||r.decision_id!==sent.decision_id)return protocol();return r;}),
 handovers:(cursor?:string,signal?:AbortSignal)=>api.read(at('/handovers')+filter({cursor}),handoverInbox,signal),
 handover:(id:string,beforeVersion?:number,signal?:AbortSignal)=>api.read(at('/handovers/'+uuid(id))+filter({before_version:beforeVersion===undefined?undefined:String(beforeVersion)}),value=>{const r=cashHandoverDetail(value);return r.request.id===id?r:protocol();},signal),
 targets:(id:string,cursor?:string,signal?:AbortSignal)=>api.read(at('/locations/'+uuid(id)+'/handover-targets')+filter({cursor}),value=>{const r=targets(value);return r.source_location_id===id&&!r.items.some(x=>x.id===id)&&new Set(r.items.map(x=>x.id)).size===r.items.length?r:protocol();},signal),
 requestHandover:(input:CashHandoverInput)=>api.intent('cashbook.handover.request',at('/handovers'),input),
 respondHandover:(id:string,input:CashHandoverCommandInput)=>api.intent('cashbook.handover.respond',at('/handovers/'+uuid(id)+'/commands'),input),
 executeHandover:(intent:CommandIntent)=>api.execute(intent,value=>{if(intent.operation==='cashbook.handover.request'){const r=handoverRequest(value),sent=JSON.parse(intent.bodyJson);if(r.actor_id!==api.scope.authority?.userId||Object.entries(sent).some(([k,v])=>r[k as keyof typeof r]!==v))return protocol();return r;}const r=command(value),sent=JSON.parse(intent.bodyJson);if(r.kind==='accept'?(r.amount_paise<1||r.legs.length!==2||new Set(r.legs.map(l=>l.location_id)).size!==2||new Set(r.legs.map(l=>l.direction)).size!==2||r.legs.some(l=>l.amount_paise!==String(r.amount_paise))):(r.amount_paise!==0||r.legs.length!==0))return protocol();if(!intent.path.includes('/'+r.handover_id+'/commands')||r.actor_id!==api.scope.authority?.userId||r.version!==sent.expected_version+1||r.kind!==sent.kind||r.amount_paise!==sent.amount_paise||r.reason!==sent.reason)return protocol();return r;}),
};}
export type CashbookSource=ReturnType<typeof cashbook>;
