import type { CommandIntent } from './command-intent';
import { array, choice, instant, integer, list, nullable, object, optional, text, uuid, type Decoder, protocol } from './dto';
import type { ScopedApi } from './scoped-api';

export interface EwayDeclaration {value_paise:number;source_ref:string}
export interface EwayExternal {issuer:string;reference:string;source_ref:string|null;issued_at:string|null;official_valid_until:string|null;validity_evidence_ref:string|null;provenance:'external_observation';verification_state:'unverified_external';verified_at:null}
export interface EwayEstimate {estimated_valid_until:string;estimate_policy_id:string;estimate_policy_version:number;estimate_inputs?:{distance_km:number;starts_at:string;block_km:number;block_seconds:number};estimate_calculated_at?:string;provenance:'shippingco_estimate';label:'ShippingCo estimate — verify on the government portal'}
export interface EwayRecord {record_id:string;booking_id:string;version:number;declaration:EwayDeclaration|null;external:EwayExternal|null;estimate:EwayEstimate|null;captured_at:string;vehicle_number?:string|null;distance_km?:number|null;captured_by?:string;reason_code?:string;reason_ref?:string|null}
export interface EwayState {reference_state:'missing'|'recorded';official_validity_state:'unknown'|'source_supported'|'expired';estimate_state:'absent'|'estimated'|'expired';verification_state:'not_recorded'|'unverified_external';verified_at:null;applicability_state:'unknown';value_check_state:'unknown'|'below_threshold'|'threshold_met';reminder_reasons:string[];evaluated_at:string;policy:{state:'approved'|'no_approved_policy';id:string|null;version:number|null;effective_from:string|null;source_ref:string|null;approval_ref:string|null}}
export interface EwayCurrent {booking_id:string;record:EwayRecord|null;state:EwayState}
export interface EwayReminder {booking_id:string;record_id:string|null;version:number|null;external_reference:string|null;state:EwayState}
export type EwayCapture={declaration:EwayDeclaration|null;external:{issuer:string;reference:string;source_ref:string|null;issued_at:string|null;official_valid_until:string|null;validity_evidence_ref:string|null}|null;vehicle_number:string|null;distance_km:number|null};
export type EwayCommand={kind:'create';bookingId:string;body:Partial<EwayCapture>}|{kind:'correct';bookingId:string;body:Partial<EwayCapture>&{expected_version:number;reason_code:'metadata_correction'|'source_extension'|'declaration_correction';reason_ref:string}}|{kind:'estimate';bookingId:string;body:{expected_version:number;reason_ref:string;starts_at:string}};

const declaration:Decoder<EwayDeclaration>=object({value_paise:integer(),source_ref:text});
const neverVerified:Decoder<null>=value=>value===null?null:protocol();
const external:Decoder<EwayExternal>=object({issuer:text,reference:text,source_ref:nullable(text),issued_at:nullable(instant),official_valid_until:nullable(instant),validity_evidence_ref:nullable(text),provenance:choice('external_observation'),verification_state:choice('unverified_external'),verified_at:neverVerified});
const estimateInputs=object({distance_km:integer(1),starts_at:instant,block_km:integer(1),block_seconds:integer(1)});
const estimate:Decoder<EwayEstimate>=object({estimated_valid_until:instant,estimate_policy_id:uuid,estimate_policy_version:integer(1),estimate_inputs:optional(estimateInputs),estimate_calculated_at:optional(instant),provenance:choice('shippingco_estimate'),label:choice('ShippingCo estimate — verify on the government portal')});
const state:Decoder<EwayState>=object({reference_state:choice('missing','recorded'),official_validity_state:choice('unknown','source_supported','expired'),estimate_state:choice('absent','estimated','expired'),verification_state:choice('not_recorded','unverified_external'),verified_at:neverVerified,applicability_state:choice('unknown'),value_check_state:choice('unknown','below_threshold','threshold_met'),reminder_reasons:array(text,20),evaluated_at:instant,policy:object({state:choice('approved','no_approved_policy'),id:nullable(uuid),version:nullable(integer(1)),effective_from:nullable(instant),source_ref:nullable(text),approval_ref:nullable(text)})});
export const ewayRecord:Decoder<EwayRecord>=object({record_id:uuid,booking_id:uuid,version:integer(1),declaration:nullable(declaration),external:nullable(external),estimate:nullable(estimate),captured_at:instant,vehicle_number:optional(nullable(text)),distance_km:optional(nullable(integer(1))),captured_by:optional(uuid),reason_code:optional(text),reason_ref:optional(nullable(text))});
export const ewayCurrent:Decoder<EwayCurrent>=object({booking_id:uuid,record:nullable(ewayRecord),state});
const reminder:Decoder<EwayReminder>=object({booking_id:uuid,record_id:nullable(uuid),version:nullable(integer(1)),external_reference:nullable(text),state});
const result=object({booking_id:uuid,record_id:uuid,version:integer(1)});
const operations:Record<EwayCommand['kind'],string>={create:'api.v1.eway.create',correct:'api.v1.eway.correct',estimate:'api.v1.eway.estimate'};
export function eway(api:ScopedApi){return {
 reminders(filter:{limit?:number;cursor?:string|null}={},signal?:AbortSignal){const q=new URLSearchParams();for(const[k,v]of Object.entries(filter))if(v!==undefined&&v!==null)q.set(k,String(v));return api.read(api.path('/api/v1/eway/reminders')+(q.size?'&'+q:''),list(reminder),signal);},
 read(bookingId:string,signal?:AbortSignal){return api.read(api.path(`/api/v1/bookings/${uuid(bookingId)}/eway`),ewayCurrent,signal);},
 history(bookingId:string,filter:{limit?:number;cursor?:string|null}={},signal?:AbortSignal){const q=new URLSearchParams();for(const[k,v]of Object.entries(filter))if(v!==undefined&&v!==null)q.set(k,String(v));return api.read(api.path(`/api/v1/bookings/${uuid(bookingId)}/eway/history`)+(q.size?'&'+q:''),list(ewayRecord),signal);},
 intent(command:EwayCommand){const base=`/api/v1/bookings/${uuid(command.bookingId)}/eway`,path=command.kind==='estimate'?base+'/estimate':base,method=command.kind==='correct'?'PATCH':'POST',expected='expected_version'in command.body?command.body.expected_version:undefined;return api.intent(operations[command.kind],api.path(path),command.body,method,expected);},
 execute(intent:CommandIntent){if(!Object.values(operations).includes(intent.operation))return protocol();const bookingId=/\/bookings\/([0-9a-f-]{36})\/eway/.exec(intent.path)?.[1],body=JSON.parse(intent.bodyJson)as Record<string,unknown>;return api.execute(intent,value=>{const decoded=result(value),expected='expected_version'in body?Number(body.expected_version)+1:1;if(!bookingId||decoded.booking_id!==bookingId||decoded.version!==expected)return protocol();return decoded;},['$','declaration','external','vehicle_number','distance_km','expected_version','reason_code','reason_ref','starts_at']);},
};}
export type EwaySource=ReturnType<typeof eway>;
